
#ifndef NVP_MEMORYMAPPING_H_
#define NVP_MEMORYMAPPING_H_ 1

/******************************************************************************

AUTOLIV ELECTRONIC document.

-------------------------------------------------------------------------------

Copyright Autoliv Inc. All rights reserved.

*******************************************************************************
H-File Template Version: 
*******************************************************************************

Overview:
   This file Nvp_MemoryMapping.h is generated by the generate_NVPMemoryMappingh.py
   when using the eclipse plugin or directly the script

Date and time of generation of files: ::DATE::

******************************************************************************/
/* PRQA S 0288 ++ */
/*
 * Explanation:
 *    Disabled for MKS keywords
 */
/*
$Revision: 1.2 $
$ProjectName: e:/MKSProjects/SBE/eCS/AUDI_MCC/Phase_01/View_Development/Components/Application/Autoliv/NVP/Scripts/project.pj $
*/
/* PRQA S 0288 -- */
/*****************************************************************************/
/******************************************************************************
EXTERNAL DEPENDENCIES
******************************************************************************/

#include "Common.h"
#include "Platform_Types.h"

#ifdef __cplusplus
extern "C" {
#endif
/******************************************************************************
DEFINITION OF CONSTANTS
******************************************************************************/

#define NVP_KU8_MAJOR_VERSION_CALIB                        ( ::MAJOR_VERSION:: )
#define NVP_KU8_MINOR_VERSION_CALIB                        ( ::MINOR_VERSION:: )
#define NVP_KU8_SUBVERSION_CALIB                           ( ::SUBVERSION:: )

#define NVP_ROM_DEFAULT_START_ADDRESS                      (::ROM_START_ADDRESS::)
#define NVP_CALIBRATION_START_ADDRESS                      (::CALIBRATION_START_ADDRESS::)
#define NVP_SHADOW_RAM_START_ADDRESS                       (::RAM_SHADOW_START_ADDRESS::)

/******************************************************************************
DECLARATION OF TYPES
******************************************************************************/

/******************************************************************************
DECLARATION OF VARIABLES
******************************************************************************/

/******************************************************************************
DECLARATION OF CONSTANT DATA
******************************************************************************/

/******************************************************************************
DECLARATION OF FUNCTIONS
******************************************************************************/

/******************************************************************************
DECLARATION OF FUNCTION-LIKE MACROS
******************************************************************************/

#ifndef __RAM_SHADOW__
#define __RAM_SHADOW__(x)         (NVP_SHADOW_RAM_START_ADDRESS+x)
#else
#define __RAM_SHADOW__(x)
#endif
#ifndef __ROM_DEFAULT__
#define __ROM_DEFAULT__(x)        (NVP_ROM_DEFAULT_START_ADDRESS+x)
#else
#define __ROM_DEFAULT__(x)
#endif
#ifndef __CALIBRATION__
#define __CALIBRATION__(x)        (NVP_CALIBRATION_START_ADDRESS+x)
#else
#define __CALIBRATION__(x)
#endif

#ifdef __cplusplus
}
#endif
/******************************************************************************
End Of File
*****************************************************************************/

#endif /* _TEMPLATE_H_ */
