/**
 * \file
 *
 * \brief AUTOSAR Dem
 *
 * This file contains the implementation of the AUTOSAR
 * module Dem.
 *
 * \version 6.4.7
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2022 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */
#ifndef DEM_CFG_H
#define DEM_CFG_H

/* This file contains all target independent public configuration declarations
 * for the AUTOSAR module Dem. */



/*==================[includes]==============================================*/
/* !LINKSTO dsn.Dem.IncludeStr,1 */

#include <Rte_Dem_Type.h>        /* types generated by RTE */
#include <Dem_IntErrId.h>        /* BSW Event ID symbols */
#include <Dem_IntEvtId.h>        /* SW-C Event ID symbols */

#include <NvM.h>           /* NvM symbols */

/*==================[type definitions]======================================*/

#ifndef RTE_TYPE_Dem_EventIdType
#define RTE_TYPE_Dem_EventIdType
/**  \brief Defines the Dem Event ID which is
 **  identification of an event by assigned EventId
 **  In case the Rte is available this type is defined in Rte_Type.h.
 **/
typedef uint16 Dem_EventIdType;
#endif

/*==================[macros]================================================*/
#if (defined DEM_GENERAL_OBD)
#error DEM_GENERAL_OBD already defined
#endif
/** \brief Definition of DEM_GENERAL_OBD */
#define DEM_GENERAL_OBD STD_OFF


/** \brief Macro to define the dimension of Dem_OBDReadinessGroupMap[]
 ** and Dem_OBDReadinessGroup[] */

#if (defined DEM_CFG_SIGNATURE)
#error DEM_CFG_SIGNATURE is already defined
#endif
/* !LINKSTO Dem.EB.Config.Id,1 */
/** \brief Sign a certain configuration with unique hash
 **/
#define DEM_CFG_SIGNATURE 372401035U

#if (defined DEM_NVRAM_CONFIG_SIGNATURE_USED)
#error DEM_NVRAM_CONFIG_SIGNATURE_USED is already defined
#endif

/* !LINKSTO Dem.NvDataSignature.Config.Used,1 */
/** \brief Switch, Indicating a support of reset of NVRAM memory based on signature value
 **/
#define DEM_NVRAM_CONFIG_SIGNATURE_USED    STD_OFF

/*------------------[RTE configuration]-------------------------------------*/

#if (defined DEM_INCLUDE_RTE)
#error DEM_INCLUDE_RTE already defined
#endif
/** \brief Switch, indicating if RTE is available and can be used from Dem */
#define DEM_INCLUDE_RTE              STD_ON

#if (defined DEM_SERVICE_API_NONE)
#error DEM_SERVICE_API_NONE already defined
#endif
/** \brief Definition that no default service API is set */
#define DEM_SERVICE_API_NONE      0U

#if (defined DEM_SERVICE_API_ASR40)
#error DEM_SERVICE_API_ASR40 already defined
#endif
/** \brief Definition that AUTOSAR 4.0 service API is set as default */
#define DEM_SERVICE_API_ASR40     40U

#if (defined DEM_SERVICE_API_ASR42)
#error DEM_SERVICE_API_ASR42 already defined
#endif
/** \brief Definition that AUTOSAR 4.2 service API is set as default */
#define DEM_SERVICE_API_ASR42     42U

#if (defined DEM_SERVICE_API_ASR2011)
#error DEM_SERVICE_API_ASR2011 already defined
#endif
/** \brief Definition that AUTOSAR 20-11 service API is set as default */
#define DEM_SERVICE_API_ASR2011   2011U

#if (defined DEM_ENABLE_ASR40_SERVICE_API)
#error DEM_ENABLE_ASR40_SERVICE_API already defined
#endif
/** \brief Definition whether AUTOSAR 4.0 service API is enabled */
#define DEM_ENABLE_ASR40_SERVICE_API  STD_OFF

#if (defined DEM_ENABLE_ASR42_SERVICE_API)
#error DEM_ENABLE_ASR42_SERVICE_API already defined
#endif
/** \brief Definition whether AUTOSAR 4.2 service API is enabled */
#define DEM_ENABLE_ASR42_SERVICE_API  STD_ON

#if (defined DEM_ENABLE_ASR43_SERVICE_API)
#error DEM_ENABLE_ASR43_SERVICE_API already defined
#endif
/** \brief Definition whether AUTOSAR 4.3 service API is enabled */
#define DEM_ENABLE_ASR43_SERVICE_API  STD_OFF

#if (defined DEM_DEFAULT_ASR_SERVICE_API)
#error DEM_DEFAULT_ASR_SERVICE_API already defined
#endif
/** \brief Definition of default service API
 ** AUTOSAR_40: service APIs are fully based on the AUTOSAR 4.0 specification.
 ** AUTOSAR_42: some parts of the service APIs are based on the AUTOSAR 4.2
 ** specification the remaning APIs are still based on the AUTOSAR 4.0
 ** specification.
 ** AUTOSAR_43: uses AUTOSAR 4.2 as base, see above, plus some service APIs
 ** based on AUTOSAR 4.3.
 ** AUTOSAR_2011: uses AUTOSAR 4.2 as base, see above, plus some service APIs
 ** based on AUTOSAR 20-11.
 **/
#define DEM_DEFAULT_ASR_SERVICE_API DEM_SERVICE_API_ASR42

#if (defined DEM_USER_CTRL_WIR_SUPPORT)
#error DEM_USER_CTRL_WIR_SUPPORT already defined
#endif
/** \brief Switch, indicating if user controlled WIR-bit is enabled */
#define DEM_USER_CTRL_WIR_SUPPORT             STD_OFF

#if (defined DEM_DATA_ELEMENT_INTERFACE_WITH_EVENTID_SUPPORT)
#error DEM_DATA_ELEMENT_INTERFACE_WITH_EVENTID_SUPPORT already defined
#endif
/** \brief Switch, indicating if support for ReadData interface with
  * EventId parameter is enabled */
#define DEM_DATA_ELEMENT_INTERFACE_WITH_EVENTID_SUPPORT  STD_OFF

#if (defined DEM_SR_SUPPORT)
#error DEM_SR_SUPPORT already defined
#endif
/* !LINKSTO dsn.Dem.SRFunctionality.Support.Macro,1 */
/** \brief Switch, indicating if sender receiver interface is enabled */
#define DEM_SR_SUPPORT                        STD_OFF

/*------------------[DTC configuration]-------------------------------------*/

#if (defined DEM_NO_DTC)
#error DEM_NO_DTC already defined
#endif
/** \brief No DTC (neither UDS, OBD nor J1939) configured for event */
#define DEM_NO_DTC                 0U

#if (defined DEM_NO_DTC_FUNCTIONAL_UNIT)
#error DEM_NO_DTC_FUNCTIONAL_UNIT already defined
#endif
/** \brief No DTC functional unit configured for event */
#define DEM_NO_DTC_FUNCTIONAL_UNIT 0U

/*------------------[General]-----------------------------------------------*/

#if (defined DEM_VERSION_INFO_API)
#error DEM_VERSION_INFO_API already defined
#endif
/** \brief Switch, indicating if Version Info is activated for Dem */
#define DEM_VERSION_INFO_API                  STD_OFF

#if (defined DEM_CALIBRATION_SUPPORT)
#error DEM_CALIBRATION_SUPPORT already defined
#endif
/** \brief Switch for calibration support without event combination */
/* !LINKSTO dsn.Dem.Calibration.Support.Macro,1 */
#define DEM_CALIBRATION_SUPPORT               STD_OFF

#if (defined DEM_CALIBRATION_WITHEVCOMB_SUPPORT)
#error DEM_CALIBRATION_WITHEVCOMB_SUPPORT already defined
#endif
/** \brief Switch for calibration support with event combination */
#define DEM_CALIBRATION_WITHEVCOMB_SUPPORT STD_OFF

#if (defined DEM_INDICATORCLASS_SUPPORT)
#error DEM_INDICATORCLASS_SUPPORT already defined
#endif
/** \brief Switch for indicator class support */
#define DEM_INDICATORCLASS_SUPPORT STD_OFF


#if (defined DEM_POSITIVE_RESPONSE_NO_FFCLASSES)
#error DEM_POSITIVE_RESPONSE_NO_FFCLASSES already defined
#endif
/** \brief Switch for positive response when event has no FF assigned
 ** (disabled through calibration) */
/* !LINKSTO dsn.Dem.Calibration.NoFFClass.PositiveResponse,1 */
#define DEM_POSITIVE_RESPONSE_NO_FFCLASSES   STD_OFF

#if (defined DEM_CONSISTENT_FF_SIZE_SUPPORT)
#error DEM_CONSISTENT_FF_SIZE_SUPPORT already defined
#endif
/** \brief Switch for consistent FF size */
/* !LINKSTO dsn.Dem.Storage.ConsistentFFSize.Support,1 */
#define DEM_CONSISTENT_FF_SIZE_SUPPORT   STD_OFF


#if (defined DEM_COMMON_OPERATION_CYCLE_SUPPORT)
#error DEM_COMMON_OPERATION_CYCLE_SUPPORT already defined
#endif
/** \brief Switch for common operation cycle support */
/* !LINKSTO dsn.Dem.CommonOperationCycle.Support.Macro,1 */
#define DEM_COMMON_OPERATION_CYCLE_SUPPORT    STD_OFF

#if (defined DEM_AGINGALLOWED_CONVENIENT_CALIBRATION)
#error DEM_AGINGALLOWED_CONVENIENT_CALIBRATION already defined
#endif
/** \brief Switch to enable a convenient way of aging allowed calibration */
/* !LINKSTO dsn.Dem.Calibration.AgingAllowedConvenient.Macro,1 */
#define DEM_AGINGALLOWED_CONVENIENT_CALIBRATION       STD_OFF

#if (defined DEM_AGING_REQUIRES_TESTED_CYCLE_SET_OPERATION_CYCLE_STATE)
#error DEM_AGING_REQUIRES_TESTED_CYCLE_SET_OPERATION_CYCLE_STATE already defined
#endif
/** \brief Switch, indicating whether Dem_SetOperationCycleState() will consider or not the untested cyles */
#define DEM_AGING_REQUIRES_TESTED_CYCLE_SET_OPERATION_CYCLE_STATE    STD_OFF

#if (defined DEM_AGING_REQUIRES_TESTED_CYCLE_SET_AGING_CYCLE_STATE)
#error DEM_AGING_REQUIRES_TESTED_CYCLE_SET_AGING_CYCLE_STATE already defined
#endif
/** \brief Switch, indicating whether Dem_SetAgingCycleState() will consider or not the untested cyles */
#define DEM_AGING_REQUIRES_TESTED_CYCLE_SET_AGING_CYCLE_STATE        STD_OFF

#if (defined DEM_AGING_BASED_ON_HEALING_COMPLETION_SUPPORT)
#error DEM_AGING_BASED_ON_HEALING_COMPLETION_SUPPORT already defined
#endif
/** \brief Switch, indicating whether aging process should start only after healing is finished */
#define DEM_AGING_BASED_ON_HEALING_COMPLETION_SUPPORT    STD_OFF

#if (defined DEM_CB_TRIG_ON_EVDAT_ASR403)
#error DEM_CB_TRIG_ON_EVDAT_ASR403 already defined
#endif
/** \brief Switch, indicating whether EventDataChanged callback triggering behavior
 ** will be done according to ASR4.0.3 or or to ASR4.2.1 */
/* !LINKSTO dsn.Dem.CallbackEventDataChangedASR403.Macro,1 */
#define DEM_CB_TRIG_ON_EVDAT_ASR403    STD_OFF

#if (defined DEM_CB_EVST_CHANGED_OPCYC_START_SUPPORT)
#error DEM_CB_EVST_CHANGED_OPCYC_START_SUPPORT already defined
#endif
/** \brief Switch, indicating whether Dem_OpCycleProcessCycleStart() will trigger
 ** EventStatusChanged/DTCStatusChanged callback. */
/* !LINKSTO dsn.Dem.DemCallbackEventStatusChangedOpCycStartSupport.Macro,1 */
#define DEM_CB_EVST_CHANGED_OPCYC_START_SUPPORT    STD_ON

#if (defined DEM_NO_SUPPRESSION)
#error DEM_NO_SUPPRESSION already defined
#endif
#define DEM_NO_SUPPRESSION  0U

#if (defined DEM_DTC_SUPPRESSION)
#error DEM_DTC_SUPPRESSION already defined
#endif
#define DEM_DTC_SUPPRESSION  1U

#if (defined DEM_SUPPRESSION_SUPPORT)
#error DEM_SUPPRESSION_SUPPORT already defined
#endif
/** \brief Switch for DTC suppression support */
#define DEM_SUPPRESSION_SUPPORT           DEM_NO_SUPPRESSION

#if (defined DEM_NO_AVAILABILITY)
#error DEM_NO_AVAILABILITY already defined
#endif
#define DEM_NO_AVAILABILITY  0U

#if (defined DEM_EVENT_AVAILABILITY)
#error DEM_EVENT_AVAILABILITY already defined
#endif
#define DEM_EVENT_AVAILABILITY  1U

#if (defined DEM_AVAILABILITY_SUPPORT)
#error DEM_AVAILABILITY_SUPPORT already defined
#endif
/** \brief Switch for dynamic event availability support */
#define DEM_AVAILABILITY_SUPPORT          DEM_NO_AVAILABILITY

#if (defined DEM_EVENT_DISABLING_SUPPORT)
#error DEM_EVENT_DISABLING_SUPPORT already defined
#endif
/** \brief Switch for DTC availability support */
#define DEM_EVENT_DISABLING_SUPPORT           STD_OFF

#if (defined DEM_CLEAR_DTC_OF_DISABLED_EVENTS )
#error DEM_CLEAR_DTC_OF_DISABLED_EVENTS  already defined
#endif
/** \brief Switch to support clearing of DTCs for disabled events */
#define DEM_CLEAR_DTC_OF_DISABLED_EVENTS            STD_OFF

#if (defined DEM_MAX_NUM_CLEAR_EVENTS_PER_CYCLE )
#error DEM_MAX_NUM_CLEAR_EVENTS_PER_CYCLE  already defined
#endif
/** \brief Maximum number of events to be cleared per
 ** Dem_MainFunction() cycle on a ClearDTC request */
#define DEM_MAX_NUM_CLEAR_EVENTS_PER_CYCLE       3U

#if (defined DEM_EVENTCLASS_SUPPORT)
#error DEM_EVENTCLASS_SUPPORT already defined
#endif
/** \brief Switch for event class support */
#define DEM_EVENTCLASS_SUPPORT                STD_OFF

#if (defined DEM_DTC_STATUS_AVAILABILITY_MASK)
#error DEM_DTC_STATUS_AVAILABILITY_MASK already defined
#endif
/** \brief DTC status availability mask */
#define DEM_DTC_STATUS_AVAILABILITY_MASK    255U

#if (defined DEM_STATUS_BIT_STORAGE_TF_PER_EVENT_SUPPORT)
#error DEM_STATUS_BIT_STORAGE_TF_PER_EVENT_SUPPORT already defined
#endif


/** \brief macro is enabled only when all the events
 ** do not have same value */
#define DEM_STATUS_BIT_STORAGE_TF_PER_EVENT_SUPPORT  STD_OFF

#if (defined DEM_STATUS_BIT_STORAGE_TF)
#error DEM_STATUS_BIT_STORAGE_TF already defined
#endif
/** \brief Switch, indicating if permanent storage of the
 ** "TestFailed" status bit is activated */
#define DEM_STATUS_BIT_STORAGE_TF     STD_ON

#if (defined DEM_RESET_PENDING_BIT_ON_OVERFLOW_SUPPORT)
#error DEM_RESET_PENDING_BIT_ON_OVERFLOW_SUPPORT already defined
#endif
/** \brief Switch, indicating if the pending bit is reset or
 ** not while an event memory entry will be displaced */
#define DEM_RESET_PENDING_BIT_ON_OVERFLOW_SUPPORT     STD_ON

#if (defined DEM_RESET_CONFIRMED_BIT_ON_OVERFLOW_SUPPORT)
#error DEM_RESET_CONFIRMED_BIT_ON_OVERFLOW_SUPPORT already defined
#endif
/** \brief Switch, indicating if the confirmed bit is reset or
 ** not while an event memory entry will be displaced */
#define DEM_RESET_CONFIRMED_BIT_ON_OVERFLOW_SUPPORT     STD_ON

#if (defined DEM_UPDATE_OCCORDER_ON_EVENTENTRY_UPDATE)
#error DEM_UPDATE_OCCORDER_ON_EVENTENTRY_UPDATE already defined
#endif
/** \brief Switch, indicating whether the OccOrder shall be updated
 ** at every event entry update */
#define DEM_UPDATE_OCCORDER_ON_EVENTENTRY_UPDATE    STD_ON

#if (defined DEM_USE_PERMANENT_STORAGE)
#error DEM_USE_PERMANENT_STORAGE already defined
#endif
/** \brief Switch, indicating if Permanent storage of event
 ** memory entries in NvM is activated for
 ** Dem */
#define DEM_USE_PERMANENT_STORAGE             STD_ON

#if (defined DEM_OPCYC_NVSTORAGE)
#error DEM_OPCYC_NVSTORAGE already defined
#endif
/** \brief Switch, indicating if permanent storage of operation cycle entries
 ** to NVRAM is enabled */
#define DEM_OPCYC_NVSTORAGE                   STD_ON

#if (defined DEM_OPCYCLESTATE)
#error DEM_OPCYCLESTATE already defined
#endif
/** \brief Macro to get the operation cycle states based on permanent storage
 ** of operation cycle entries to NVRAM */
#define DEM_OPCYCLESTATE             Dem_NvData.OpCycleState

/* !LINKSTO Dem.OperationCyclePermStorage.FDC,1 */
#if (defined DEM_NUM_DEBOUNCE_COUNTER_PERM)
#error DEM_NUM_DEBOUNCE_COUNTER_PERM already defined
#endif
/** \brief Number of counter debounced events with permanent debounce
 ** counter storage
 **/
#define DEM_NUM_DEBOUNCE_COUNTER_PERM  2U

/* !LINKSTO dsn.Dem.FDCTriggerDebounceAlgorithm,1 */
#if (defined DEM_USE_TRIGGER_DEBOUNCE_BEHAVIOR)
#error DEM_USE_TRIGGER_DEBOUNCE_BEHAVIOR already defined
#endif
/** \brief Macro to get the the support for freeze/reset for time-based and
 ** frequency-based debouncing and counter-based reset behavior via non-fulfilled enable
 ** conditions and disabled DTCSettings.
 ** STD_ON: If at least one event is configured with counter-based RESET behavior or
 ** time/frequency-based debouncing and DemDebounceBehavior is set to RESET/FREEZE.
 **/
#define DEM_USE_TRIGGER_DEBOUNCE_BEHAVIOR   STD_OFF

#if (defined DEM_NVM_BLOCK_ID_INVALID)
#error DEM_NVM_BLOCK_ID_INVALID already defined
#endif
/** \brief NvM block Id does not exist as it is not configured */
#define DEM_NVM_BLOCK_ID_INVALID      0U



#if (defined DEM_NVM_BLOCK_ID_DEFAULT)
#error DEM_NVM_BLOCK_ID_DEFAULT already defined
#endif
/** \brief NvM block Id for block DEM_NVM_BLOCK_ID_DEFAULT */
#if defined (NvMConf_NvMBlockDescriptor_NVM_BLOCK_DEM_DEFAULT)
#define DEM_NVM_BLOCK_ID_DEFAULT NvMConf_NvMBlockDescriptor_NVM_BLOCK_DEM_DEFAULT
#elif defined (NvM_NVM_BLOCK_DEM_DEFAULT)
#define DEM_NVM_BLOCK_ID_DEFAULT NvM_NVM_BLOCK_DEM_DEFAULT
#elif defined (NVM_BLOCK_DEM_DEFAULT)
#define DEM_NVM_BLOCK_ID_DEFAULT NVM_BLOCK_DEM_DEFAULT
#else
#error No symbolic name for NvM block NVM_BLOCK_DEM_DEFAULT (refered by DEM_NVM_BLOCK_ID_DEFAULT) is generated
#endif

#if (defined DEM_NVM_BLOCK_ID_PERMANENT)
#error DEM_NVM_BLOCK_ID_PERMANENT already defined
#endif
/** \brief Invalid block Id for Dem permanent block as permanent memory is not configured */
#define DEM_NVM_BLOCK_ID_PERMANENT DEM_NVM_BLOCK_ID_INVALID

/** \brief Maximum number of events over all memory sources */

#if (defined DEM_MAX_NUM_ORDERED_EVENT_IDS)
#error DEM_MAX_NUM_ORDERED_EVENT_IDS already defined
#endif
/** \brief Array size for ordered output of filtered DTCs */
#define DEM_MAX_NUM_ORDERED_EVENT_IDS 20U

#if (defined DEM_TYPE_OF_ORIGIN_SUPPORTED)
#error DEM_TYPE_OF_ORIGIN_SUPPORTED already defined
#endif
/** \brief Supported origin types
 **
 ** This macro is only exported and not used internally.
 ** It is derived from ::DEM_MAX_NUMBER_EVENT_ENTRY_PRI,
 ** ::DEM_MAX_NUMBER_EVENT_ENTRY_SEC, ::DEM_MAX_NUMBER_EVENT_ENTRY_MIR, and
 ** ::DEM_MAX_NUMBER_EVENT_ENTRY_PER.
 **
 ** \note Macro name is still existing for compatibility reasons with AR2.1.
 **/
#define DEM_TYPE_OF_ORIGIN_SUPPORTED 1U

#if (defined DEM_DEV_ERROR_DETECT)
#error DEM_DEV_ERROR_DETECT already defined
#endif
/* !LINKSTO Dem113,1 */
/** \brief Switch, indicating if development error detection is activated for
 ** Dem */
#define DEM_DEV_ERROR_DETECT         STD_OFF

#if (defined DEM_TYPE_OF_DTC_SUPPORTED)
#error DEM_TYPE_OF_DTC_SUPPORTED already defined
#endif
/** \brief Returned DTC translation format by Dem_GetTranslationType()
 **
 ** \note Macro name is conform to the vague definition in chapter 10 of SWS.
 **/
#define DEM_TYPE_OF_DTC_SUPPORTED    DEM_DTC_TRANSLATION_ISO14229_1

#if (defined DEM_DCM_ENABLED)
#error DEM_DCM_ENABLED already defined
#endif
/** \brief Switch, indicating whether Dcm module should be a part of Dem */
#define DEM_DCM_ENABLED              STD_ON

#if (defined DEM_GET_DTCBYOCCURRENCETIME_SUPPORT)
#error DEM_GET_DTCBYOCCURRENCETIME_SUPPORT already defined
#endif
/** \brief Switch, indicating the existence of the functionality provided
 **  by Dem_GetDTCByOccurrenceTime() and the existence of the function itself
 **  to the Dcm module.
 **/
#define DEM_GET_DTCBYOCCURRENCETIME_SUPPORT      STD_OFF

#if (defined DEM_STORE_INTERNAL_EVENTS)
#error DEM_STORE_INTERNAL_EVENTS already defined
#endif
/** \brief Switch, indicating whether DTC=0 means event storage disabled */
#define DEM_STORE_INTERNAL_EVENTS       STD_ON

#if (defined DEM_TRIGGER_FIM_REPORTS)
#error DEM_TRIGGER_FIM_REPORTS already defined
#endif
/** \brief Switch, indicating if notification to FiM is activated for Dem */
#define DEM_TRIGGER_FIM_REPORTS      STD_OFF

#if (defined DEM_SUPPORT_FIM_ON_FDC_TRESHOLD)
#error DEM_SUPPORT_FIM_ON_FDC_TRESHOLD already defined
#endif
/** \brief Switch, indicating if FiM support for FDC threshold is activated for Dem */
#define DEM_SUPPORT_FIM_ON_FDC_TRESHOLD      STD_OFF

#if (defined DEM_TRIGGER_DCM_REPORTS)
#error DEM_TRIGGER_DCM_REPORTS already defined
#endif
/** \brief Switch, indicating if notification to Dcm is activated for Dem */
#define DEM_TRIGGER_DCM_REPORTS      STD_OFF


#if (defined DEM_USE_DYNAMIC_DTCS)
#error DEM_USE_DYNAMIC_DTCS already defined
#endif
/** \brief Macro for Enabling/Disabling dynamic DTC fetching */
#define DEM_USE_DYNAMIC_DTCS   STD_OFF

#if (defined DEM_EVCOMB_DISABLED)
#error DEM_EVCOMB_DISABLED already defined
#endif
/** \brief Macro used when no event combination is supported. */
#define DEM_EVCOMB_DISABLED                  0x00U

#if (defined DEM_EVCOMB_TYPE1)
#error DEM_EVCOMB_TYPE1  already defined
#endif
/** \brief Event combination is available and combined DTCs are stored/updated
    in a single event memory entry. */
#define DEM_EVCOMB_TYPE1                     0x01U

#if (defined DEM_EVENT_COMBINATION_SUPPORT)
#error DEM_EVENT_COMBINATION_SUPPORT already defined
#endif
/** \brief Macro for Enabling/Disabling event combination support. */
#define DEM_EVENT_COMBINATION_SUPPORT   DEM_EVCOMB_DISABLED

#if (defined DEM_SEM_SUPPORT)
#error DEM_SEM_SUPPORT already defined
#endif
/** \brief Macro for Enabling/Disabling security event support. */
/* !LINKSTO dsn.Dem.Sem.Availability,1 */
#define DEM_SEM_SUPPORT   STD_OFF


#if (defined DEM_NUM_CMB_DTCS)
#error DEM_NUM_CMB_DTCS already defined
#endif
/** \brief Define the number of combined DTCs.
 **
 ** This define will be present always in order to know if events are combined.
 ** Could be that event combination is configured and no events are combined.
 **/
#define DEM_NUM_CMB_DTCS   0U

#if (defined DEM_IDENTICAL_OBD_DTC_AVAILABLE)
#error DEM_IDENTICAL_OBD_DTC_AVAILABLE already defined
#endif
/** \brief Switch, indicating if there exists events with identical OBD DTC */
#define DEM_IDENTICAL_OBD_DTC_AVAILABLE  STD_OFF

#if (defined DEM_INIT_MONITOR_REENABLED_SUPPORT)
#error DEM_INIT_MONITOR_REENABLED_SUPPORT already defined
#endif
 /** \brief Macro for Enabling/Disabling support for InitMonitorReason DEM_INIT_MONITOR_REENABLED */
#define DEM_INIT_MONITOR_REENABLED_SUPPORT   STD_OFF

#if (defined DEM_MAX_NUM_INIT_MONITOR_PER_CYCLE)
#error DEM_MAX_NUM_INIT_MONITOR_PER_CYCLE already defined
#endif
/* !LINKSTO Dem.ControlDTCSetting.InitMonitorRE.Config,1 */
/** \brief Maximum number of CallbackInitMonitorForEvent calls per scheduling. */
#define DEM_MAX_NUM_INIT_MONITOR_PER_CYCLE    50U

#if (defined DEM_USE_EVENT_DISPLACEMENT)
#error DEM_USE_EVENT_DISPLACEMENT already defined
#endif
/** \brief Switch, indicating if event displacement support is activated for
 ** Dem */
#define DEM_USE_EVENT_DISPLACEMENT   STD_OFF

#if (defined DEM_EVENT_DISPLACEMENT_CRITERION_TNCTOC)
#error DEM_EVENT_DISPLACEMENT_CRITERION_TNCTOC already defined
#endif
/** \brief Switch, indicating if TNCTOC event displacement extension is
 ** activated */
#define DEM_EVENT_DISPLACEMENT_CRITERION_TNCTOC STD_OFF

#if (defined DEM_OBD_EVENT_DISPLACEMENT)
#error DEM_OBD_EVENT_DISPLACEMENT already defined
#endif
/** \brief Switch, indicating if OBD event displacement behavior is
 ** activated */
#define DEM_OBD_EVENT_DISPLACEMENT STD_OFF

#if (defined DEM_USE_ADVANCED_EVENT_DISPLACEMENT)
#error DEM_USE_ADVANCED_EVENT_DISPLACEMENT already defined
#endif
/** \brief advanced displacement not used **/
#define DEM_USE_ADVANCED_EVENT_DISPLACEMENT STD_OFF

#if (defined DEM_DISPLACEMENT_NONE)
#error DEM_DISPLACEMENT_NONE already defined
#endif
/** \brief Event memory entry displacement is disabled */
#define DEM_DISPLACEMENT_NONE                  0x00U

#if (defined DEM_DISPLACEMENT_PRIO_OCC)
#error DEM_DISPLACEMENT_PRIO_OCC already defined
#endif
/** \brief Event memory entry displacement is enabled, by consideration of
 ** priority and occurrence (but without active/passive status) */
#define DEM_DISPLACEMENT_PRIO_OCC              0x01U

#if (defined DEM_DISPLACEMENT_FULL)
#error DEM_DISPLACEMENT_FULL already defined
#endif
/** \brief Event memory entry displacement is enabled, by consideration of
 ** priority active/passive status, and occurrence */
#define DEM_DISPLACEMENT_FULL                  0x02U

#if (defined DEM_EVENT_DISPLACEMENT_STRATEGY)
#error DEM_EVENT_DISPLACEMENT_STRATEGY already defined
#endif
/** \brief Switch, indicating which displacement strategy is followed */
#define DEM_EVENT_DISPLACEMENT_STRATEGY DEM_DISPLACEMENT_FULL

#ifndef DEM_STATUS_BIT_AGING_AND_DISPLACEMENT
/** \brief The "TestFailedSinceLastClear" status bits are reset to 0, if
 ** aging or displacement applies (like done for the "ConfirmedDTC" status
 ** bits) */
#define DEM_STATUS_BIT_AGING_AND_DISPLACEMENT  0x00U
#endif

#ifndef DEM_STATUS_BIT_NORMAL
/** \brief The aging and displacement has no impact on the
 ** "TestFailedSinceLastClear" status bits */
#define DEM_STATUS_BIT_NORMAL                  0x01U
#endif

#if (defined DEM_STATUS_BIT_HANDLING_TESTFAILEDSINCELASTCLEAR)
#error DEM_STATUS_BIT_HANDLING_TESTFAILEDSINCELASTCLEAR already defined
#endif
/** \brief Switch, indicating if the aging and displacement mechanism shall be
 ** applied to the "TestFailedSinceLastClear" status bits */
#define DEM_STATUS_BIT_HANDLING_TESTFAILEDSINCELASTCLEAR \
  DEM_STATUS_BIT_NORMAL

#if (defined DEM_CLRRESP_VOLATILE)
#error DEM_CLRRESP_VOLATILE already defined
#endif
#define DEM_CLRRESP_VOLATILE            0U

#if (defined DEM_CLRRESP_NONVOLATILE_TRIGGER)
#error DEM_CLRRESP_NONVOLATILE_TRIGGER already defined
#endif
#define DEM_CLRRESP_NONVOLATILE_TRIGGER 1U

#if (defined DEM_CLRRESP_NONVOLATILE_FINISH)
#error DEM_CLRRESP_NONVOLATILE_FINISH already defined
#endif
#define DEM_CLRRESP_NONVOLATILE_FINISH  2U

#if (defined DEM_CLEAR_DTC_BEHAVIOR)
#error DEM_CLEAR_DTC_BEHAVIOR already defined
#endif
/** \brief Behaviour of ClearDTC */
#define DEM_CLEAR_DTC_BEHAVIOR  DEM_CLRRESP_VOLATILE

#if (defined DEM_OBD_DEP_SEC_ECU)
#error DEM_OBD_DEP_SEC_ECU already defined
#endif
#define DEM_OBD_DEP_SEC_ECU      0U

#if (defined DEM_OBD_MASTER_ECU)
#error DEM_OBD_MASTER_ECU already defined
#endif
#define DEM_OBD_MASTER_ECU       1U

#if (defined DEM_OBD_NO_OBD_SUPPORT)
#error DEM_OBD_NO_OBD_SUPPORT already defined
#endif
#define DEM_OBD_NO_OBD_SUPPORT   2U

#if (defined DEM_OBD_PRIMARY_ECU)
#error DEM_OBD_PRIMARY_ECU already defined
#endif
#define DEM_OBD_PRIMARY_ECU      3U

/* !LINKSTO ECUC_Dem_00698_1,1 */
#if (defined DEM_OBD_Support_Kind)
#error DEM_OBD_Support_Kind already defined
#endif
/* !LINKSTO Dem_OBD_0080,1 */
/** \brief Switch defines OBD support and kind of OBD ECU */
#define DEM_OBD_Support_Kind    DEM_OBD_NO_OBD_SUPPORT

#if (defined DEM_OBD_VARIANT_OBD_CLASSIC)
#error DEM_OBD_VARIANT_OBD_CLASSIC already defined
#endif
#define DEM_OBD_VARIANT_OBD_CLASSIC 0U

#if (defined DEM_OBD_VARIANT_OBDONUDS)
#error DEM_OBD_VARIANT_OBDONUDS already defined
#endif
#define DEM_OBD_VARIANT_OBDONUDS    1U

#if (defined DEM_OBD_VARIANT_NONE)
#error DEM_OBD_VARIANT_NONE already defined
#endif
#define DEM_OBD_VARIANT_NONE      2U

#if (defined DEM_OBD_VARIANT )
#error DEM_OBD_VARIANT  already defined
#endif
/* !LINKSTO Dem.Config.DemObdVariant,1 */
/** \brief switch selects the supported OBD variant */
#define DEM_OBD_VARIANT     DEM_OBD_VARIANT_NONE

#if (defined DEM_NUM_FFPARTS)
#error DEM_NUM_FFPARTS already defined
#endif
/** \brief The Number of freeze frame parts of an event entry
 **   (common + individual or only individual) */
#define DEM_NUM_FFPARTS     1U


#define DEM_STATIC  STATIC

/* !LINKSTO dsn.Dem.ProjectSpecificCustomization.Macro,1 */
#if (defined DEM_PROJECT_SPECIFIC_CUSTOMIZATION_SUPPORT)
#error DEM_PROJECT_SPECIFIC_CUSTOMIZATION_SUPPORT already defined
#endif
/** \brief Switch for user defined APIs support */
#define DEM_PROJECT_SPECIFIC_CUSTOMIZATION_SUPPORT    STD_OFF

/*-----------------------[Event burst reduction]----------------------------*/
/* !LINKSTO dsn.Dem.EventBurstReduction.MaxPassed,1 */
#if (defined DEM_MAX_HANDLED_PASSED_EVENTS_PER_SCHEDULING)
#error DEM_MAX_HANDLED_PASSED_EVENTS_PER_SCHEDULING already defined
#endif
/** \brief The number of passed events handled per Dem_MainFunction call */
#define DEM_MAX_HANDLED_PASSED_EVENTS_PER_SCHEDULING 3U

/* !LINKSTO dsn.Dem.EventBurstReduction.MaxFailed,1 */
#if (defined DEM_MAX_HANDLED_FAILED_EVENTS_PER_SCHEDULING)
#error DEM_MAX_HANDLED_FAILED_EVENTS_PER_SCHEDULING already defined
#endif
/** \brief The number of failed events handled per Dem_MainFunction call */
#define DEM_MAX_HANDLED_FAILED_EVENTS_PER_SCHEDULING 3U


/* !LINKSTO Dem_OBD_0001,2 */
#if (defined DEM_OBD_Support)
#error DEM_OBD_Support already defined
#endif
/** \brief Switch, indicating if OBD functionalities are enabled */
#define DEM_OBD_Support         STD_OFF

/*-------------------------[MIL group configuration]------------------------*/

#if (defined DEM_MILGROUP_SUPPORT)
#error DEM_MILGROUP_SUPPORT already defined
#endif
/** \brief Switch, indicating if MIL group functionality is enabled */
#define DEM_MILGROUP_SUPPORT   STD_OFF

/*---------------------------[J1939 configuration]----------------------------*/

#if (defined DEM_J1939_SUPPORT)
#error DEM_J1939_SUPPORT already defined
#endif
/** \brief Switch, indicating if J1939 functionalities are enabled */
#define DEM_J1939_SUPPORT         STD_OFF


#if (defined DEM_J1939_READING_DTC_SUPPORT)
#error DEM_J1939_READING_DTC_SUPPORT already defined
#endif
/** \brief Switch, indicating if J1939 Reading DTC functionalities are enabled */
#define DEM_J1939_READING_DTC_SUPPORT         STD_OFF

#if (defined DEM_J1939_RATIO_SUPPORT)
#error DEM_J1939_RATIO_SUPPORT already defined
#endif
/** \brief Switch, indicating if J1939 Ratio functionalities are enabled */
#define DEM_J1939_RATIO_SUPPORT         STD_OFF

#if (defined DEM_J1939_READINESS1_SUPPORT)
#error DEM_J1939_READINESS1_SUPPORT already defined
#endif
/** \brief Switch, indicating if J1939 Readiness1 functionalities are enabled */
#define DEM_J1939_READINESS1_SUPPORT         STD_OFF

#if (defined DEM_J1939_READINESS2_SUPPORT)
#error DEM_J1939_READINESS2_SUPPORT already defined
#endif
/** \brief Switch, indicating if J1939 Readiness2 functionalities are enabled */
#define DEM_J1939_READINESS2_SUPPORT         STD_OFF

#if (defined DEM_J1939_READINESS3_SUPPORT)
#error DEM_J1939_READINESS3_SUPPORT already defined
#endif
/** \brief Switch, indicating if J1939 Readiness3 functionalities are enabled */
#define DEM_J1939_READINESS3_SUPPORT         STD_OFF

#if (defined DEM_J1939_CLEAR_DTC_SUPPORT)
#error DEM_J1939_CLEAR_DTC_SUPPORT already defined
#endif
/** \brief Switch, indicating if J1939 Clear DTC functionalities are enabled */
#define DEM_J1939_CLEAR_DTC_SUPPORT         STD_OFF

#if (defined DEM_J1939_FREEZEFRAME_SUPPORT)
#error DEM_J1939_FREEZEFRAME_SUPPORT already defined
#endif
/** \brief Macro for Enabling/Disabling J1939 freeze frames functionality */
#define DEM_J1939_FREEZEFRAME_SUPPORT   STD_OFF

#if (defined DEM_J1939_EXPANDED_FREEZEFRAME_SUPPORT)
#error DEM_J1939_EXPANDED_FREEZEFRAME_SUPPORT already defined
#endif
 /** \brief Switch, indicating if J1939 expanded freeze frames functionalities are enabled */
#define DEM_J1939_EXPANDED_FREEZEFRAME_SUPPORT         STD_OFF

#if (defined DEM_J1939_DM31_SUPPORT)
#error DEM_J1939_DM31_SUPPORT already defined
#endif
 /** \brief Switch, indicating if J1939 DM31 functionalities are enabled */
#define DEM_J1939_DM31_SUPPORT         STD_OFF

/*---------------------[IUMPR function support ]----------------------------*/
/* !LINKSTO Dem.Config.IumprFunctionsEnabled,1 */
#if (defined DEM_IUMPR_FUNCTIONS_ENABLED)
#error DEM_IUMPR_FUNCTIONS_ENABLED already defined
#endif
/* Switch, indicating whether IUMPR related functions are enabled. */
#define DEM_IUMPR_FUNCTIONS_ENABLED         STD_OFF

#if (defined DEM_OBD_COMPLIANCY_ENABLED)
#error DEM_OBD_COMPLIANCY_ENABLED already defined
#endif
#define DEM_OBD_COMPLIANCY_ENABLED         STD_OFF

/*---------------------[OBD centralized PID handling]-----------------------*/

#if (defined DEM_OBD_CENTRALIZED_PID31_HANDLING)
#error DEM_OBD_CENTRALIZED_PID31_HANDLING already defined
#endif
 /** \brief Switch, indicating if PID$31 is calculated Dem internally (if set to 'false')
  ** or returned as 0 always (if set to 'true')*/
#define DEM_OBD_CENTRALIZED_PID31_HANDLING         STD_OFF

#if (defined DEM_OBD_CENTRALIZED_PID21_HANDLING)
#error DEM_OBD_CENTRALIZED_PID21_HANDLING already defined
#endif
 /** \brief Switch, indicating if PID$21 is calculated Dem internally (if set to 'false')
  ** or returned as 0 always (if set to 'true')*/
#define DEM_OBD_CENTRALIZED_PID21_HANDLING         STD_OFF


#if (defined DEM_MAX_SIZE_PID_CLASS)
#error DEM_MAX_SIZE_PID_CLASS already defined
#endif
/** \brief Maximum size of a PID class.
 ** This value is derived from the size of the configured PID DataElements for each PID. */
#define DEM_MAX_SIZE_PID_CLASS    0U

#if (defined DEM_MAX_INDEX_PID_CLASS)
#error DEM_MAX_INDEX_PID_CLASS already defined
#endif
/** \brief Maximum index of a PID class.
 ** This value is derived from the index of the configured PID DataElements for each PID. */
#define DEM_MAX_INDEX_PID_CLASS    0U

/*-----[Indexes to access PID0D and PID1F within data element class]--------*/


#if (defined DEM_MAINCYCLE_TICKS_PER_SECOND)
#error DEM_MAINCYCLE_TICKS_PER_SECOND already defined
#endif
#define DEM_MAINCYCLE_TICKS_PER_SECOND 100U

/*------------------[Extended data configuration]---------------------------*/

/* Symbolic names of configured extended data record numbers */

/* DEM_TRIGGER_<...> macros used for DEM_EXTENDED_DATA_CAPTURE are
 * defined in section 'Freeze frame configuration' */

#if (defined DEM_EXTENDED_DATA_CAPTURE)
#error DEM_EXTENDED_DATA_CAPTURE already defined
#endif
/** \brief Type of extended data capture trigger
 **
 ** This parameter defines the point in time, when the extended data
 ** collection is done for the initial event memory entry.
 **/
#define DEM_EXTENDED_DATA_CAPTURE     DEM_TRIGGER_EVENT_MEMORY_STORAGE

#if (defined DEM_NUM_EVENT_PRIORITIES)
#error DEM_NUM_EVENT_PRIORITIES already defined
#endif
    /** \brief Used for defining size of Dem_ExternalPrioValue array */
#define DEM_NUM_EVENT_PRIORITIES      0

/*------------------[Fault confirmation configurations]---------------------*/

#if (defined DEM_NUM_FAILURECYCLES)
#error DEM_NUM_FAILURECYCLES already defined
#endif
/** \brief Number of fault confirmation configurations */
#define DEM_NUM_FAILURECYCLES 0U

#if (defined DEM_RESET_CONFIRMED_BIT_ON_OVERFLOW_SUPPORT_FAULT_CONFIRMATION)
#error DEM_RESET_CONFIRMED_BIT_ON_OVERFLOW_SUPPORT_FAULT_CONFIRMATION already defined
#endif
/** \brief Switch, indicating support for fault confirmation without event memory entry */
#define DEM_RESET_CONFIRMED_BIT_ON_OVERFLOW_SUPPORT_FAULT_CONFIRMATION     STD_OFF

#if (defined DEM_STATUS_COUNTER_SIZE)
#error DEM_STATUS_COUNTER_SIZE already defined
#endif
/** \brief Number of status counters in ::Dem_NvData
 ** per non-combined event with fault confirmation enabled */
#define DEM_STATUS_COUNTER_SIZE   0U

/*------------------[Memory size configuration]-----------------------------*/

/* !LINKSTO dsn.Dem.ErrorQueueOpt,1 */
#if (defined DEM_BSW_ERROR_BUFFER_SIZE)
#error DEM_BSW_ERROR_BUFFER_SIZE already defined
#endif
/** \brief Maximal number of error-queue entries
 **
 ** \note Macro name is conform to the vague definition in chapter 10 of SWS.
 **/
#define DEM_BSW_ERROR_BUFFER_SIZE 10U



/* DEM_DTC_ORIGIN_PRIMARY_MEMORY - Event EVENT_CANSM_E_BUS_OFF:
   no internal values + no extended data + no freeze frames = 0 */


/* DEM_DTC_ORIGIN_PRIMARY_MEMORY - Event EVENT_ADC_OUT_OF_ORDER:
   no internal values + no extended data + no freeze frames = 0 */


/* DEM_DTC_ORIGIN_PRIMARY_MEMORY - Event EVENT_WARM_RESET:
   no internal values + no extended data + no freeze frames = 0 */


/* DEM_DTC_ORIGIN_PRIMARY_MEMORY - Event EVENT_PFLASH_MEM_CORRUPT:
   no internal values + no extended data + no freeze frames = 0 */


/* DEM_DTC_ORIGIN_PRIMARY_MEMORY - Event EVENT_EXT_WDG_OUT_OF_ORDER:
   no internal values + no extended data + no freeze frames = 0 */


/* DEM_DTC_ORIGIN_PRIMARY_MEMORY - Event EVENT_NVM_NOT_PRG:
   no internal values + no extended data + no freeze frames = 0 */


/* DEM_DTC_ORIGIN_PRIMARY_MEMORY - Event EVENT_RAM_MEM_CORRUPT:
   no internal values + no extended data + no freeze frames = 0 */


/* DEM_DTC_ORIGIN_PRIMARY_MEMORY - Event EVENT_ADC_CALIB:
   no internal values + no extended data + no freeze frames = 0 */


/* DEM_DTC_ORIGIN_PRIMARY_MEMORY - Event EVENT_ECU_OVER_TEMPERATURE:
   no internal values + no extended data + no freeze frames = 0 */


/* DEM_DTC_ORIGIN_PRIMARY_MEMORY - Event EVENT_DFLASH_MEM_CORRUPT:
   no internal values + no extended data + no freeze frames = 0 */


/* DEM_DTC_ORIGIN_PRIMARY_MEMORY - Event EVENT_SBC_STATUS_FAILURE:
   no internal values + no extended data + no freeze frames = 0 */


/* DEM_DTC_ORIGIN_PRIMARY_MEMORY - Event EVENT_POWER_SUPPLY_OV:
   no internal values + no extended data + no freeze frames = 0 */


/* DEM_DTC_ORIGIN_PRIMARY_MEMORY - Event EVENT_POWER_SUPPLY_UV:
   no internal values + no extended data + no freeze frames = 0 */


/* DEM_DTC_ORIGIN_PRIMARY_MEMORY - Event EVENT_ACTUATOR_STATUS:
   no internal values + no extended data + no freeze frames = 0 */


/* DEM_DTC_ORIGIN_PRIMARY_MEMORY - Event EVENT_MCU_SELFTEST:
   no internal values + no extended data + no freeze frames = 0 */


/* DEM_DTC_ORIGIN_PRIMARY_MEMORY - Event EVENT_ACTUATOR_OPEN_CIRCUIT:
   no internal values + no extended data + no freeze frames = 0 */


/* DEM_DTC_ORIGIN_PRIMARY_MEMORY - Event EVENT_ACTUATOR_SHORT_TO_GND:
   no internal values + no extended data + no freeze frames = 0 */


/* DEM_DTC_ORIGIN_PRIMARY_MEMORY - Event EVENT_ACTUATOR_SHORT_TO_VBAT:
   no internal values + no extended data + no freeze frames = 0 */


/* DEM_DTC_ORIGIN_PRIMARY_MEMORY - Event EVENT_ACC_STATUS_FAILURE:
   no internal values + no extended data + no freeze frames = 0 */


/* DEM_DTC_ORIGIN_PRIMARY_MEMORY - Event EVENT_SPI_E_HW_ERROR:
   no internal values + no extended data + no freeze frames = 0 */


/* DEM_DTC_ORIGIN_PRIMARY_MEMORY - Event EVENT_SOLENOID_OVERVOLTAGE:
   no internal values + no extended data + no freeze frames = 0 */


/* DEM_DTC_ORIGIN_PRIMARY_MEMORY - Event EVENT_POWER_STAGE_FAILIURE:
   no internal values + no extended data + no freeze frames = 0 */


/* DEM_DTC_ORIGIN_PRIMARY_MEMORY - Event EVENT_MCU_CRC_REGISTERS:
   no internal values + no extended data + no freeze frames = 0 */
/* entry data sizes (IntVal + ED + Num * FF) of prm memory:
   0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 */
/* entry data sizes (IntVal + ED + Num * FF) of sec memory:
   */
/* entry data sizes (IntVal + ED + Num * FF) of mir memory:
   */

#if (defined DEM_SIZE_GATE_ENTRY_DATA_PRIMARY)
#error DEM_SIZE_GATE_ENTRY_DATA_PRIMARY already defined
#endif
/** \brief Gate entry size for primary memory
 **
 ** If immediate storage is enabled for any of the events in primary memory
 ** then this size is maximum of the highest primary event memory size
 ** considering IntVal, extended data freeze frames, and J1939 Freeze frame.
 ** If maximum calculated size is 0, then default 1 is used.
 */
#define DEM_SIZE_GATE_ENTRY_DATA_PRIMARY   1U

#if (defined DEM_SIZE_GATE_ENTRY_DATA_SECONDARY)
#error DEM_SIZE_GATE_ENTRY_DATA_SECONDARY already defined
#endif
/** \brief Gate entry size for secondary memory
 **
 ** If immediate storage is enabled for any of the events in secondary memory
 ** then this size is maximum of the highest secondary event memory size
 ** considering IntVal, extended data and freeze frames.
 ** If maximum calculated size is 0, then default 1 is used.
 */
#define DEM_SIZE_GATE_ENTRY_DATA_SECONDARY 1U

#if (defined DEM_SIZE_GATE_ENTRY_DATA_MIRROR)
#error DEM_SIZE_GATE_ENTRY_DATA_MIRROR already defined
#endif
/** \brief Gate entry size for mirror memory
 **
 ** If immediate storage is enabled for any of the events in mirror memory
 ** then this size is maximum of the highest mirror event memory size
 ** considering IntVal, extended data and freeze frames.
 ** If maximum calculated size is 0, then default 1 is used.
 */
#define DEM_SIZE_GATE_ENTRY_DATA_MIRROR    1U

#if (defined DEM_SIZE_GATE_ENTRY_DATA_PERMANENT)
#error DEM_SIZE_GATE_ENTRY_DATA_PERMANENT already defined
#endif
/** \brief Gate entry size for permanent memory
 **
 ** As this event memory type is not supported this shall be default 1.
 */
#define DEM_SIZE_GATE_ENTRY_DATA_PERMANENT 1U

#if (defined DEM_USE_IMMEDIATE_NV_STORAGE)
#error DEM_USE_IMMEDIATE_NV_STORAGE already defined
#endif
/** \brief Switch, indicating if Immediate storage of event memory entries in
 ** NvM is activated for Dem
 **
 ** This can be the case if any DTC is configured to be stored immediately, or
 ** if ClearDTC behavior is configured to non-volatile triggered or finished.
 */
#define DEM_USE_IMMEDIATE_NV_STORAGE    STD_OFF

#if (defined DEM_NV_STORAGE_EMPTY_EVMEM_ENTRIES)
#error DEM_NV_STORAGE_EMPTY_EVMEM_ENTRIES already defined
#endif
/* !LINKSTO Dem.NvStorageEmptyEvMemEntries.Config,1 */
/** \brief Switch, indicating if empty event memory entries will be
 ** initialized in NVRAM
 **
 ** If the restoration of an event memory entry from NvM was not successful,
 ** this switch controls (esp. for ::DEM_USE_IMMEDIATE_NV_STORAGE = ON) if
 ** this entry is initialized with default values during next shutdown.
 */
#define DEM_NV_STORAGE_EMPTY_EVMEM_ENTRIES    STD_ON

#if (defined DEM_INTERMEDIATE_STORAGE_DTC_STATUS)
#error DEM_INTERMEDIATE_STORAGE_DTC_STATUS already defined
#endif
/* !LINKSTO dsn.Dem.IntermediateNvStorageOfDTCStatus.Support,1 */
/** \brief Switch to indicate intermediate DTC status storage is enabled
 **
 ** The intermediate storage of DTC status is enabled if at least one
 ** DTC has DemImmediateNvStorage set to true or
 ** DemImmediateStorageInternalEvents is true with at least one internal
 ** event.
 **/
#define DEM_INTERMEDIATE_STORAGE_DTC_STATUS      STD_OFF


#if (DEM_USE_IMMEDIATE_NV_STORAGE == STD_ON)

#if (defined DEM_IMMEDIATE_CLEARED)
#error DEM_IMMEDIATE_CLEARED already defined
#endif
/** \brief Immediate storage configuration value: store CLEARED entries */
#define DEM_IMMEDIATE_CLEARED 0U

#if (defined DEM_IMMEDIATE_CHANGED)
#error DEM_IMMEDIATE_CHANGED already defined
#endif
/** \brief Immediate storage configuration value: store ALL entries */
#define DEM_IMMEDIATE_CHANGED 1U

#if (defined DEM_IMMEDIATE_NV_STORAGE_TYPE)
#error DEM_IMMEDIATE_NV_STORAGE_TYPE already defined
#endif
/** \brief Immediate storage configuration */
#define DEM_IMMEDIATE_NV_STORAGE_TYPE    DEM_IMMEDIATE_CLEARED

#endif /* (DEM_USE_IMMEDIATE_NV_STORAGE == STD_ON) */

#if (defined DEM_IMMEDIATE_NV_STORAGE_LIMIT)
#error DEM_IMMEDIATE_NV_STORAGE_LIMIT already defined
#endif
/** \brief Immediate NvM storage limit
 **
 ** Defines the maximum number of occurrences, a specific event memory entry
 ** is allowed, to be stored in NVRAM immediately.
 ** Its value is set to 0 when the immediate storage limit feature is
 ** disabled by the user. In that case, there is no limit for the storage to
 ** NVRAM and whenever the entry gets updated, it can be stored immediately
 ** to NVRAM if immediate storage is enabled for it.
 **/
#define DEM_IMMEDIATE_NV_STORAGE_LIMIT     0U

#if (defined DEM_ZERO_END)
#error DEM_ZERO_END already defined
#endif
/** \brief Zero value to be added to each size, whose involved patterns could
 ** be none */
#define DEM_ZERO_END                  0U

#if (defined DEM_SIZE_ENTRY_DATA_PRIMARY)
#error DEM_SIZE_ENTRY_DATA_PRIMARY already defined
#endif
/** \brief Size of dynamic primary entry data
 **
 ** The N (primary memory entry number) maximal sizes are added.
 **
 ** \note The DEM_ZERO_END is not necessary here, because primary event memory
 **       is always > 0.
 **/
#define DEM_SIZE_ENTRY_DATA_PRIMARY   \
  (0U + 0U + 0U + 0U + 0U + 0U + 0U + 0U + 0U + 0U + 0U + 0U + 0U + 0U + 0U + 0U + 0U + 0U + 0U + 0U  )
/* !LINKSTO dsn.Dem.Dem_EntryData.MaxSize,1 */
#if DEM_SIZE_ENTRY_DATA_PRIMARY > 0xFFFFU
#error The total size of the dynamic primary entry data exceed 65535 byte. \
  Please reduce size or remove Extended Data Recordes, Freeze Frame Classes, or \
  number of Freeze Frame Records to reduce the needed space.
#endif

#if (defined DEM_SIZE_ENTRY_DATA_SECONDARY)
#error DEM_SIZE_ENTRY_DATA_SECONDARY already defined
#endif
/** \brief Size of dynamic secondary entry data
 **
 ** The N (secondary memory entry number) maximal sizes are added.
 **/
#define DEM_SIZE_ENTRY_DATA_SECONDARY \
  (  DEM_ZERO_END)
/* !LINKSTO dsn.Dem.Dem_EntryData.MaxSize,1 */
#if DEM_SIZE_ENTRY_DATA_SECONDARY > 0xFFFFU
#error The total size of the dynamic secondary entry data exceed 65535 byte. \
  Please reduce size or remove Extended Data Recordes, Freeze Frame Classes, or \
  number of Freeze Frame Records to reduce the needed space.
#endif

#if (defined DEM_SIZE_ENTRY_DATA_MIRROR)
#error DEM_SIZE_ENTRY_DATA_MIRROR already defined
#endif
/** \brief Size of dynamic mirror entry data
 **
 ** The N (mirror memory entry number) maximal sizes are added.
 **/
#define DEM_SIZE_ENTRY_DATA_MIRROR    \
  (  DEM_ZERO_END)
/* !LINKSTO dsn.Dem.Dem_EntryData.MaxSize,1 */
#if DEM_SIZE_ENTRY_DATA_MIRROR > 0xFFFFU
#error The total size of the dynamic mirror entry data exceed 65535 byte. \
  Please reduce size or remove Extended Data Recordes, Freeze Frame Classes, or \
  number of Freeze Frame Records to reduce the needed space.
#endif

#if (defined DEM_SIZE_ENTRY_DATA_PERMANENT)
#error DEM_SIZE_ENTRY_DATA_PERMANENT already defined
#endif
/** \brief Size of dynamic permanent entry data
 **
 ** The N (permanent memory entry number) maximal sizes are added.
 **/
#define DEM_SIZE_ENTRY_DATA_PERMANENT DEM_ZERO_END

/*---------------------[Common Freeze Frame]--------------------------------*/

#if (defined DEM_COMMON_FREEZEFRAMES_USED)
#error DEM_COMMON_FREEZEFRAMES_USED already defined
#endif
/** \brief Defines if any common freeze frame class is configured */
#define DEM_COMMON_FREEZEFRAMES_USED   STD_OFF

/*------------------[Development Freeze Frame]------------------------------*/

/* !LINKSTO dsn.Dem.DevFF.Encapsulation,1 */
#if (defined DEM_DEV_FREEZE_FRAME_USED)
#error DEM_DEV_FREEZE_FRAME_USED already defined
#endif
/** \brief Switch, indicating if Development Freeze Frames are enabled */
#define DEM_DEV_FREEZE_FRAME_USED   STD_OFF

#if (defined DEM_MAX_NUMBER_DEVFFA_ENTRY)
#error DEM_MAX_NUMBER_DEVFFA_ENTRY already defined
#endif
#define DEM_MAX_NUMBER_DEVFFA_ENTRY 0U

#if (defined DEM_DEV_FFA_MAX_CLASS_SIZE)
#error DEM_DEV_FFA_MAX_CLASS_SIZE already defined
#endif
/** \brief Size of largest configured Development Freeze Frames A class
 ** including the Common Development Freeze Frame A part
 **/
/* !LINKSTO dsn.Dem.DevFF.DemMaxNumberDevFreezeFrameAEntry, 1 */
#define DEM_DEV_FFA_MAX_CLASS_SIZE 0U

#if (defined DEM_MAX_NUMBER_DEVFFB_ENTRY)
#error DEM_MAX_NUMBER_DEVFFB_ENTRY already defined
#endif
#define DEM_MAX_NUMBER_DEVFFB_ENTRY 0U

#if (defined DEM_DEV_FFB_MAX_CLASS_SIZE)
#error DEM_DEV_FFB_MAX_CLASS_SIZE already defined
#endif
/** \brief Size of largest configured Development Freeze Frames B class
 **/
#define DEM_DEV_FFB_MAX_CLASS_SIZE 0U

/*------------------[Error Queue configuration]----------------------------*/
/* brief Switch, indicating if extended error queue is enabled */
#define DEM_ERROR_QUEUE_EXTENDED STD_OFF

/*------------------[Freeze frame configuration]----------------------------*/

/* Symbolic names of configured freeze frame data IDs */

#if (defined DEM_FF_RECNUM_CALCULATED)
#error DEM_FF_RECNUM_CALCULATED already defined
#endif
/** \brief Freeze frame records will be numbered consecutive starting by 1 in
 ** their chronological order */
#define DEM_FF_RECNUM_CALCULATED     0x00U

#if (defined DEM_FF_RECNUM_CONFIGURED)
#error DEM_FF_RECNUM_CONFIGURED already defined
#endif
/** \brief Freeze frame records will be numbered based on the given
 ** configuration in their chronological order */
#define DEM_FF_RECNUM_CONFIGURED     0x01U

#if (defined DEM_FREEZE_FRAME_REC_NUMERATION_TYPE)
#error DEM_FREEZE_FRAME_REC_NUMERATION_TYPE already defined
#endif
/** \brief Type of assignment of freeze frame record numbers
 **
 ** This switch defines the type for assigning freeze frame record numbers for
 ** event-specific freeze frame records.
 **/
#define DEM_FREEZE_FRAME_REC_NUMERATION_TYPE  DEM_FF_RECNUM_CALCULATED

#if (defined DEM_MAX_NUMBER_PRESTORED_FF)
#error DEM_MAX_NUMBER_PRESTORED_FF already defined
#endif
/** \brief Maximum number of available prestored freeze frames
 **
 ** \note Macro name is conform to the vague definition in chapter 10 of SWS.
 **/
#define DEM_MAX_NUMBER_PRESTORED_FF 0U

#if (defined DEM_TRIGGER_EVENT_MEMORY_STORAGE)
#error DEM_TRIGGER_EVENT_MEMORY_STORAGE already defined
#endif
/** \brief Triggers the collection of freeze frame / extended data if the
 ** event is stored in the event memory */
#define DEM_TRIGGER_EVENT_MEMORY_STORAGE  0x00U

#if (defined DEM_TRIGGER_TESTFAILED)
#error DEM_TRIGGER_TESTFAILED already defined
#endif
/** \brief Triggers the collection of freeze frame / extended data if the
 ** UDS DTC status bit 0 (TestedFailed) changes from 0 to 1 */
#define DEM_TRIGGER_TESTFAILED            0x01U

#if (defined DEM_TRIGGER_ON_FDC_THRESHOLD)
#error DEM_TRIGGER_ON_FDC_THRESHOLD already defined
#endif
/** \brief Triggers the collection of freeze frame / extended data if the
 ** unconfirmedDTC threshold is reached */
#define DEM_TRIGGER_ON_FDC_THRESHOLD      0x02U

#if (defined DEM_FREEZE_FRAME_CAPTURE)
#error DEM_FREEZE_FRAME_CAPTURE already defined
#endif
/** \brief Type of freeze frame capture trigger
 **
 ** This parameter defines the point in time, when the freeze frame data
 ** collection is done for the initial event memory entry.
 **/
#define DEM_FREEZE_FRAME_CAPTURE          DEM_TRIGGER_EVENT_MEMORY_STORAGE

/*------------------[Client configuration]----------------------------------*/
/** \brief Provides symbolic names of configured Clients
 **
 ** Configured clients are prefixed with symbolic name DemConf_DemClient_
 **/
#if (defined DemConf_DemClient_CLIENT_0)
#error DemConf_DemClient_CLIENT_0 is already defined
#endif
#define DemConf_DemClient_CLIENT_0                        0U
#if (defined DemConf_DemClient_CLIENT_1)
#error DemConf_DemClient_CLIENT_1 is already defined
#endif
#define DemConf_DemClient_CLIENT_1                        1U
/*------------------[Multi-event triggering configuration]------------------*/
#if (defined DEM_MULTIEVENTTRIGGERING_ALT_NONE)
#error DEM_MULTIEVENTTRIGGERING_ALT_NONE already defined
#endif
/** \brief Type of multi-event triggering default behavior */
#define DEM_MULTIEVENTTRIGGERING_ALT_NONE  0x00U

#if (defined DEM_MULTIEVENTTRIGGERING_ALT_EXCLUSIVE_REPLACE)
#error DEM_MULTIEVENTTRIGGERING_ALT_EXCLUSIVE_REPLACE already defined
#endif
/** \brief Type of multi-event triggering exlusive replacement behavior */
#define DEM_MULTIEVENTTRIGGERING_ALT_EXCLUSIVE_REPLACE  0x01U

/*------------------[Events configuration]----------------------------------*/

#if (defined DEM_MAX_NUMBER_EVENT_ENTRY_PRI)
#error DEM_MAX_NUMBER_EVENT_ENTRY_PRI already defined
#endif
/** \brief Maximum number of events which can be stored in the primary memory
 **
 ** \note Macro name is conform to the vague definition in chapter 10 of SWS.
 **/
#define DEM_MAX_NUMBER_EVENT_ENTRY_PRI 20U

#if (defined DEM_MAX_NUMBER_EVENT_ENTRY_SEC)
#error DEM_MAX_NUMBER_EVENT_ENTRY_SEC already defined
#endif
/** \brief Maximum number of events which can be stored in the secondary
 ** memory
 **
 ** \note Macro name is conform to the vague definition in chapter 10 of SWS.
 **/
#define DEM_MAX_NUMBER_EVENT_ENTRY_SEC 0U

#if (defined DEM_MAX_NUMBER_EVENT_ENTRY_MIR)
#error DEM_MAX_NUMBER_EVENT_ENTRY_MIR already defined
#endif
/** \brief Maximum number of events which can be stored in the mirror memory
 **
 ** \note Macro name is conform to the vague definition in chapter 10 of SWS.
 **/
#define DEM_MAX_NUMBER_EVENT_ENTRY_MIR 0U

#if (defined DEM_MAX_NUMBER_EVENT_ENTRY_PER)
#error DEM_MAX_NUMBER_EVENT_ENTRY_PER already defined
#endif
/** \brief Maximum number of events which can be stored in the permanent memory
 **
 ** \note Macro name is conform to the vague definition in chapter 10 of SWS.
 **/
/* !LINKSTO Dem_OBD_0005,1 */

#define DEM_MAX_NUMBER_EVENT_ENTRY_PER 0U

#if (defined DEM_NUMBER_OF_EVENT_CLASSES)
#error DEM_NUMBER_OF_EVENT_CLASSES already defined
#endif
/** \brief Number of individual event classes which are present in the system
 **
 ** If calibration is enabled the Dem combine set of this parameter to one entry in Dem_EventClass[]
 **/
#define DEM_NUMBER_OF_EVENT_CLASSES 1U

#if (defined DEM_NUMBER_OF_EVENTS)
#error DEM_NUMBER_OF_EVENTS already defined
#endif
/** \brief Number of events which are present in the system
 **
 ** Calculated by number of event IDs listed in Dem_IntErrId.h and
 ** Dem_IntEvtId.h including ::DEM_EVENT_ID_INVALID.
 **
 ** \note Macro name is still existing for compatibility reasons with AR2.1.
 **/
#define DEM_NUMBER_OF_EVENTS  24U

#if (defined DEM_NUM_SWC_EVENTS)
#error DEM_NUM_SWC_EVENTS already defined
#endif
/** \brief Number of SW-C events present in the system
 **/
#define DEM_NUM_SWC_EVENTS 21U

#if (defined DEM_NUM_BSW_EVENTS)
#error DEM_NUM_BSW_EVENTS already defined
#endif
/** \brief Number of BSW events present in the system
 **/
#define DEM_NUM_BSW_EVENTS (DEM_NUMBER_OF_EVENTS - DEM_NUM_SWC_EVENTS - 1U)

#if (defined DEM_NUM_OF_PIDS_IN_OBDFF)
#error DEM_NUM_OF_PIDS_IN_OBDFF already defined
#endif
/** \brief Number of PIDs to be stored in OBD freeze frame **/
#define DEM_NUM_OF_PIDS_IN_OBDFF 0U

#if (defined DEM_OBDFF_SINGLE)
#error DEM_OBDFF_SINGLE already defined
#endif
/** \brief Single OBD freeze frame support */
#define DEM_OBDFF_SINGLE            0x01U

#if (defined DEM_OBDFF_MULTIPLE)
#error DEM_OBDFF_MULTIPLE already defined
#endif
/** \brief Multiple OBD freeze frame support */
#define DEM_OBDFF_MULTIPLE            0x02U

#if (defined DEM_OBDFF_SUPPORT_KIND)
#error DEM_OBDFF_SUPPORT_KIND already defined
#endif
/** \brief Type of OBD freeze frame support
 **
 ** This macro controls support of the multiple and single OBD Freeze Frame
 **/
/* !LINKSTO dsn.Dem.OBD.OBDFreezeFrame.HandlingVariants,1 */

#define DEM_OBDFF_SUPPORT_KIND            STD_OFF

#if (defined DEM_MAX_EVENTS_PER_READINESS_GROUP)
#error DEM_MAX_EVENTS_PER_READINESS_GROUP already defined
#endif
/** \brief Maximum number of events per readiness groups
 *
 *  If calibration is enabled, this value defines the maximum number of events
 *  which can be assigned to an OBD readiness group.
 *  If calibration is disabled, this value is set to 0 which triggers an
 *  optimized implementation of OBD readiness groups.
 */
#define DEM_MAX_EVENTS_PER_READINESS_GROUP 0U

/*------------------[DTC groups configuration]------------------------------*/

/* Symbolic names of configured DTC groups */

#if (defined DEM_EMISSION_REL_DTCS_GROUP_EXIST)
#error DEM_EMISSION_REL_DTCS_GROUP_EXIST already defined
#endif
 /** \brief Switch, indicating if emision related DTC group is enabled */
#define DEM_EMISSION_REL_DTCS_GROUP_EXIST   STD_OFF

/*------------------[Warning indicators configuration]----------------------*/

/* Symbolic names of configured warning indicator IDs */


#if (defined DEM_NUMBER_OF_INDICATORS)
#error DEM_NUMBER_OF_INDICATORS already defined
#endif
/** \brief Number of warning indicators which are present in the system
 **
 ** \note Macro name is conform to the vague definition in chapter 10 of SWS.
 **/
#define DEM_NUMBER_OF_INDICATORS                0U


#if (defined DEM_NUM_INDICATOR_LINKS)
#error DEM_NUM_INDICATOR_LINKS already defined
#endif
/** \brief Number of warning indicator links
 **        In case of calibration-support a link represents an indicator class */
#define DEM_NUM_INDICATOR_LINKS                 0U


#if (defined DEM_INDICATOR_MULTIPLICITY)
#error DEM_INDICATOR_MULTIPLICITY already defined
#endif
/** \brief Number of different warning indicator which could be assigned to an
 **        event. Without calibration support the assigned indicator can not be
 **        changed.
 **/
  #define DEM_INDICATOR_MULTIPLICITY              1U


#if (defined DEM_NUM_INDICATOR_COUNTER)
#error DEM_NUM_INDICATOR_COUNTER already defined
#endif
/** \brief Number of used indicator counter in ::Dem_NvData */
  #define DEM_NUM_INDICATOR_COUNTER               DEM_NUM_INDICATOR_LINKS


#if (defined DEM_NUM_INDICATOR_COUNTER_BIT)
#error DEM_NUM_INDICATOR_COUNTER_BIT already defined
#endif
/** \brief Number of bytes to hold one bit for each indicator counter
 **        in ::Dem_NvData for IndicatorCycleCounterRole and
 **        IndicatorCycleCounterWIRStatus */
#define DEM_NUM_INDICATOR_COUNTER_BIT           ((DEM_NUM_INDICATOR_COUNTER + 7U) / 8U)



#if (defined DEM_NUM_BSWEVENT_INDICATOR_USED)
#error DEM_NUM_BSWEVENT_INDICATOR_USED already defined
#endif
/** \brief Number of BSW events which are configured for warning indicator */
#define DEM_NUM_BSWEVENT_INDICATOR_USED         0U

/*------------------[Enable conditions configuration]-----------------------*/
#if (defined DEM_NUM_ENCONDGROUPS)
#error DEM_NUM_ENCONDGROUPS already defined
#endif
/** \brief Number of enable condition groups, used for further calculation */
#define DEM_NUM_ENCONDGROUPS   0U

/* Symbolic names of configured enable conditions */

#if (defined DEM_NUM_ENABLECONDITIONS)
#error DEM_NUM_ENABLECONDITIONS already defined
#endif
/** \brief Number of enable conditions */
#define DEM_NUM_ENABLECONDITIONS 0U

#if (defined DEM_ENCONDITIONGROUP_UNUSED)
#error DEM_ENCONDITIONGROUP_UNUSED already defined
#endif
/** \brief Used in Dem_EventDesc and Dem_EventClassDesc if a dedicated event
 ** does not refer to any enable condition group */
#define DEM_ENCONDITIONGROUP_UNUSED         DEM_NUM_ENCONDGROUPS

/*------------------[Multi event triggering configuration]------------------*/

#if (defined DEM_MULTI_EVENT_TRIGGERING_CLASS_COUNT)
#error DEM_MULTI_EVENT_TRIGGERING_CLASS_COUNT already defined
#endif
/** \brief Number of multi event triggering classes */
#define DEM_MULTI_EVENT_TRIGGERING_CLASS_COUNT 0U

#if (defined DEM_MULTI_EVENT_TRIGGERING_COUNT)
#error DEM_MULTI_EVENT_TRIGGERING_COUNT already defined
#endif
/** \brief Number of multi event triggering configurations */
#define DEM_MULTI_EVENT_TRIGGERING_COUNT 0U

#if (defined DEM_MULTI_EVENT_TRIGGERING_COUNT_MAX_WIDTH)
#error DEM_MULTI_EVENT_TRIGGERING_COUNT_MAX_WIDTH already defined
#endif
/** \brief Maximum bit-width of multi event triggering configurations */
#define DEM_MULTI_EVENT_TRIGGERING_COUNT_MAX_WIDTH 8U

#if (defined DEM_MULTI_EVENT_TRIGGERING_SLAVE_COUNT)
#error DEM_MULTI_EVENT_TRIGGERING_SLAVE_COUNT already defined
#endif
/** \brief Number of configured slave events based on multi event triggering classes */
#define DEM_MULTI_EVENT_TRIGGERING_SLAVE_COUNT 0U

#if (defined DEM_MULTI_EVENT_TRIGGERING_BIT_COUNT)
#error DEM_MULTI_EVENT_TRIGGERING_BIT_COUNT already defined
#endif
/** \brief Bit-width needed to store DEM_MULTI_EVENT_TRIGGERING_COUNT */
#define DEM_MULTI_EVENT_TRIGGERING_BIT_COUNT 1U

#if (defined DEM_ROOT_ERROR_BUFFER_SIZE)
#error DEM_ROOT_ERROR_BUFFER_SIZE already defined
#endif
/** \brief Number of multi event root error queue element groups */
#define DEM_ROOT_ERROR_BUFFER_SIZE 2U

#if (defined DEM_ROOT_ERROR_ENTRY_MASK)
#error DEM_ROOT_ERROR_ENTRY_MASK already defined
#endif
/** \brief Mask used to extract multi event indeces from root error queue */
#define DEM_ROOT_ERROR_ENTRY_MASK 0x01U

#if (defined DEM_MULTIEVENTTRIGGERINGMASTERIDX_UNUSED)
#error DEM_MULTIEVENTTRIGGERINGMASTERIDX_UNUSED already defined
#endif
/** \brief Used in Dem_GetMultiEventTriggeringMasterIdx if a dedicated event
 ** does not have any entry in Dem_MultiEventTriggeringMasterEventId[] */
#define DEM_MULTIEVENTTRIGGERINGMASTERIDX_UNUSED   DEM_MULTI_EVENT_TRIGGERING_COUNT

#if (defined DEM_MULTIEVENTTRIGGERINGIDX_UNUSED)
#error DEM_MULTIEVENTTRIGGERINGIDX_UNUSED already defined
#endif
/** \brief Used in Dem_EventDesc and Dem_EventClassDesc if a dedicated event
 ** does not refer to any multi event triggering class configuration */
#define DEM_MULTIEVENTTRIGGERINGIDX_UNUSED   DEM_MULTI_EVENT_TRIGGERING_CLASS_COUNT

/*------------------[Operation and aging cycles configuration]--------------*/

#ifndef DEM_PROCESS_OPCYC_STATE
/** \brief Operation cycle processing is triggered by START/END */
#define DEM_PROCESS_OPCYC_STATE        0x00U
#endif

#ifndef DEM_PROCESS_OPCYC_COUNTER
/** \brief Operation cycle processing is triggered by collecting an external
 ** counter value */
#define DEM_PROCESS_OPCYC_COUNTER      0x01U
#endif

#if (defined DEM_OPERATION_CYCLE_PROCESSING)
#error DEM_OPERATION_CYCLE_PROCESSING already defined
#endif
/** \brief Operation cycle processing mode
 **
 ** This processing mode defines whether the operation cycles are triggered by
 ** START/END reports via Dem_SetOperationCycleState(), or collecting an
 ** external counter value via Dem_SetOperationCycleCntValue().
 **
 ** \note Macro name is NOT present in SWS. This is as per bugzilla ticket
 ** #47189.
 **/
#define DEM_OPERATION_CYCLE_PROCESSING DEM_PROCESS_OPCYC_STATE

#ifndef DEM_PROCESS_AGINGCTR_INTERN
/** \brief Aging counter processing is triggered internally */
#define DEM_PROCESS_AGINGCTR_INTERN      0x00U
#endif

#ifndef DEM_PROCESS_AGINGCTR_EXTERN
/** \brief Aging counter processing is triggered by collecting an external
 ** counter value */
#define DEM_PROCESS_AGINGCTR_EXTERN      0x01U
#endif

#if (defined DEM_AGINGCYCLE_COUNTER_PROCESSING)
#error DEM_AGINGCYCLE_COUNTER_PROCESSING already defined
#endif
/** \brief Aging counter processing mode
 **
 ** This processing mode defines whether aging is triggered via
 ** Dem_SetOperationCycleState() and Dem_SetAgingCycleState(), or via an
 ** external counter value reported by Dem_SetAgingCycleCounterValue().
 **/
#define DEM_AGINGCYCLE_COUNTER_PROCESSING DEM_PROCESS_AGINGCTR_INTERN

#if (defined DEM_PROCESS_OCCCTR_CDTC)
#error DEM_PROCESS_OCCCTR_CDTC already defined
#endif
/** \brief Occurrence counter processing is triggered
 ** after the fault confirmation was successfull
 **/
#define DEM_PROCESS_OCCCTR_CDTC    0x00U

#if (defined DEM_PROCESS_OCCCTR_TF)
#error DEM_PROCESS_OCCCTR_TF already defined
#endif
/** \brief Occurrence counter processing is triggered
 **  by the TestFailed bit only
 **/
#define DEM_PROCESS_OCCCTR_TF      0x01U

#if (defined DEM_OCCURRENCE_COUNTER_PROCESSING)
#error DEM_OCCURRENCE_COUNTER_PROCESSING already defined
#endif
/** \brief Occurrence counter processing mode
 **
 ** This switch defines the consideration of the fault confirmation
 ** process for the occurrence counter.
 **/
#define DEM_OCCURRENCE_COUNTER_PROCESSING  DEM_PROCESS_OCCCTR_TF

/* Symbolic names of configured operation cycle types */

#if (defined DEM_OPCYC_POWER_TYPE)
#error DEM_OPCYC_POWER_TYPE already defined
#endif
/** \brief Symbolic name of configured operation cycle type
** DEM_OPCYC_POWER for DEM_OPCYC_POWER.
 ** Not used in the current implementation
**/
#define DEM_OPCYC_POWER_TYPE                 2U

/* Symbolic names of configured operation cycles and failure cycles */
/* Following macro is generated by the RTE to identify if it is in synch with the current DEM configuration.
* Notwithstanding, the macro is not intended for the usage via an RTE interface but only via a c API. */
#if (DEM_OPCYC_POWER != 0)
#error Definition of macro DEM_OPCYC_POWER does not match to the DEM configuration due to RTE and DEM are out of synch. Please update the RTE based on the newest DEM BSWMD file!
#endif

/* !LINKSTO dsn.Dem.OBD.OPCYC.WARMUP.Id,1 */

#if (defined DEM_NUM_OPCYCLES)
#error DEM_NUM_OPCYCLES already defined
#endif
/** \brief Number of operation cycles */
#define DEM_NUM_OPCYCLES 1U

#if (defined DEM_OPCYC_AUTO_END_MASK_GROUP_LENGTH)
#error DEM_OPCYC_AUTO_END_MASK_GROUP_LENGTH already defined
#endif
/* Number of operation cycles, masked by one automatic end enabled mask */
#define DEM_OPCYC_AUTO_END_MASK_GROUP_LENGTH 8U

#if (defined DEM_OPCYC_AUTO_END_ENABLED)
#error DEM_OPCYC_AUTO_END_ENABLED already defined
#endif
/** \brief automatic end of opcycle configured for at least 1 opcycle */
#define DEM_OPCYC_AUTO_END_ENABLED STD_ON

#if (defined DEM_OPCYC_NUM_OF_AUTO_END_ENABLED_MASKS)
#error DEM_OPCYC_NUM_OF_AUTO_END_ENABLED_MASKS already defined
#endif
/** \brief automatic end of opcycle configured for at least 1 opcycle */
#define DEM_OPCYC_NUM_OF_AUTO_END_ENABLED_MASKS 1U

/* compile switch for OBD DCY */
/* !LINKSTO dsn.Dem.OBD.OPCYC.DCY.CompileSwitch,1 */
#if (defined DEM_OPCYC_OBD_DCY_USED)
#error DEM_OPCYC_OBD_DCY_USED already defined
#endif

/** \brief OBD DCY not used */
#define DEM_OPCYC_OBD_DCY_USED STD_OFF

/* !LINKSTO dsn.Dem.OBD.OPCYC.DCY.0001,1 */

/* !LINKSTO dsn.Dem.OBD.OPCYC.IGNITION.0001,1 */

/* Symbolic names of configured aging cycles */

#if (defined DEM_NUM_AGINGCYCLES)
#error DEM_NUM_AGINGCYCLES already defined
#endif
/** \brief Number of aging cycles
 **
 ** For these cycles, aging will not be performed based on the operation cycle
 ** of the respective event.
 **
 ** The value is always 0, if ::DEM_USE_AGING is switched off. */
#define DEM_NUM_AGINGCYCLES 0U

/*------------------[OCC5 Configuration]------------------------------------*/
/* !LINKSTO dsn.Dem.OBD.OCC5.VccOcc5Used,1 */
#if (defined DEM_VCC_OCC5_USED)
#error DEM_VCC_OCC5_USED already defined
#endif

/* !LINKSTO dsn.Dem.OBD.OCC5.Encapsulation,1 */
#define DEM_VCC_OCC5_USED          STD_OFF

/*------------------[Operation Cycle Counters Configuration]----------------*/

#if (defined DEM_OPCYCLE_CTR_CSLF_SUPPORT)
#error DEM_OPCYCLE_CTR_CSLF_SUPPORT already defined
#endif
/** \brief Macro for availability of feature cycles since last failed */

#define DEM_OPCYCLE_CTR_CSLF_SUPPORT          STD_OFF

#if (defined DEM_OPCYCLE_CTR_CSFF_SUPPORT)
#error DEM_OPCYCLE_CTR_CSFF_SUPPORT already defined
#endif
/** \brief Macro for availability of feature cycles since first failed */

#define DEM_OPCYCLE_CTR_CSFF_SUPPORT          STD_OFF

#if (defined DEM_OPCYCLE_CTRS_SUPPORT)
#error DEM_OPCYCLE_CTRS_SUPPORT already defined
#endif
/** \brief Macro for availability of any of the cycle counters as specified by AUTOSAR */
#if ( (DEM_OPCYCLE_CTR_CSLF_SUPPORT == STD_ON) || (DEM_OPCYCLE_CTR_CSFF_SUPPORT == STD_ON) )
#define DEM_OPCYCLE_CTRS_SUPPORT          STD_ON
#else
#define DEM_OPCYCLE_CTRS_SUPPORT          STD_OFF
#endif

/*------------------[Dem BSW Distribution macro]--------------------------------------*/

#if (defined DEM_BSW_DISTRIBUTION_FOR_BSW_EVENT_REPORTING)
#error DEM_BSW_DISTRIBUTION_FOR_BSW_EVENT_REPORTING already defined
#endif
/** \brief Macro for verifying if the Dem Multi-Core functionality is enabled */
#define DEM_BSW_DISTRIBUTION_FOR_BSW_EVENT_REPORTING STD_OFF
/*==================[type definitions]======================================*/

/*------------------[Dem_ConfigType]----------------------------------------*/

/** \brief This type of the external data structure shall contain the post
 **  build initialization data for the Dem.
 **
 ** \note Type is unused, as only pre-compile time support is implemented. */
typedef uint8 Dem_ConfigType;

/*------------------[Dem_FFSegIdxType]--------------------------------------*/

/** \brief Index of freeze frame segment type
 **
 ** Index concerning ::Dem_FFSegments[].
 **
 ** Note: The range (maximum of 65500) of this type is limited by the
 ** configuration (multiplicity of parameter DemDidClass).
 */
typedef uint16 Dem_FFSegIdxType;

/*==================[external function declarations]========================*/

/*==================[internal function declarations]========================*/

/*==================[external constants]====================================*/


#define DEM_START_SEC_CONST_8
#include <Dem_MemMap.h>

/** \brief Configuration structure */
extern CONST(Dem_ConfigType, DEM_CONST) Dem_Config_0;

#define DEM_STOP_SEC_CONST_8
#include <Dem_MemMap.h>

/* !LINKSTO Dem.Dem_FFSegId.External,1 */

/*==================[internal constants]====================================*/

/*==================[external data]=========================================*/

/*==================[internal data]=========================================*/

/*==================[external function definitions]=========================*/

/*==================[internal function definitions]=========================*/

#endif /* ifndef DEM_CFG_H */
/*==================[end of file]===========================================*/
