#ifndef RTE_DCM_H
#define RTE_DCM_H
/**
 * \file
 *
 * \brief AUTOSAR Rte
 *
 * This file contains the implementation of the AUTOSAR
 * module Rte.
 *
 * \version 6.9.3
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2023 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

/*
 * This file contains Rte component declarations for component type Dcm
 *
 * This file has been automatically generated by
 * EB tresos AutoCore Rte Generator Version 6.9.3
 */

/*
 * \addtogroup Rte Runtime Environment
 * @{
 */

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */
/* ==================[Includes]=============================================== */
#include <Rte_Intern.h>
#include <Rte_Main.h>
#include <Rte_Dcm_Type.h>
#include <Rte_Dcm_Hook.h>
#include <Rte_Components_Shared.h>

/* ==================[Macros]================================================= */
#ifndef RTE_CORE /* if included by software component */
#ifndef RTE_APPLICATION_HEADER_FILE_H /* prevent double inclusion */
#define RTE_APPLICATION_HEADER_FILE_H
#else
#error Multiple application header files included.
#endif
#if (!defined(RTE_RUNNABLEAPI_RE_GetSecurityLevel)) && (!defined(RTE_RUNNABLEAPI_RE_GetSesCtrlType)) && (!defined(RTE_RUNNABLEAPI_RE_GetActiveProtocol)) && (!defined(RTE_RUNNABLEAPI_RE_ResetToDefaultSession)) && (!defined(RTE_RUNNABLEAPI_RE_SetActiveDiagnostic)) && (!defined(RTE_RUNNABLEAPI_RE_MainFunction))
#define RTE_RUNNABLEAPI_RE_GetSecurityLevel
#define RTE_RUNNABLEAPI_RE_GetSesCtrlType
#define RTE_RUNNABLEAPI_RE_GetActiveProtocol
#define RTE_RUNNABLEAPI_RE_ResetToDefaultSession
#define RTE_RUNNABLEAPI_RE_SetActiveDiagnostic
#define RTE_RUNNABLEAPI_RE_MainFunction
#endif
#endif
/* ------------------[API mapping]-------------------------------------------- */
#ifndef RTE_CORE /* if included by software component */
#if defined(RTE_RUNNABLEAPI_RE_MainFunction)
#define Rte_Call_SecurityAccess_DcmDspSecurityAlv_GetSeed Rte_Call_Dcm_SecurityAccess_DcmDspSecurityAlv_GetSeed/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_SecurityAccess_DcmDspSecurityAlv_CompareKey Rte_Call_Dcm_SecurityAccess_DcmDspSecurityAlv_CompareKey/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_4024_SWSystemTimeData_ReadData Rte_Call_Dcm_DataServices_DID_4024_SWSystemTimeData_ReadData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_FD00_HWVersionData_WriteData Rte_Call_Dcm_DataServices_DID_FD00_HWVersionData_WriteData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_FD00_HWVersionData_ReadData Rte_Call_Dcm_DataServices_DID_FD00_HWVersionData_ReadData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_FD01_SWVersionData_ReadData Rte_Call_Dcm_DataServices_DID_FD01_SWVersionData_ReadData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_FD03_AEETraceabilityNumberData_WriteData Rte_Call_Dcm_DataServices_DID_FD03_AEETraceabilityNumberData_WriteData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_FD03_AEETraceabilityNumberData_ReadData Rte_Call_Dcm_DataServices_DID_FD03_AEETraceabilityNumberData_ReadData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_FD08_ResetCauseData_ReadData Rte_Call_Dcm_DataServices_DID_FD08_ResetCauseData_ReadData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_FD09_LastWarmResetParamData_ReadData Rte_Call_Dcm_DataServices_DID_FD09_LastWarmResetParamData_ReadData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_FD62_EccOccurenceNbData_ReadData Rte_Call_Dcm_DataServices_DID_FD62_EccOccurenceNbData_ReadData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_FEFF_MeasurementFramesConfData_WriteData Rte_Call_Dcm_DataServices_DID_FEFF_MeasurementFramesConfData_WriteData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_FEFF_MeasurementFramesConfData_ReadData Rte_Call_Dcm_DataServices_DID_FEFF_MeasurementFramesConfData_ReadData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_FE00_AllEventStatusesRead_ReadData Rte_Call_Dcm_DataServices_DID_FE00_AllEventStatusesRead_ReadData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_FD8B_ECUManufacturingDateData_WriteData Rte_Call_Dcm_DataServices_DID_FD8B_ECUManufacturingDateData_WriteData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_FD8B_ECUManufacturingDateData_ReadData Rte_Call_Dcm_DataServices_DID_FD8B_ECUManufacturingDateData_ReadData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_FD8C_AssemblySerialNumber_WriteData Rte_Call_Dcm_DataServices_DID_FD8C_AssemblySerialNumber_WriteData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_FD8C_AssemblySerialNumber_ReadData Rte_Call_Dcm_DataServices_DID_FD8C_AssemblySerialNumber_ReadData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_FD0F_BatteryMeasureData_ReadData Rte_Call_Dcm_DataServices_DID_FD0F_BatteryMeasureData_ReadData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_FD10_ECUTemperatureData_ReadData Rte_Call_Dcm_DataServices_DID_FD10_ECUTemperatureData_ReadData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_FDE0_EcsVariantData_WriteData Rte_Call_Dcm_DataServices_DID_FDE0_EcsVariantData_WriteData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_FDE0_EcsVariantData_ReadData Rte_Call_Dcm_DataServices_DID_FDE0_EcsVariantData_ReadData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_FDE1_EcsParametersData_WriteData Rte_Call_Dcm_DataServices_DID_FDE1_EcsParametersData_WriteData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_FDE1_EcsParametersData_ReadData Rte_Call_Dcm_DataServices_DID_FDE1_EcsParametersData_ReadData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_FDE2_AccOffsetData_WriteData Rte_Call_Dcm_DataServices_DID_FDE2_AccOffsetData_WriteData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_FDE2_AccOffsetData_ReadData Rte_Call_Dcm_DataServices_DID_FDE2_AccOffsetData_ReadData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_FDE3_EcsProfilesData_WriteData Rte_Call_Dcm_DataServices_DID_FDE3_EcsProfilesData_WriteData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_FDE3_EcsProfilesData_ReadData Rte_Call_Dcm_DataServices_DID_FDE3_EcsProfilesData_ReadData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_FDE4_EcsStepsData_WriteData Rte_Call_Dcm_DataServices_DID_FDE4_EcsStepsData_WriteData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_FDE4_EcsStepsData_ReadData Rte_Call_Dcm_DataServices_DID_FDE4_EcsStepsData_ReadData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_FDE5_EcsAccLowPassData_WriteData Rte_Call_Dcm_DataServices_DID_FDE5_EcsAccLowPassData_WriteData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_FDE5_EcsAccLowPassData_ReadData Rte_Call_Dcm_DataServices_DID_FDE5_EcsAccLowPassData_ReadData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_FDE7_AlgoOutputDelayData_WriteData Rte_Call_Dcm_DataServices_DID_FDE7_AlgoOutputDelayData_WriteData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_FDE7_AlgoOutputDelayData_ReadData Rte_Call_Dcm_DataServices_DID_FDE7_AlgoOutputDelayData_ReadData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_FDE9_SensitivityLutData_WriteData Rte_Call_Dcm_DataServices_DID_FDE9_SensitivityLutData_WriteData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_FDE9_SensitivityLutData_ReadData Rte_Call_Dcm_DataServices_DID_FDE9_SensitivityLutData_ReadData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_FDEA_SensitivityOptData_WriteData Rte_Call_Dcm_DataServices_DID_FDEA_SensitivityOptData_WriteData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_FDEA_SensitivityOptData_ReadData Rte_Call_Dcm_DataServices_DID_FDEA_SensitivityOptData_ReadData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_FDFF_MeasurementFrameConfDataRam_WriteData Rte_Call_Dcm_DataServices_DID_FDFF_MeasurementFrameConfDataRam_WriteData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_FDFF_MeasurementFrameConfDataRam_ReadData Rte_Call_Dcm_DataServices_DID_FDFF_MeasurementFrameConfDataRam_ReadData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_F187_VWSparePartNumberData_WriteData Rte_Call_Dcm_DataServices_DID_F187_VWSparePartNumberData_WriteData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_F187_VWSparePartNumberData_ReadData Rte_Call_Dcm_DataServices_DID_F187_VWSparePartNumberData_ReadData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_F189_VWApplicationSoftwareVersionNumberData_WriteData Rte_Call_Dcm_DataServices_DID_F189_VWApplicationSoftwareVersionNumberData_WriteData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_F189_VWApplicationSoftwareVersionNumberData_ReadData Rte_Call_Dcm_DataServices_DID_F189_VWApplicationSoftwareVersionNumberData_ReadData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_F191_VWECUHardwareNumberData_WriteData Rte_Call_Dcm_DataServices_DID_F191_VWECUHardwareNumberData_WriteData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_F191_VWECUHardwareNumberData_ReadData Rte_Call_Dcm_DataServices_DID_F191_VWECUHardwareNumberData_ReadData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_F197_VWSystemNameOrEngineTypeData_WriteData Rte_Call_Dcm_DataServices_DID_F197_VWSystemNameOrEngineTypeData_WriteData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_F197_VWSystemNameOrEngineTypeData_ReadData Rte_Call_Dcm_DataServices_DID_F197_VWSystemNameOrEngineTypeData_ReadData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_F1B4_TechnicalSpecificationsVersionData_ReadData Rte_Call_Dcm_DataServices_DID_F1B4_TechnicalSpecificationsVersionData_ReadData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_0407_VWLogicalSoftwareBlockCounterOfProgrammingAttemptsData_ReadData Rte_Call_Dcm_DataServices_DID_0407_VWLogicalSoftwareBlockCounterOfProgrammingAttemptsData_ReadData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_040F_VWLogicalSoftwareBlockLockValueData_ReadData Rte_Call_Dcm_DataServices_DID_040F_VWLogicalSoftwareBlockLockValueData_ReadData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_0410_BootloaderTPBlocksizeData_WriteData Rte_Call_Dcm_DataServices_DID_0410_BootloaderTPBlocksizeData_WriteData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_0410_BootloaderTPBlocksizeData_ReadData Rte_Call_Dcm_DataServices_DID_0410_BootloaderTPBlocksizeData_ReadData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_0448_ProgrammingPreconditionsData_ReadData Rte_Call_Dcm_DataServices_DID_0448_ProgrammingPreconditionsData_ReadData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_F1DF_ECUProgrammingInformationData_ReadData Rte_Call_Dcm_DataServices_DID_F1DF_ECUProgrammingInformationData_ReadData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_F19E_ASAMODXFileIdentifierData_WriteData Rte_Call_Dcm_DataServices_DID_F19E_ASAMODXFileIdentifierData_WriteData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_F19E_ASAMODXFileIdentifierData_ReadData Rte_Call_Dcm_DataServices_DID_F19E_ASAMODXFileIdentifierData_ReadData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_F1A2_ASAMODXFileVersionData_WriteData Rte_Call_Dcm_DataServices_DID_F1A2_ASAMODXFileVersionData_WriteData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_F1A2_ASAMODXFileVersionData_ReadData Rte_Call_Dcm_DataServices_DID_F1A2_ASAMODXFileVersionData_ReadData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_F1D5_FDSProjectData_ReadData Rte_Call_Dcm_DataServices_DID_F1D5_FDSProjectData_ReadData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_F1A3_VWECUHardwareVersionNumberData_WriteData Rte_Call_Dcm_DataServices_DID_F1A3_VWECUHardwareVersionNumberData_WriteData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_F1A3_VWECUHardwareVersionNumberData_ReadData Rte_Call_Dcm_DataServices_DID_F1A3_VWECUHardwareVersionNumberData_ReadData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_F18C_ECUSerialNumberData_WriteData Rte_Call_Dcm_DataServices_DID_F18C_ECUSerialNumberData_WriteData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_F18C_ECUSerialNumberData_ReadData Rte_Call_Dcm_DataServices_DID_F18C_ECUSerialNumberData_ReadData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_F1AB_VWLogicalSoftwareBlockVersionData_ReadData Rte_Call_Dcm_DataServices_DID_F1AB_VWLogicalSoftwareBlockVersionData_ReadData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_F15B_FingerprintAndProgrammingDateOfLogicalSoftwareBlocksData_ReadData Rte_Call_Dcm_DataServices_DID_F15B_FingerprintAndProgrammingDateOfLogicalSoftwareBlocksData_ReadData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_0236_ProgrammingDataElockEcuData_WriteData Rte_Call_Dcm_DataServices_DID_0236_ProgrammingDataElockEcuData_WriteData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_0236_ProgrammingDataElockEcuData_ReadData Rte_Call_Dcm_DataServices_DID_0236_ProgrammingDataElockEcuData_ReadData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_023E_WSCForProgrammingElockEcuData_WriteData Rte_Call_Dcm_DataServices_DID_023E_WSCForProgrammingElockEcuData_WriteData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_DataServices_DID_023E_WSCForProgrammingElockEcuData_ReadData Rte_Call_Dcm_DataServices_DID_023E_WSCForProgrammingElockEcuData_ReadData/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_ServiceRequestSupplierNotification_DcmDslServiceRequestSupplierNotification_Indication Rte_Call_Dcm_ServiceRequestSupplierNotification_DcmDslServiceRequestSupplierNotification_Indication/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_ServiceRequestSupplierNotification_DcmDslServiceRequestSupplierNotification_Confirmation Rte_Call_Dcm_ServiceRequestSupplierNotification_DcmDslServiceRequestSupplierNotification_Confirmation/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_RoutineServices_DcmDspRoutineCtrl_Lock_UnlockECU_Start Rte_Call_Dcm_RoutineServices_DcmDspRoutineCtrl_Lock_UnlockECU_Start/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_RoutineServices_DcmDspRoutineCtrl_Lock_UnlockECU_Stop Rte_Call_Dcm_RoutineServices_DcmDspRoutineCtrl_Lock_UnlockECU_Stop/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_RoutineServices_DcmDspRoutineCtrl_Lock_UnlockECU_RequestResults Rte_Call_Dcm_RoutineServices_DcmDspRoutineCtrl_Lock_UnlockECU_RequestResults/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_RoutineServices_DcmDspRoutineProcessMode_Start Rte_Call_Dcm_RoutineServices_DcmDspRoutineProcessMode_Start/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_RoutineServices_DcmDspRoutineProcessMode_Stop Rte_Call_Dcm_RoutineServices_DcmDspRoutineProcessMode_Stop/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_RoutineServices_DcmDspRoutineProcessMode_RequestResults Rte_Call_Dcm_RoutineServices_DcmDspRoutineProcessMode_RequestResults/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_RoutineServices_DcmDspRoutineAccCalib_Start Rte_Call_Dcm_RoutineServices_DcmDspRoutineAccCalib_Start/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_RoutineServices_DcmDspRoutineLockSolenoid_Start Rte_Call_Dcm_RoutineServices_DcmDspRoutineLockSolenoid_Start/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_RoutineServices_DcmDspRoutineLockSolenoid_Stop Rte_Call_Dcm_RoutineServices_DcmDspRoutineLockSolenoid_Stop/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_RoutineServices_DcmDspRoutineEcuTempCalibration_Start Rte_Call_Dcm_RoutineServices_DcmDspRoutineEcuTempCalibration_Start/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_RoutineServices_DcmDspRoutineAccAngleOffsetCalibration_Start Rte_Call_Dcm_RoutineServices_DcmDspRoutineAccAngleOffsetCalibration_Start/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_RoutineServices_DcmDspRoutineRoutineCheckProgrammingPreconditions_Start Rte_Call_Dcm_RoutineServices_DcmDspRoutineRoutineCheckProgrammingPreconditions_Start/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_CallBackDCMRequestServices_CBReqServInd_1_StartProtocol Rte_Call_Dcm_CallBackDCMRequestServices_CBReqServInd_1_StartProtocol/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define Rte_Call_CallBackDCMRequestServices_CBReqServInd_1_StopProtocol Rte_Call_Dcm_CallBackDCMRequestServices_CBReqServInd_1_StopProtocol/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#endif
#endif

/* ------------------[port handle API mapping]-------------------------------- */
#ifndef RTE_CORE /* if included by software component */
#endif

#define RTE_E_Dcm_ASR42_DCMServices_E_NOT_OK 1U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DCMServices_E_NOT_OK 1U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_SecurityAccess_DcmDspSecurityAlv_E_NOT_OK 1U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_SecurityAccess_DcmDspSecurityAlv_DCM_E_PENDING 10U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_SecurityAccess_DcmDspSecurityAlv_DCM_E_COMPARE_KEY_FAILED 11U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_4024_SWSystemTimeData_E_NOT_OK 1U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_FD00_HWVersionData_E_NOT_OK 1U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_FD00_HWVersionData_DCM_E_PENDING 10U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_FD01_SWVersionData_E_NOT_OK 1U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_FD03_AEETraceabilityNumberData_E_NOT_OK 1U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_FD03_AEETraceabilityNumberData_DCM_E_PENDING 10U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_FD08_ResetCauseData_E_NOT_OK 1U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_FD09_LastWarmResetParamData_E_NOT_OK 1U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_FD62_EccOccurenceNbData_E_NOT_OK 1U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_FEFF_MeasurementFramesConfData_E_NOT_OK 1U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_FEFF_MeasurementFramesConfData_DCM_E_PENDING 10U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_FE00_AllEventStatusesRead_E_NOT_OK 1U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_FD8B_ECUManufacturingDateData_E_NOT_OK 1U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_FD8B_ECUManufacturingDateData_DCM_E_PENDING 10U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_FD8C_AssemblySerialNumber_E_NOT_OK 1U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_FD8C_AssemblySerialNumber_DCM_E_PENDING 10U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_FD0F_BatteryMeasureData_E_NOT_OK 1U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_FD0F_BatteryMeasureData_DCM_E_PENDING 10U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_FD10_ECUTemperatureData_E_NOT_OK 1U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_FD10_ECUTemperatureData_DCM_E_PENDING 10U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_FDE0_EcsVariantData_E_NOT_OK 1U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_FDE0_EcsVariantData_DCM_E_PENDING 10U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_FDE1_EcsParametersData_E_NOT_OK 1U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_FDE1_EcsParametersData_DCM_E_PENDING 10U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_FDE2_AccOffsetData_E_NOT_OK 1U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_FDE2_AccOffsetData_DCM_E_PENDING 10U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_FDE3_EcsProfilesData_E_NOT_OK 1U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_FDE3_EcsProfilesData_DCM_E_PENDING 10U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_FDE4_EcsStepsData_E_NOT_OK 1U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_FDE4_EcsStepsData_DCM_E_PENDING 10U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_FDE5_EcsAccLowPassData_E_NOT_OK 1U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_FDE5_EcsAccLowPassData_DCM_E_PENDING 10U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_FDE7_AlgoOutputDelayData_E_NOT_OK 1U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_FDE7_AlgoOutputDelayData_DCM_E_PENDING 10U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_FDE9_SensitivityLutData_E_NOT_OK 1U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_FDE9_SensitivityLutData_DCM_E_PENDING 10U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_FDEA_SensitivityOptData_E_NOT_OK 1U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_FDEA_SensitivityOptData_DCM_E_PENDING 10U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_FDFF_MeasurementFrameConfDataRam_E_NOT_OK 1U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_FDFF_MeasurementFrameConfDataRam_DCM_E_PENDING 10U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_F187_VWSparePartNumberData_E_NOT_OK 1U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_F187_VWSparePartNumberData_DCM_E_PENDING 10U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_F189_VWApplicationSoftwareVersionNumberData_E_NOT_OK 1U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_F189_VWApplicationSoftwareVersionNumberData_DCM_E_PENDING 10U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_F191_VWECUHardwareNumberData_E_NOT_OK 1U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_F191_VWECUHardwareNumberData_DCM_E_PENDING 10U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_F197_VWSystemNameOrEngineTypeData_E_NOT_OK 1U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_F197_VWSystemNameOrEngineTypeData_DCM_E_PENDING 10U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_F1B4_TechnicalSpecificationsVersionData_E_NOT_OK 1U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_F1B4_TechnicalSpecificationsVersionData_DCM_E_PENDING 10U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_0407_VWLogicalSoftwareBlockCounterOfProgrammingAttemptsData_E_NOT_OK 1U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_0407_VWLogicalSoftwareBlockCounterOfProgrammingAttemptsData_DCM_E_PENDING 10U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_040F_VWLogicalSoftwareBlockLockValueData_E_NOT_OK 1U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_040F_VWLogicalSoftwareBlockLockValueData_DCM_E_PENDING 10U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_0410_BootloaderTPBlocksizeData_E_NOT_OK 1U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_0410_BootloaderTPBlocksizeData_DCM_E_PENDING 10U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_0448_ProgrammingPreconditionsData_E_NOT_OK 1U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_0448_ProgrammingPreconditionsData_DCM_E_PENDING 10U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_F1DF_ECUProgrammingInformationData_E_NOT_OK 1U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_F1DF_ECUProgrammingInformationData_DCM_E_PENDING 10U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_F19E_ASAMODXFileIdentifierData_E_NOT_OK 1U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_F19E_ASAMODXFileIdentifierData_DCM_E_PENDING 10U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_F1A2_ASAMODXFileVersionData_E_NOT_OK 1U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_F1A2_ASAMODXFileVersionData_DCM_E_PENDING 10U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_F1D5_FDSProjectData_E_NOT_OK 1U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_F1D5_FDSProjectData_DCM_E_PENDING 10U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_F1A3_VWECUHardwareVersionNumberData_E_NOT_OK 1U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_F1A3_VWECUHardwareVersionNumberData_DCM_E_PENDING 10U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_F18C_ECUSerialNumberData_E_NOT_OK 1U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_F18C_ECUSerialNumberData_DCM_E_PENDING 10U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_F1AB_VWLogicalSoftwareBlockVersionData_E_NOT_OK 1U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_F1AB_VWLogicalSoftwareBlockVersionData_DCM_E_PENDING 10U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_F15B_FingerprintAndProgrammingDateOfLogicalSoftwareBlocksData_E_NOT_OK 1U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_F15B_FingerprintAndProgrammingDateOfLogicalSoftwareBlocksData_DCM_E_PENDING 10U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_0236_ProgrammingDataElockEcuData_E_NOT_OK 1U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_0236_ProgrammingDataElockEcuData_DCM_E_PENDING 10U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_023E_WSCForProgrammingElockEcuData_E_NOT_OK 1U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_DataServices_DID_023E_WSCForProgrammingElockEcuData_DCM_E_PENDING 10U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_ServiceRequestNotification_E_NOT_OK 1U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_ServiceRequestNotification_E_REQUEST_NOT_ACCEPTED 8U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_RoutineServices_DcmDspRoutineCtrl_Lock_UnlockECU_E_NOT_OK 1U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_RoutineServices_DcmDspRoutineCtrl_Lock_UnlockECU_DCM_E_PENDING 10U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_RoutineServices_DcmDspRoutineCtrl_Lock_UnlockECU_DCM_E_FORCE_RCRRP 12U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_RoutineServices_DcmDspRoutineProcessMode_E_NOT_OK 1U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_RoutineServices_DcmDspRoutineProcessMode_DCM_E_PENDING 10U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_RoutineServices_DcmDspRoutineProcessMode_DCM_E_FORCE_RCRRP 12U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_RoutineServices_DcmDspRoutineAccCalib_E_NOT_OK 1U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_RoutineServices_DcmDspRoutineAccCalib_DCM_E_PENDING 10U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_RoutineServices_DcmDspRoutineAccCalib_DCM_E_FORCE_RCRRP 12U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_RoutineServices_DcmDspRoutineLockSolenoid_E_NOT_OK 1U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_RoutineServices_DcmDspRoutineLockSolenoid_DCM_E_PENDING 10U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_RoutineServices_DcmDspRoutineLockSolenoid_DCM_E_FORCE_RCRRP 12U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_RoutineServices_DcmDspRoutineEcuTempCalibration_E_NOT_OK 1U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_RoutineServices_DcmDspRoutineEcuTempCalibration_DCM_E_PENDING 10U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_RoutineServices_DcmDspRoutineEcuTempCalibration_DCM_E_FORCE_RCRRP 12U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_RoutineServices_DcmDspRoutineAccAngleOffsetCalibration_E_NOT_OK 1U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_RoutineServices_DcmDspRoutineAccAngleOffsetCalibration_DCM_E_PENDING 10U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_RoutineServices_DcmDspRoutineAccAngleOffsetCalibration_DCM_E_FORCE_RCRRP 12U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_RoutineServices_DcmDspRoutineRoutineCheckProgrammingPreconditions_E_NOT_OK 1U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_RoutineServices_DcmDspRoutineRoutineCheckProgrammingPreconditions_DCM_E_PENDING 10U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_RoutineServices_DcmDspRoutineRoutineCheckProgrammingPreconditions_DCM_E_FORCE_RCRRP 12U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_CallbackDCMRequestServices_E_NOT_OK 1U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#define RTE_E_CallbackDCMRequestServices_E_PROTOCOL_NOT_ALLOWED 5U/* RTE.Review.PreprocessorMacro.ReadOnly.Justification: The value/identifier returned by the preprocessor macro is read-only and cannot be modified by the user. */
#ifndef RTE_CORE /* if included by software component */
#endif

/* ==================[Types]================================================== */
#ifndef RTE_CORE /* if included by software component */
typedef CONSTP2CONST(Rte_CDS_Dcm, TYPEDEF, RTE_CONST) Rte_Instance;
#endif

/* ==================[Definition of variables with external linkage]========== */
#define RTE_START_SEC_CONST_8
#include <Rte_MemMap.h>
extern CONST(Rte_CDS_Dcm, RTE_CONST) Rte_Instance_Dcm;
#define RTE_STOP_SEC_CONST_8
#include <Rte_MemMap.h>
#define RTE_START_SEC_CONST_32
#include <Rte_MemMap.h>
extern CONSTP2CONST(Rte_CDS_Dcm, RTE_CONST, RTE_CONST) Rte_Inst_Dcm;
#define RTE_STOP_SEC_CONST_32
#include <Rte_MemMap.h>

/* ==================[Declaration of functions with external linkage]========= */
/* ------------------[declaration of runnable entities]----------------------- */
#define Dcm_START_SEC_CODE
#include <Dcm_MemMap.h>
extern FUNC(Std_ReturnType, RTE_CODE) Dcm_GetSecurityLevel (P2VAR(Dcm_SecLevelType, AUTOMATIC, RTE_APPL_DATA) SecLevel);

extern FUNC(Std_ReturnType, RTE_CODE) Dcm_GetSesCtrlType (P2VAR(Dcm_SesCtrlType, AUTOMATIC, RTE_APPL_DATA) SesCtrlType);

extern FUNC(Std_ReturnType, RTE_CODE) Dcm_GetActiveProtocol (P2VAR(Dcm_ProtocolType, AUTOMATIC, RTE_APPL_DATA) ActiveProtocol);

extern FUNC(Std_ReturnType, RTE_CODE) Dcm_ResetToDefaultSession (void);

extern FUNC(Std_ReturnType, RTE_CODE) Dcm_SetActiveDiagnostic (boolean active);

#define Dcm_STOP_SEC_CODE
#include <Dcm_MemMap.h>

/* ------------------[declaration of API functions provided by Rte]----------- */
#define RTE_START_SEC_CODE
#include <Rte_MemMap.h>
#if (defined(RTE_CORE)) || (defined(RTE_RUNNABLEAPI_RE_MainFunction))
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_SecurityAccess_DcmDspSecurityAlv_GetSeed (Dcm_OpStatusType OpStatus, P2VAR(Dcm_SecSeedDcmDspSecurityAlv_ArrayType, AUTOMATIC, RTE_APPL_DATA) Seed, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_SecurityAccess_DcmDspSecurityAlv_GetSeed (Dcm_OpStatusType OpStatus, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Seed, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_SecurityAccess_DcmDspSecurityAlv_CompareKey (P2CONST(Dcm_SecKeyDcmDspSecurityAlv_ArrayType, AUTOMATIC, RTE_APPL_DATA) Key, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_SecurityAccess_DcmDspSecurityAlv_CompareKey (P2CONST(uint8, AUTOMATIC, RTE_APPL_DATA) Key, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_4024_SWSystemTimeData_ReadData (P2VAR(Dcm_DataDID_4024_SWSystemTimeData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_4024_SWSystemTimeData_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FD00_HWVersionData_WriteData (P2CONST(Dcm_DataDID_FD00_HWVersionData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FD00_HWVersionData_WriteData (P2CONST(uint8, AUTOMATIC, RTE_APPL_DATA) Data, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FD00_HWVersionData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(Dcm_DataDID_FD00_HWVersionData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FD00_HWVersionData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FD01_SWVersionData_ReadData (P2VAR(Dcm_DataDID_FD01_SWVersionData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FD01_SWVersionData_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FD03_AEETraceabilityNumberData_WriteData (P2CONST(Dcm_DataDID_FD03_AEETraceabilityNumberData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FD03_AEETraceabilityNumberData_WriteData (P2CONST(uint8, AUTOMATIC, RTE_APPL_DATA) Data, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FD03_AEETraceabilityNumberData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(Dcm_DataDID_FD03_AEETraceabilityNumberData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FD03_AEETraceabilityNumberData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FD08_ResetCauseData_ReadData (P2VAR(Dcm_DataDID_FD08_ResetCauseData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FD08_ResetCauseData_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FD09_LastWarmResetParamData_ReadData (P2VAR(Dcm_DataDID_FD09_LastWarmResetParamData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FD09_LastWarmResetParamData_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FD62_EccOccurenceNbData_ReadData (P2VAR(Dcm_DataDID_FD62_EccOccurenceNbData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FD62_EccOccurenceNbData_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FEFF_MeasurementFramesConfData_WriteData (P2CONST(Dcm_DataDID_FEFF_MeasurementFramesConfData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FEFF_MeasurementFramesConfData_WriteData (P2CONST(uint8, AUTOMATIC, RTE_APPL_DATA) Data, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FEFF_MeasurementFramesConfData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(Dcm_DataDID_FEFF_MeasurementFramesConfData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FEFF_MeasurementFramesConfData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FE00_AllEventStatusesRead_ReadData (P2VAR(Dcm_DataDID_FE00_AllEventStatusesRead_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FE00_AllEventStatusesRead_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FD8B_ECUManufacturingDateData_WriteData (P2CONST(Dcm_DataDID_FD8B_ECUManufacturingDateData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FD8B_ECUManufacturingDateData_WriteData (P2CONST(uint8, AUTOMATIC, RTE_APPL_DATA) Data, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FD8B_ECUManufacturingDateData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(Dcm_DataDID_FD8B_ECUManufacturingDateData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FD8B_ECUManufacturingDateData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FD8C_AssemblySerialNumber_WriteData (P2CONST(Dcm_DataDID_FD8C_AssemblySerialNumber_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FD8C_AssemblySerialNumber_WriteData (P2CONST(uint8, AUTOMATIC, RTE_APPL_DATA) Data, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FD8C_AssemblySerialNumber_ReadData (Dcm_OpStatusType OpStatus, P2VAR(Dcm_DataDID_FD8C_AssemblySerialNumber_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FD8C_AssemblySerialNumber_ReadData (Dcm_OpStatusType OpStatus, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FD0F_BatteryMeasureData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(Dcm_DataDID_FD0F_BatteryMeasureData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FD0F_BatteryMeasureData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FD10_ECUTemperatureData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(Dcm_DataDID_FD10_ECUTemperatureData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FD10_ECUTemperatureData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FDE0_EcsVariantData_WriteData (P2CONST(Dcm_DataDID_FDE0_EcsVariantData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FDE0_EcsVariantData_WriteData (P2CONST(uint8, AUTOMATIC, RTE_APPL_DATA) Data, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FDE0_EcsVariantData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(Dcm_DataDID_FDE0_EcsVariantData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FDE0_EcsVariantData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FDE1_EcsParametersData_WriteData (P2CONST(Dcm_DataDID_FDE1_EcsParametersData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FDE1_EcsParametersData_WriteData (P2CONST(uint8, AUTOMATIC, RTE_APPL_DATA) Data, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FDE1_EcsParametersData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(Dcm_DataDID_FDE1_EcsParametersData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FDE1_EcsParametersData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FDE2_AccOffsetData_WriteData (P2CONST(Dcm_DataDID_FDE2_AccOffsetData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FDE2_AccOffsetData_WriteData (P2CONST(uint8, AUTOMATIC, RTE_APPL_DATA) Data, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FDE2_AccOffsetData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(Dcm_DataDID_FDE2_AccOffsetData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FDE2_AccOffsetData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FDE3_EcsProfilesData_WriteData (P2CONST(Dcm_DataDID_FDE3_EcsProfilesData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FDE3_EcsProfilesData_WriteData (P2CONST(uint8, AUTOMATIC, RTE_APPL_DATA) Data, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FDE3_EcsProfilesData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(Dcm_DataDID_FDE3_EcsProfilesData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FDE3_EcsProfilesData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FDE4_EcsStepsData_WriteData (P2CONST(Dcm_DataDID_FDE4_EcsStepsData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FDE4_EcsStepsData_WriteData (P2CONST(uint8, AUTOMATIC, RTE_APPL_DATA) Data, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FDE4_EcsStepsData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(Dcm_DataDID_FDE4_EcsStepsData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FDE4_EcsStepsData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FDE5_EcsAccLowPassData_WriteData (P2CONST(Dcm_DataDID_FDE5_EcsAccLowPassData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FDE5_EcsAccLowPassData_WriteData (P2CONST(uint8, AUTOMATIC, RTE_APPL_DATA) Data, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FDE5_EcsAccLowPassData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(Dcm_DataDID_FDE5_EcsAccLowPassData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FDE5_EcsAccLowPassData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FDE7_AlgoOutputDelayData_WriteData (P2CONST(Dcm_DataDID_FDE7_AlgoOutputDelayData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FDE7_AlgoOutputDelayData_WriteData (P2CONST(uint8, AUTOMATIC, RTE_APPL_DATA) Data, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FDE7_AlgoOutputDelayData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(Dcm_DataDID_FDE7_AlgoOutputDelayData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FDE7_AlgoOutputDelayData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FDE9_SensitivityLutData_WriteData (P2CONST(Dcm_DataDID_FDE9_SensitivityLutData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FDE9_SensitivityLutData_WriteData (P2CONST(uint8, AUTOMATIC, RTE_APPL_DATA) Data, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FDE9_SensitivityLutData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(Dcm_DataDID_FDE9_SensitivityLutData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FDE9_SensitivityLutData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FDEA_SensitivityOptData_WriteData (P2CONST(Dcm_DataDID_FDEA_SensitivityOptData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FDEA_SensitivityOptData_WriteData (P2CONST(uint8, AUTOMATIC, RTE_APPL_DATA) Data, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FDEA_SensitivityOptData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(Dcm_DataDID_FDEA_SensitivityOptData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FDEA_SensitivityOptData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FDFF_MeasurementFrameConfDataRam_WriteData (P2CONST(Dcm_DataDID_FDFF_MeasurementFrameConfDataRam_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FDFF_MeasurementFrameConfDataRam_WriteData (P2CONST(uint8, AUTOMATIC, RTE_APPL_DATA) Data, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FDFF_MeasurementFrameConfDataRam_ReadData (Dcm_OpStatusType OpStatus, P2VAR(Dcm_DataDID_FDFF_MeasurementFrameConfDataRam_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_FDFF_MeasurementFrameConfDataRam_ReadData (Dcm_OpStatusType OpStatus, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_F187_VWSparePartNumberData_WriteData (P2CONST(Dcm_DataDID_F187_VWSparePartNumberData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_F187_VWSparePartNumberData_WriteData (P2CONST(uint8, AUTOMATIC, RTE_APPL_DATA) Data, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_F187_VWSparePartNumberData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(Dcm_DataDID_F187_VWSparePartNumberData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_F187_VWSparePartNumberData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_F189_VWApplicationSoftwareVersionNumberData_WriteData (P2CONST(Dcm_DataDID_F189_VWApplicationSoftwareVersionNumberData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_F189_VWApplicationSoftwareVersionNumberData_WriteData (P2CONST(uint8, AUTOMATIC, RTE_APPL_DATA) Data, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_F189_VWApplicationSoftwareVersionNumberData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(Dcm_DataDID_F189_VWApplicationSoftwareVersionNumberData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_F189_VWApplicationSoftwareVersionNumberData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_F191_VWECUHardwareNumberData_WriteData (P2CONST(Dcm_DataDID_F191_VWECUHardwareNumberData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_F191_VWECUHardwareNumberData_WriteData (P2CONST(uint8, AUTOMATIC, RTE_APPL_DATA) Data, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_F191_VWECUHardwareNumberData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(Dcm_DataDID_F191_VWECUHardwareNumberData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_F191_VWECUHardwareNumberData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_F197_VWSystemNameOrEngineTypeData_WriteData (P2CONST(Dcm_DataDID_F197_VWSystemNameOrEngineTypeData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_F197_VWSystemNameOrEngineTypeData_WriteData (P2CONST(uint8, AUTOMATIC, RTE_APPL_DATA) Data, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_F197_VWSystemNameOrEngineTypeData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(Dcm_DataDID_F197_VWSystemNameOrEngineTypeData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_F197_VWSystemNameOrEngineTypeData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_F1B4_TechnicalSpecificationsVersionData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(Dcm_DataDID_F1B4_TechnicalSpecificationsVersionData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_F1B4_TechnicalSpecificationsVersionData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_0407_VWLogicalSoftwareBlockCounterOfProgrammingAttemptsData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(Dcm_DataDID_0407_VWLogicalSoftwareBlockCounterOfProgrammingAttemptsData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_0407_VWLogicalSoftwareBlockCounterOfProgrammingAttemptsData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_040F_VWLogicalSoftwareBlockLockValueData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(Dcm_DataDID_040F_VWLogicalSoftwareBlockLockValueData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_040F_VWLogicalSoftwareBlockLockValueData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_0410_BootloaderTPBlocksizeData_WriteData (P2CONST(Dcm_DataDID_0410_BootloaderTPBlocksizeData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_0410_BootloaderTPBlocksizeData_WriteData (P2CONST(uint8, AUTOMATIC, RTE_APPL_DATA) Data, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_0410_BootloaderTPBlocksizeData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(Dcm_DataDID_0410_BootloaderTPBlocksizeData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_0410_BootloaderTPBlocksizeData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_0448_ProgrammingPreconditionsData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(Dcm_DataDID_0448_ProgrammingPreconditionsData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_0448_ProgrammingPreconditionsData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_F1DF_ECUProgrammingInformationData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(Dcm_DataDID_F1DF_ECUProgrammingInformationData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_F1DF_ECUProgrammingInformationData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_F19E_ASAMODXFileIdentifierData_WriteData (P2CONST(Dcm_DataDID_F19E_ASAMODXFileIdentifierData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_F19E_ASAMODXFileIdentifierData_WriteData (P2CONST(uint8, AUTOMATIC, RTE_APPL_DATA) Data, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_F19E_ASAMODXFileIdentifierData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(Dcm_DataDID_F19E_ASAMODXFileIdentifierData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_F19E_ASAMODXFileIdentifierData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_F1A2_ASAMODXFileVersionData_WriteData (P2CONST(Dcm_DataDID_F1A2_ASAMODXFileVersionData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_F1A2_ASAMODXFileVersionData_WriteData (P2CONST(uint8, AUTOMATIC, RTE_APPL_DATA) Data, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_F1A2_ASAMODXFileVersionData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(Dcm_DataDID_F1A2_ASAMODXFileVersionData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_F1A2_ASAMODXFileVersionData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_F1D5_FDSProjectData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(Dcm_DataDID_F1D5_FDSProjectData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_F1D5_FDSProjectData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_F1A3_VWECUHardwareVersionNumberData_WriteData (P2CONST(Dcm_DataDID_F1A3_VWECUHardwareVersionNumberData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_F1A3_VWECUHardwareVersionNumberData_WriteData (P2CONST(uint8, AUTOMATIC, RTE_APPL_DATA) Data, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_F1A3_VWECUHardwareVersionNumberData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(Dcm_DataDID_F1A3_VWECUHardwareVersionNumberData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_F1A3_VWECUHardwareVersionNumberData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_F18C_ECUSerialNumberData_WriteData (P2CONST(Dcm_DataDID_F18C_ECUSerialNumberData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_F18C_ECUSerialNumberData_WriteData (P2CONST(uint8, AUTOMATIC, RTE_APPL_DATA) Data, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_F18C_ECUSerialNumberData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(Dcm_DataDID_F18C_ECUSerialNumberData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_F18C_ECUSerialNumberData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_F1AB_VWLogicalSoftwareBlockVersionData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(Dcm_DataDID_F1AB_VWLogicalSoftwareBlockVersionData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_F1AB_VWLogicalSoftwareBlockVersionData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_F15B_FingerprintAndProgrammingDateOfLogicalSoftwareBlocksData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(Dcm_DataDID_F15B_FingerprintAndProgrammingDateOfLogicalSoftwareBlocksData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_F15B_FingerprintAndProgrammingDateOfLogicalSoftwareBlocksData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_0236_ProgrammingDataElockEcuData_WriteData (P2CONST(Dcm_DataDID_0236_ProgrammingDataElockEcuData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_0236_ProgrammingDataElockEcuData_WriteData (P2CONST(uint8, AUTOMATIC, RTE_APPL_DATA) Data, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_0236_ProgrammingDataElockEcuData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(Dcm_DataDID_0236_ProgrammingDataElockEcuData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_0236_ProgrammingDataElockEcuData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_023E_WSCForProgrammingElockEcuData_WriteData (P2CONST(Dcm_DataDID_023E_WSCForProgrammingElockEcuData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_023E_WSCForProgrammingElockEcuData_WriteData (P2CONST(uint8, AUTOMATIC, RTE_APPL_DATA) Data, Dcm_OpStatusType OpStatus, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_023E_WSCForProgrammingElockEcuData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(Dcm_DataDID_023E_WSCForProgrammingElockEcuData_ArrayType, AUTOMATIC, RTE_APPL_DATA) Data);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_DataServices_DID_023E_WSCForProgrammingElockEcuData_ReadData (Dcm_OpStatusType OpStatus, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
#endif
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_ServiceRequestSupplierNotification_DcmDslServiceRequestSupplierNotification_Indication (uint8 SID, P2CONST(Dcm_RequestData_ArrayType, AUTOMATIC, RTE_APPL_DATA) RequestData, uint16 DataSize, uint8 ReqType, uint16 SourceAddress, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_ServiceRequestSupplierNotification_DcmDslServiceRequestSupplierNotification_Indication (uint8 SID, P2CONST(uint8, AUTOMATIC, RTE_APPL_DATA) RequestData, uint16 DataSize, uint8 ReqType, uint16 SourceAddress, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#endif
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_ServiceRequestSupplierNotification_DcmDslServiceRequestSupplierNotification_Confirmation (uint8 SID, uint8 ReqType, uint16 SourceAddress, Dcm_ConfirmationStatusType ConfirmationStatus);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_RoutineServices_DcmDspRoutineCtrl_Lock_UnlockECU_Start (Dcm_OpStatusType OpStatus, P2VAR(Dcm_StartDataOut_DcmDspRoutineCtrl_Lock_UnlockECU_DcmDspStartRoutineOutSignal_0Type, AUTOMATIC, RTE_APPL_DATA) dataOut0, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_RoutineServices_DcmDspRoutineCtrl_Lock_UnlockECU_Stop (Dcm_OpStatusType OpStatus, P2VAR(Dcm_StopDataOut_DcmDspRoutineCtrl_Lock_UnlockECU_DcmDspRoutineStopOutSignal_0Type, AUTOMATIC, RTE_APPL_DATA) dataOut0, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_RoutineServices_DcmDspRoutineCtrl_Lock_UnlockECU_RequestResults (Dcm_OpStatusType OpStatus, P2VAR(Dcm_RequestDataOut_DcmDspRoutineCtrl_Lock_UnlockECU_DcmDspRoutineRequestResOutSignalType, AUTOMATIC, RTE_APPL_DATA) dataOut0, P2VAR(Dcm_RequestDataOut_DcmDspRoutineCtrl_Lock_UnlockECU_DcmDspRoutineRequestResOutSignalInformationLockType, AUTOMATIC, RTE_APPL_DATA) dataOut1, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_RoutineServices_DcmDspRoutineProcessMode_Start (Dcm_OpStatusType OpStatus, P2VAR(Dcm_StartDataOut_DcmDspRoutineProcessMode_DcmDspStartRoutineOutSignal_RoutineInfoType, AUTOMATIC, RTE_APPL_DATA) dataOut0, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_RoutineServices_DcmDspRoutineProcessMode_Stop (Dcm_OpStatusType OpStatus, P2VAR(Dcm_StopDataOut_DcmDspRoutineProcessMode_DcmDspRoutineStopOutSignal_RoutineInfoType, AUTOMATIC, RTE_APPL_DATA) dataOut0, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_RoutineServices_DcmDspRoutineProcessMode_RequestResults (Dcm_OpStatusType OpStatus, P2VAR(Dcm_RequestDataOut_DcmDspRoutineProcessMode_DcmDspRoutineRequestResOutSignal_RoutineInfoType, AUTOMATIC, RTE_APPL_DATA) dataOut0, P2VAR(Dcm_RequestDataOut_DcmDspRoutineProcessMode_DcmDspRoutineRequestResOutSignal_PROCESSType, AUTOMATIC, RTE_APPL_DATA) dataOut1, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_RoutineServices_DcmDspRoutineAccCalib_Start (Dcm_OpStatusType OpStatus, P2VAR(Dcm_StartDataOut_DcmDspRoutineAccCalib_DcmDspStartRoutineOutSignal_RoutineInfoType, AUTOMATIC, RTE_APPL_DATA) dataOut0, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_RoutineServices_DcmDspRoutineLockSolenoid_Start (Dcm_OpStatusType OpStatus, P2VAR(Dcm_StartDataOut_DcmDspRoutineLockSolenoid_DcmDspStartRoutineOutSignal_0Type, AUTOMATIC, RTE_APPL_DATA) dataOut0, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_RoutineServices_DcmDspRoutineLockSolenoid_Stop (Dcm_OpStatusType OpStatus, P2VAR(Dcm_StopDataOut_DcmDspRoutineLockSolenoid_DcmDspStopRoutineOutSignal_RoutineInfoType, AUTOMATIC, RTE_APPL_DATA) dataOut0, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_RoutineServices_DcmDspRoutineEcuTempCalibration_Start (Dcm_StartDataIn_DcmDspRoutineEcuTempCalibration_DcmDspStartRoutineInSignal_0Type dataIn0, Dcm_OpStatusType OpStatus, P2VAR(Dcm_StartDataOut_DcmDspRoutineEcuTempCalibration_DcmDspStartRoutineOutSignal_0Type, AUTOMATIC, RTE_APPL_DATA) dataOut0, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_RoutineServices_DcmDspRoutineAccAngleOffsetCalibration_Start (Dcm_StartDataIn_DcmDspRoutineAccAngleOffsetCalibration_DcmDspStartRoutineInSignal_0Type dataIn0, Dcm_StartDataIn_DcmDspRoutineAccAngleOffsetCalibration_DcmDspStartRoutineInSignal_1Type dataIn1, Dcm_StartDataIn_DcmDspRoutineAccAngleOffsetCalibration_DcmDspStartRoutineInSignal_2Type dataIn2, Dcm_OpStatusType OpStatus, P2VAR(Dcm_StartDataOut_DcmDspRoutineAccAngleOffsetCalibration_DcmDspStartRoutineOutSignal_0Type, AUTOMATIC, RTE_APPL_DATA) dataOut0, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#ifdef RTE_PTR2ARRAYTYPE_PASSING
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_RoutineServices_DcmDspRoutineRoutineCheckProgrammingPreconditions_Start (Dcm_OpStatusType OpStatus, P2VAR(Dcm_StartFlexibleOutArrayData_DcmDspRoutineRoutineCheckProgrammingPreconditions_DcmDspStartRoutineOutSignal_0Type, AUTOMATIC, RTE_APPL_DATA) dataOut0, P2VAR(uint16, AUTOMATIC, RTE_APPL_DATA) currentDataLength, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#else
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_RoutineServices_DcmDspRoutineRoutineCheckProgrammingPreconditions_Start (Dcm_OpStatusType OpStatus, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) dataOut0, P2VAR(uint16, AUTOMATIC, RTE_APPL_DATA) currentDataLength, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
#endif
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_CallBackDCMRequestServices_CBReqServInd_1_StartProtocol (Dcm_ProtocolType ProtocolID);
extern FUNC(Std_ReturnType, RTE_CODE) Rte_Call_Dcm_CallBackDCMRequestServices_CBReqServInd_1_StopProtocol (Dcm_ProtocolType ProtocolID);
#endif

#define RTE_STOP_SEC_CODE
#include <Rte_MemMap.h>

/* ------------------[declaration of API functions provided by other Appl]---- */

#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif
/** @} doxygen end group definition  */
/* ==================[end of file]============================================ */
