# Write the path to the Enterptise Architect project
EA_project_path: 's:\Architectures\Application\Description\eCS_SW_Arhitecture.eapx'

# Write here the path to the output folder of the generated html files
Output_folder: 'C:\PyCharm_projects\EA_automate_publish_html\Output'

# Write here the Enterprise Architect model name
EA_models_to_publish:
    - all
#    - FuSa-SW Architecture Static View
#    - SW Architectural Design
#    - SW Architecture Dynamic View
#    - SW Architecture Memory Map
#    - SW Architecture Scheduling
#    - SW Architecture Static View
#    - SW Detailed Design