#ifndef SCHM_SPI_H
#define SCHM_SPI_H
/**
 * \file
 *
 * \brief AUTOSAR Rte
 *
 * This file contains the implementation of the AUTOSAR
 * module Rte.
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2018 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

/*
 * This file is the Module Interlink Header which contains the declarations relevant for that instance of a basic software module.
 *
 * This file has been automatically generated by
 * EB tresos AutoCore Rte Generator Version 6.2.21
 * on Wed Oct 10 17:03:09 CEST 2018. !!!IGNORE-LINE!!!
 */

/*
 * \addtogroup Rte Runtime Environment
 * @{
 */

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */
/* ==================[Includes]=============================================== */

/* ==================[Declaration of functions with external linkage]========= */

extern FUNC(void, RTE_CODE) SchM_Enter_Spi_SPI_EXCLUSIVE_AREA_01 (void);
extern FUNC(void, RTE_CODE) SchM_Exit_Spi_SPI_EXCLUSIVE_AREA_01 (void);
extern FUNC(void, RTE_CODE) SchM_Enter_Spi_SPI_EXCLUSIVE_AREA_02 (void);
extern FUNC(void, RTE_CODE) SchM_Exit_Spi_SPI_EXCLUSIVE_AREA_02 (void);
extern FUNC(void, RTE_CODE) SchM_Enter_Spi_SPI_EXCLUSIVE_AREA_03 (void);
extern FUNC(void, RTE_CODE) SchM_Exit_Spi_SPI_EXCLUSIVE_AREA_03 (void);
extern FUNC(void, RTE_CODE) SchM_Enter_Spi_SPI_EXCLUSIVE_AREA_04 (void);
extern FUNC(void, RTE_CODE) SchM_Exit_Spi_SPI_EXCLUSIVE_AREA_04 (void);
extern FUNC(void, RTE_CODE) SchM_Enter_Spi_SPI_EXCLUSIVE_AREA_05 (void);
extern FUNC(void, RTE_CODE) SchM_Exit_Spi_SPI_EXCLUSIVE_AREA_05 (void);
extern FUNC(void, RTE_CODE) SchM_Enter_Spi_SPI_EXCLUSIVE_AREA_06 (void);
extern FUNC(void, RTE_CODE) SchM_Exit_Spi_SPI_EXCLUSIVE_AREA_06 (void);
extern FUNC(void, RTE_CODE) SchM_Enter_Spi_SPI_EXCLUSIVE_AREA_07 (void);
extern FUNC(void, RTE_CODE) SchM_Exit_Spi_SPI_EXCLUSIVE_AREA_07 (void);
#ifndef RTE_SCHM_SWCBSW_SPI_MAINFUNCTION_HANDLING
#define RTE_SCHM_SWCBSW_SPI_MAINFUNCTION_HANDLING
extern FUNC(void, SPI_CODE) Spi_MainFunction_Handling (void);
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif
/** @} doxygen end group definition  */
/* ==================[end of file]============================================ */
