/*==================================================================================================
*   Project              : RTD AUTOSAR 4.4
*   Platform             : CORTEXM
*   Peripheral           : generic
*   Dependencies         : 
*
*   Autosar Version      : 4.4.0
*   Autosar Revision     : ASR_REL_4_4_REV_0000
*   Autosar Conf.Variant :
*   SW Version           : 1.0.1
*   Build Version        : S32K1_RTD_1_0_1_D2202_ASR_REL_4_4_REV_0000_20220224
*
*   (c) Copyright 2020-2022 NXP Semiconductors
*   All Rights Reserved.
*
*   NXP Confidential. This software is owned or controlled by NXP and may only be
*   used strictly in accordance with the applicable license terms. By expressly
*   accepting such terms or by downloading, installing, activating and/or otherwise
*   using the software, you are agreeing that you have read, and that you agree to
*   comply with and are bound by, such license terms. If you do not agree to be
*   bound by the applicable license terms, then you may not retain, install,
*   activate or otherwise use the software.
==================================================================================================*/

#ifndef OS_H
#define OS_H

/**
*   @file Os.h
*
*   @addtogroup [OS]
*   @{
*/


#ifdef __cplusplus
extern "C"
{
#endif


#include    "Os_version.h"    /**< OS version info */
#include    "Std_Types.h"     /**< Standard type header - from MCAL  */
#include    "Os_types_public.h"   /**< Autosar OS public types  */
#include    "Os_counter_api.h"
#include    "Os_multicore.h"

#include    "Os_cfg.h"    /* OS Configuration (generated by SysGen) */

#ifdef __cplusplus
}
#endif

/** @} */

#endif /* OS_H */

