# =========================================================================
#                     CONFIG FILE FOR EA Model Generator
#   Written by: Motoc Mihai
#   Date: 9 March 2023
#   Copyright Autoliv, RBE, 2023
#   Status:
# =========================================================================

#path where the project is located
sw_comp_folder: "C:\\workspace\\KPI_Manager\\eCS_Reports\\Components\\Application\\Autoliv"

#path where the report file are located
output_folder: "C:\\workspace\\KPI_Manager\\eCS_Reports\\Script_Outputs\\peer_review_and_warningReport_analysis"


sort_version: "natsorted"
# sort_version: "last_element_from_list"


#list of files that will be ignor
list_of_files_to_ignore:
#  - ACC.c

#folder that will be ignor
list_of_directories_to_ignore:
#  - ACC
  - Design
  - Static_Analysis
  - FFU
  - Config

#list of component that will be analisys
sw_components_list:
 - all
#  - ACC
#  - AdcIf
#  - ATM
#  - BswMIf
#  - CanTrcvIf
#  - CIL
#  - DcmIf
#  - DemIf
#  - DIA
#  - DioIf
#  - eCS
#  - EcuMIf
#  - EFX
#  - FlsIf
#  - FSM
#  - IoHwAb
#  - LPM
#  - MIC
#  - NmIf
#  - NvmIf
#  - NVP
#  - OsIf
#  - PlatformsIf
#  - PortIf
#  - PwmIf
#  - RCM
#  - RTE
#  - RteIf
#  - SAD
#  - SBC
#  - SpiIf
#  - Startup
#  - STM

