#path to project
project_path: "S:\\Components\\Application\\Autoliv\\"

#path to vera exe
vera_path: "S:\\Tools\\vera++\\Installation\\vera++\\bin\\vera++.exe"

#output path
output_path: "S:\\Script_Outputs\\VeraRunner"


list_of_directories_to_ignore:
# - all
# - ACC
# - AdcIf
# - ATM
# - BswMIf
# - CanTrcvIf
# - CIL
 - CompilerIf
# - DcmIf
# - DemIf
# - DIA
# - DioIf
# - eCS
# - EcuMIf
# - EFX
# - EIM
# - FlsIf
# - FSM
# - IoHwAb
# - LPM
# - MIC
# - McuIf
 - NmIf
# - NvmIf
 - NVP
# - OsIf
# - PlatformsIf
# - PortIf
# - PwmIf
# - RCM
# - RTE
# - RteIf
# - SAD
# - SBC
# - SpiIf
# - Startup
# - STM
 - TL_Lib