#if !defined(RTE_OSIF_HOOK_H)
#define RTE_OSIF_HOOK_H

/**
 * \file
 *
 * \brief AUTOSAR Rte
 *
 * This file contains the implementation of the AUTOSAR
 * module Rte.
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2018 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

 /*
  * This file contains Rte hook declarations for the software component type OsIf
  *
  * This file has been automatically generated by
  * EB tresos AutoCore Rte Generator Version 6.2.21
  */

 /* \addtogroup Rte Runtime Environment
  * @{ */

/*==================[inclusions]=============================================*/

#include <Rte_Cfg.h>         /* RTE VFB configuration header file */
#include <Rte_Type.h>     /* Rte type definitions header file */

/*==================[macros]=================================================*/

#if (!defined RTE_CORE) /* if included by software component */
#ifndef RTE_VFB_TRACE
#define RTE_VFB_TRACE (0)
#endif /* RTE_VFB_TRACE */
#endif
#if defined(Rte_CallHook_OsIf_pclRcmServices_ReportOsErrorStatus_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_CallHook_OsIf_pclRcmServices_ReportOsErrorStatus_Start
#endif
#if defined(Rte_CallHook_OsIf_pclRcmServices_ReportOsErrorStatus_Start)
#undef Rte_CallHook_OsIf_pclRcmServices_ReportOsErrorStatus_Start
extern FUNC(void, RTE_APPL_CODE) Rte_CallHook_OsIf_pclRcmServices_ReportOsErrorStatus_Start(u8OSTaskIDType u8TaskID, u8OSErrorType u8IDOSError);
#else
#define Rte_CallHook_OsIf_pclRcmServices_ReportOsErrorStatus_Start(u8TaskID, u8IDOSError) ((void)0)
#endif /* Rte_CallHook_OsIf_pclRcmServices_ReportOsErrorStatus_Start */
#if defined(Rte_CallHook_OsIf_pclRcmServices_ReportOsErrorStatus_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_CallHook_OsIf_pclRcmServices_ReportOsErrorStatus_Return
#endif
#if defined(Rte_CallHook_OsIf_pclRcmServices_ReportOsErrorStatus_Return)
#undef Rte_CallHook_OsIf_pclRcmServices_ReportOsErrorStatus_Return
extern FUNC(void, RTE_APPL_CODE) Rte_CallHook_OsIf_pclRcmServices_ReportOsErrorStatus_Return(u8OSTaskIDType u8TaskID, u8OSErrorType u8IDOSError);
#else
#define Rte_CallHook_OsIf_pclRcmServices_ReportOsErrorStatus_Return(u8TaskID, u8IDOSError) ((void)0)
#endif /* Rte_CallHook_OsIf_pclRcmServices_ReportOsErrorStatus_Return */
#if defined(Rte_CallHook_OsIf_pclResetCauseNotification_NotifyResetCause_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_CallHook_OsIf_pclResetCauseNotification_NotifyResetCause_Start
#endif
#if defined(Rte_CallHook_OsIf_pclResetCauseNotification_NotifyResetCause_Start)
#undef Rte_CallHook_OsIf_pclResetCauseNotification_NotifyResetCause_Start
extern FUNC(void, RTE_APPL_CODE) Rte_CallHook_OsIf_pclResetCauseNotification_NotifyResetCause_Start(u32ResetReasonNotificationType u32ResetCauseNotification);
#else
#define Rte_CallHook_OsIf_pclResetCauseNotification_NotifyResetCause_Start(u32ResetCauseNotification) ((void)0)
#endif /* Rte_CallHook_OsIf_pclResetCauseNotification_NotifyResetCause_Start */
#if defined(Rte_CallHook_OsIf_pclResetCauseNotification_NotifyResetCause_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_CallHook_OsIf_pclResetCauseNotification_NotifyResetCause_Return
#endif
#if defined(Rte_CallHook_OsIf_pclResetCauseNotification_NotifyResetCause_Return)
#undef Rte_CallHook_OsIf_pclResetCauseNotification_NotifyResetCause_Return
extern FUNC(void, RTE_APPL_CODE) Rte_CallHook_OsIf_pclResetCauseNotification_NotifyResetCause_Return(u32ResetReasonNotificationType u32ResetCauseNotification);
#else
#define Rte_CallHook_OsIf_pclResetCauseNotification_NotifyResetCause_Return(u32ResetCauseNotification) ((void)0)
#endif /* Rte_CallHook_OsIf_pclResetCauseNotification_NotifyResetCause_Return */
#if defined(Rte_TriggerHook_OsIf_ptrpAsrOsServicesOsIf_ErrorHook_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_TriggerHook_OsIf_ptrpAsrOsServicesOsIf_ErrorHook_Start
#endif
#if defined(Rte_TriggerHook_OsIf_ptrpAsrOsServicesOsIf_ErrorHook_Start)
#undef Rte_TriggerHook_OsIf_ptrpAsrOsServicesOsIf_ErrorHook_Start
extern FUNC(void, RTE_APPL_CODE) Rte_TriggerHook_OsIf_ptrpAsrOsServicesOsIf_ErrorHook_Start(void);
#else
#define Rte_TriggerHook_OsIf_ptrpAsrOsServicesOsIf_ErrorHook_Start() ((void)0)
#endif /* Rte_TriggerHook_OsIf_ptrpAsrOsServicesOsIf_ErrorHook_Start */
#if defined(Rte_TriggerHook_OsIf_ptrpAsrOsServicesOsIf_ErrorHook_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_TriggerHook_OsIf_ptrpAsrOsServicesOsIf_ErrorHook_Return
#endif
#if defined(Rte_TriggerHook_OsIf_ptrpAsrOsServicesOsIf_ErrorHook_Return)
#undef Rte_TriggerHook_OsIf_ptrpAsrOsServicesOsIf_ErrorHook_Return
extern FUNC(void, RTE_APPL_CODE) Rte_TriggerHook_OsIf_ptrpAsrOsServicesOsIf_ErrorHook_Return(void);
#else
#define Rte_TriggerHook_OsIf_ptrpAsrOsServicesOsIf_ErrorHook_Return() ((void)0)
#endif /* Rte_TriggerHook_OsIf_ptrpAsrOsServicesOsIf_ErrorHook_Return */
#if defined(Rte_TriggerHook_OsIf_ptrpAsrOsServicesOsIf_OsTask_Bsw_Init_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_TriggerHook_OsIf_ptrpAsrOsServicesOsIf_OsTask_Bsw_Init_Start
#endif
#if defined(Rte_TriggerHook_OsIf_ptrpAsrOsServicesOsIf_OsTask_Bsw_Init_Start)
#undef Rte_TriggerHook_OsIf_ptrpAsrOsServicesOsIf_OsTask_Bsw_Init_Start
extern FUNC(void, RTE_APPL_CODE) Rte_TriggerHook_OsIf_ptrpAsrOsServicesOsIf_OsTask_Bsw_Init_Start(void);
#else
#define Rte_TriggerHook_OsIf_ptrpAsrOsServicesOsIf_OsTask_Bsw_Init_Start() ((void)0)
#endif /* Rte_TriggerHook_OsIf_ptrpAsrOsServicesOsIf_OsTask_Bsw_Init_Start */
#if defined(Rte_TriggerHook_OsIf_ptrpAsrOsServicesOsIf_OsTask_Bsw_Init_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_TriggerHook_OsIf_ptrpAsrOsServicesOsIf_OsTask_Bsw_Init_Return
#endif
#if defined(Rte_TriggerHook_OsIf_ptrpAsrOsServicesOsIf_OsTask_Bsw_Init_Return)
#undef Rte_TriggerHook_OsIf_ptrpAsrOsServicesOsIf_OsTask_Bsw_Init_Return
extern FUNC(void, RTE_APPL_CODE) Rte_TriggerHook_OsIf_ptrpAsrOsServicesOsIf_OsTask_Bsw_Init_Return(void);
#else
#define Rte_TriggerHook_OsIf_ptrpAsrOsServicesOsIf_OsTask_Bsw_Init_Return() ((void)0)
#endif /* Rte_TriggerHook_OsIf_ptrpAsrOsServicesOsIf_OsTask_Bsw_Init_Return */
#if defined(Rte_TriggerHook_OsIf_ptrpAsrOsServicesOsIf_ProtectionHook_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_TriggerHook_OsIf_ptrpAsrOsServicesOsIf_ProtectionHook_Start
#endif
#if defined(Rte_TriggerHook_OsIf_ptrpAsrOsServicesOsIf_ProtectionHook_Start)
#undef Rte_TriggerHook_OsIf_ptrpAsrOsServicesOsIf_ProtectionHook_Start
extern FUNC(void, RTE_APPL_CODE) Rte_TriggerHook_OsIf_ptrpAsrOsServicesOsIf_ProtectionHook_Start(void);
#else
#define Rte_TriggerHook_OsIf_ptrpAsrOsServicesOsIf_ProtectionHook_Start() ((void)0)
#endif /* Rte_TriggerHook_OsIf_ptrpAsrOsServicesOsIf_ProtectionHook_Start */
#if defined(Rte_TriggerHook_OsIf_ptrpAsrOsServicesOsIf_ProtectionHook_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_TriggerHook_OsIf_ptrpAsrOsServicesOsIf_ProtectionHook_Return
#endif
#if defined(Rte_TriggerHook_OsIf_ptrpAsrOsServicesOsIf_ProtectionHook_Return)
#undef Rte_TriggerHook_OsIf_ptrpAsrOsServicesOsIf_ProtectionHook_Return
extern FUNC(void, RTE_APPL_CODE) Rte_TriggerHook_OsIf_ptrpAsrOsServicesOsIf_ProtectionHook_Return(void);
#else
#define Rte_TriggerHook_OsIf_ptrpAsrOsServicesOsIf_ProtectionHook_Return() ((void)0)
#endif /* Rte_TriggerHook_OsIf_ptrpAsrOsServicesOsIf_ProtectionHook_Return */
#if defined(Rte_Runnable_OsIf_ErrorHook_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_Runnable_OsIf_ErrorHook_Start
#endif
#if defined(Rte_Runnable_OsIf_ErrorHook_Start)
#undef Rte_Runnable_OsIf_ErrorHook_Start
extern FUNC(void, RTE_APPL_CODE) Rte_Runnable_OsIf_ErrorHook_Start(void);
#else
#define Rte_Runnable_OsIf_ErrorHook_Start() ((void)0)
#endif /* Rte_Runnable_OsIf_ErrorHook_Start */
#if defined(Rte_Runnable_OsIf_ErrorHook_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_Runnable_OsIf_ErrorHook_Return
#endif
#if defined(Rte_Runnable_OsIf_ErrorHook_Return)
#undef Rte_Runnable_OsIf_ErrorHook_Return
extern FUNC(void, RTE_APPL_CODE) Rte_Runnable_OsIf_ErrorHook_Return(void);
#else
#define Rte_Runnable_OsIf_ErrorHook_Return() ((void)0)
#endif /* Rte_Runnable_OsIf_ErrorHook_Return */
#if defined(Rte_Runnable_OsIf_OsTask_Bsw_Init_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_Runnable_OsIf_OsTask_Bsw_Init_Start
#endif
#if defined(Rte_Runnable_OsIf_OsTask_Bsw_Init_Start)
#undef Rte_Runnable_OsIf_OsTask_Bsw_Init_Start
extern FUNC(void, RTE_APPL_CODE) Rte_Runnable_OsIf_OsTask_Bsw_Init_Start(void);
#else
#define Rte_Runnable_OsIf_OsTask_Bsw_Init_Start() ((void)0)
#endif /* Rte_Runnable_OsIf_OsTask_Bsw_Init_Start */
#if defined(Rte_Runnable_OsIf_OsTask_Bsw_Init_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_Runnable_OsIf_OsTask_Bsw_Init_Return
#endif
#if defined(Rte_Runnable_OsIf_OsTask_Bsw_Init_Return)
#undef Rte_Runnable_OsIf_OsTask_Bsw_Init_Return
extern FUNC(void, RTE_APPL_CODE) Rte_Runnable_OsIf_OsTask_Bsw_Init_Return(void);
#else
#define Rte_Runnable_OsIf_OsTask_Bsw_Init_Return() ((void)0)
#endif /* Rte_Runnable_OsIf_OsTask_Bsw_Init_Return */
#if defined(Rte_Runnable_OsIf_ProtectionHook_Start) && (RTE_VFB_TRACE == FALSE)
#undef Rte_Runnable_OsIf_ProtectionHook_Start
#endif
#if defined(Rte_Runnable_OsIf_ProtectionHook_Start)
#undef Rte_Runnable_OsIf_ProtectionHook_Start
extern FUNC(void, RTE_APPL_CODE) Rte_Runnable_OsIf_ProtectionHook_Start(void);
#else
#define Rte_Runnable_OsIf_ProtectionHook_Start() ((void)0)
#endif /* Rte_Runnable_OsIf_ProtectionHook_Start */
#if defined(Rte_Runnable_OsIf_ProtectionHook_Return) && (RTE_VFB_TRACE == FALSE)
#undef Rte_Runnable_OsIf_ProtectionHook_Return
#endif
#if defined(Rte_Runnable_OsIf_ProtectionHook_Return)
#undef Rte_Runnable_OsIf_ProtectionHook_Return
extern FUNC(void, RTE_APPL_CODE) Rte_Runnable_OsIf_ProtectionHook_Return(void);
#else
#define Rte_Runnable_OsIf_ProtectionHook_Return() ((void)0)
#endif /* Rte_Runnable_OsIf_ProtectionHook_Return */

/*==================[type definitions]=======================================*/

/*==================[external function declarations]=========================*/

/*==================[internal function declarations]=========================*/

/*==================[external constants]=====================================*/

/*==================[internal constants]=====================================*/

/*==================[external data]==========================================*/

/*==================[internal data]==========================================*/

/*==================[external function definitions]==========================*/

/*==================[internal function definitions]==========================*/
/** @} doxygen end group definition */
#endif /* !defined(RTE_OSIF_HOOK_H) */
/*==================[end of file]============================================*/

