#if (!defined DEM_STUBCFG_H)
#define DEM_STUBCFG_H
/******************************************************************************

AUTOLIV ELECTRONIC document.

-------------------------------------------------------------------------------

Copyright Autoliv Inc. All rights reserved.

*******************************************************************************
H-File Template Version:
Template version: AEM_PROCESS_1.25.00
Last template change: AEM_PROCESS_1.00.00
Template release date: 2022-09
*******************************************************************************

Overview of the interfaces:
   This file contains the implementation of the AUTOSAR module Demo_DAG.

******************************************************************************/
/*
$Revision: 1.1 $
$ProjectName: e:/MKSProjects/SBE/eCS/AUDI_MCC/Phase_01/View_Development/Components/Bootloader_updater/Autoliv/AsrStubs/Implementation/inc/Dem_TS_TxDxM5I18R0_Stubs/project.pj $
*/
/*****************************************************************************/
/******************************************************************************
EXTERNAL DEPENDENCIES
******************************************************************************/
#ifdef __cplusplus
extern "C" {
#endif
/******************************************************************************
DEFINITION OF CONSTANTS
******************************************************************************/
/******************************************************************************
DECLARATION OF TYPES
******************************************************************************/
/******************************************************************************
DECLARATION OF VARIABLES
******************************************************************************/

/******************************************************************************
DECLARATION OF CONSTANT DATA
******************************************************************************/

/******************************************************************************
DECLARATION OF FUNCTIONS
******************************************************************************/
/******************************************************************************
DECLARATION OF FUNCTION-LIKE MACROS
******************************************************************************/

/*
   Configuration file for the Dem code stub
   The following symbols have the potential to change the behavior of the stub:
   ============================================================================

   - EBSTUBS_FUNCTION_TRACE_DEM
        Values: STD_ON (default)/STD_OFF
        En-/Disables function tracing feature module-wide if the more specific
        symbols for the single API functions are not defined.
        Also defines the default values for the following symbols if they are not set.
        If function tracing is disabled on global level this symbol has no effect.

   - EBSTUBS_FUNCTION_TRACE_DEM_[fctname]
        Values: STD_ON/STD_OFF Default: EBSTUBS_FUNCTION_TRACE_DEM
        En-/Disables function tracing feature for a single API function.
        If function tracing is disabled on global level this symbol has no effect.
        Defining a value overrules the behavior set by the module-wide symbol.
        In detail the symbols are:
      * EBSTUBS_FUNCTION_TRACE_DEM_GETVERSIONINFO
      * EBSTUBS_FUNCTION_TRACE_DEM_PREINIT
      * EBSTUBS_FUNCTION_TRACE_DEM_INIT
      * EBSTUBS_FUNCTION_TRACE_DEM_SHUTDOWN
      * EBSTUBS_FUNCTION_TRACE_DEM_REPORTERRORSTATUS
      * EBSTUBS_FUNCTION_TRACE_DEM_SETEVENTSTATUS
      * EBSTUBS_FUNCTION_TRACE_DEM_RESETEVENTSTATUS
      * EBSTUBS_FUNCTION_TRACE_DEM_PRESTOREFREEZEFRAME
      * EBSTUBS_FUNCTION_TRACE_DEM_CLEARPRESTOREDFREEZEFRAME
      * EBSTUBS_FUNCTION_TRACE_DEM_SETOPERATIONCYCLESTATE
      * EBSTUBS_FUNCTION_TRACE_DEM_SETOPERATIONCYCLECNTVALUE
      * EBSTUBS_FUNCTION_TRACE_DEM_SETAGINGCYCLESTATE
      * EBSTUBS_FUNCTION_TRACE_DEM_SETAGINGCYCLECOUNTERVALUE
      * EBSTUBS_FUNCTION_TRACE_DEM_GETEVENTSTATUS
      * EBSTUBS_FUNCTION_TRACE_DEM_GETEVENTFAILED
      * EBSTUBS_FUNCTION_TRACE_DEM_GETEVENTTESTED
      * EBSTUBS_FUNCTION_TRACE_DEM_GETDTCOFEVENT
      * EBSTUBS_FUNCTION_TRACE_DEM_SETENABLECONDITION
      * EBSTUBS_FUNCTION_TRACE_DEM_SETSTORAGECONDITION
      * EBSTUBS_FUNCTION_TRACE_DEM_GETFAULTDETECTIONCOUNTER
      * EBSTUBS_FUNCTION_TRACE_DEM_GETINDICATORSTATUS
      * EBSTUBS_FUNCTION_TRACE_DEM_GETEVENTFREEZEFRAMEDATA
      * EBSTUBS_FUNCTION_TRACE_DEM_GETEVENTEXTENDEDDATARECORD
      * EBSTUBS_FUNCTION_TRACE_DEM_GETEVENTMEMORYOVERFLOW
      * EBSTUBS_FUNCTION_TRACE_DEM_SETDTCSUPPRESSION
      * EBSTUBS_FUNCTION_TRACE_DEM_SETDTCFILTER
      * EBSTUBS_FUNCTION_TRACE_DEM_SETFREEZEFRAMERECORDFILTER
      * EBSTUBS_FUNCTION_TRACE_DEM_GETSTATUSOFDTC
      * EBSTUBS_FUNCTION_TRACE_DEM_GETDTCSTATUSAVAILABILITYMASK
      * EBSTUBS_FUNCTION_TRACE_DEM_GETNUMBEROFFILTEREDDTC
      * EBSTUBS_FUNCTION_TRACE_DEM_GETNEXTFILTEREDDTC
      * EBSTUBS_FUNCTION_TRACE_DEM_GETDTCBYOCCURRENCETIME
      * EBSTUBS_FUNCTION_TRACE_DEM_GETNEXTFILTEREDRECORD
      * EBSTUBS_FUNCTION_TRACE_DEM_GETNEXTFILTEREDDTCANDFDC
      * EBSTUBS_FUNCTION_TRACE_DEM_GETNEXTFILTEREDDTCANDSEVERITY
      * EBSTUBS_FUNCTION_TRACE_DEM_GETTRANSLATIONTYPE
      * EBSTUBS_FUNCTION_TRACE_DEM_GETSEVERITYOFDTC
      * EBSTUBS_FUNCTION_TRACE_DEM_GETFUNCTIONALUNITOFDTC
      * EBSTUBS_FUNCTION_TRACE_DEM_DISABLEDTCRECORDUPDATE
      * EBSTUBS_FUNCTION_TRACE_DEM_ENABLEDTCRECORDUPDATE
      * EBSTUBS_FUNCTION_TRACE_DEM_GETFREEZEFRAMEDATABYRECORD
      * EBSTUBS_FUNCTION_TRACE_DEM_GETFREEZEFRAMEDATABYDTC
      * EBSTUBS_FUNCTION_TRACE_DEM_GETSIZEOFFREEZEFRAMEBYDTC
      * EBSTUBS_FUNCTION_TRACE_DEM_GETEXTENDEDDATARECORDBYDTC
      * EBSTUBS_FUNCTION_TRACE_DEM_GETSIZEOFEXTENDEDDATARECORDBYDTC
      * EBSTUBS_FUNCTION_TRACE_DEM_CLEARDTC
      * EBSTUBS_FUNCTION_TRACE_DEM_DISABLEDTCSETTING
      * EBSTUBS_FUNCTION_TRACE_DEM_ENABLEDTCSETTING
      * EBSTUBS_FUNCTION_TRACE_DEM_DCMCANCELOPERATION
      * EBSTUBS_FUNCTION_TRACE_DEM_SETEVENTDISABLED
      * EBSTUBS_FUNCTION_TRACE_DEM_REPIUMPRFAULTDETECT
      * EBSTUBS_FUNCTION_TRACE_DEM_REPIUMPRDENLOCK
      * EBSTUBS_FUNCTION_TRACE_DEM_REPIUMPRDENRELEASE
      * EBSTUBS_FUNCTION_TRACE_DEM_GETINFOTYPEVALUE08
      * EBSTUBS_FUNCTION_TRACE_DEM_GETINFOTYPEVALUE0B
      * EBSTUBS_FUNCTION_TRACE_DEM_DCMREADDATAOFPID01
      * EBSTUBS_FUNCTION_TRACE_DEM_DCMREADDATAOFPID1C
      * EBSTUBS_FUNCTION_TRACE_DEM_DCMREADDATAOFPID21
      * EBSTUBS_FUNCTION_TRACE_DEM_DCMREADDATAOFPID30
      * EBSTUBS_FUNCTION_TRACE_DEM_DCMREADDATAOFPID31
      * EBSTUBS_FUNCTION_TRACE_DEM_DCMREADDATAOFPID41
      * EBSTUBS_FUNCTION_TRACE_DEM_DCMREADDATAOFPID4D
      * EBSTUBS_FUNCTION_TRACE_DEM_DCMREADDATAOFPID4E
      * EBSTUBS_FUNCTION_TRACE_DEM_READDATAOFOBDFREEZEFRAME
      * EBSTUBS_FUNCTION_TRACE_DEM_GETDTCOFOBDFREEZEFRAME
      * EBSTUBS_FUNCTION_TRACE_DEM_SETPTOSTATUS
      * EBSTUBS_FUNCTION_TRACE_DEM_MAINFUNCTION
      * EBSTUBS_FUNCTION_TRACE_DEM_DCMSETSTOREDDTCFILTER
      * EBSTUBS_FUNCTION_TRACE_DEM_DCMGETNEXTFILTEREDSTOREDDTC
      * EBSTUBS_FUNCTION_TRACE_DEM_DCMCONTROLDTCSTATUSCHANGEDNOTIFICATION

   Note: A function is only written to the function tracing buffer if:
         The global symbol EBSTUBS_FUNCTION_TRACE is enabled AND
         the symbol of the relevant function EBSTUBS_FUNCTION_TRACE_[fctname] is enabled.

     - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

   - EBSTUBS_FUNCENABLED_DEM
        Values: STD_ON (default)/STD_OFF
        En-/Disables all API functions of a single code stub at pre-compile time.
        Also defines the default values for the following symbols if they are not set.

   - EBSTUBS_FUNCENABLED_DEM_[fctname]
        Values: STD_ON/STD_OFF Default: EBSTUBS_FUNCENABLED_DEM
        En-/Disables a single API function at pre-compile time.
        Defining a value overrules the behavior set by the module-wide symbol.
        In detail the symbols are:
      * EBSTUBS_FUNCENABLED_DEM_GETVERSIONINFO
      * EBSTUBS_FUNCENABLED_DEM_PREINIT
      * EBSTUBS_FUNCENABLED_DEM_INIT
      * EBSTUBS_FUNCENABLED_DEM_SHUTDOWN
      * EBSTUBS_FUNCENABLED_DEM_REPORTERRORSTATUS
      * EBSTUBS_FUNCENABLED_DEM_SETEVENTSTATUS
      * EBSTUBS_FUNCENABLED_DEM_RESETEVENTSTATUS
      * EBSTUBS_FUNCENABLED_DEM_PRESTOREFREEZEFRAME
      * EBSTUBS_FUNCENABLED_DEM_CLEARPRESTOREDFREEZEFRAME
      * EBSTUBS_FUNCENABLED_DEM_SETOPERATIONCYCLESTATE
      * EBSTUBS_FUNCENABLED_DEM_SETOPERATIONCYCLECNTVALUE
      * EBSTUBS_FUNCENABLED_DEM_SETAGINGCYCLESTATE
      * EBSTUBS_FUNCENABLED_DEM_SETAGINGCYCLECOUNTERVALUE
      * EBSTUBS_FUNCENABLED_DEM_GETEVENTSTATUS
      * EBSTUBS_FUNCENABLED_DEM_GETEVENTFAILED
      * EBSTUBS_FUNCENABLED_DEM_GETEVENTTESTED
      * EBSTUBS_FUNCENABLED_DEM_GETDTCOFEVENT
      * EBSTUBS_FUNCENABLED_DEM_SETENABLECONDITION
      * EBSTUBS_FUNCENABLED_DEM_SETSTORAGECONDITION
      * EBSTUBS_FUNCENABLED_DEM_GETFAULTDETECTIONCOUNTER
      * EBSTUBS_FUNCENABLED_DEM_GETINDICATORSTATUS
      * EBSTUBS_FUNCENABLED_DEM_GETEVENTFREEZEFRAMEDATA
      * EBSTUBS_FUNCENABLED_DEM_GETEVENTEXTENDEDDATARECORD
      * EBSTUBS_FUNCENABLED_DEM_GETEVENTMEMORYOVERFLOW
      * EBSTUBS_FUNCENABLED_DEM_SETDTCSUPPRESSION
      * EBSTUBS_FUNCENABLED_DEM_SETDTCFILTER
      * EBSTUBS_FUNCENABLED_DEM_SETFREEZEFRAMERECORDFILTER
      * EBSTUBS_FUNCENABLED_DEM_GETSTATUSOFDTC
      * EBSTUBS_FUNCENABLED_DEM_GETDTCSTATUSAVAILABILITYMASK
      * EBSTUBS_FUNCENABLED_DEM_GETNUMBEROFFILTEREDDTC
      * EBSTUBS_FUNCENABLED_DEM_GETNEXTFILTEREDDTC
      * EBSTUBS_FUNCENABLED_DEM_GETDTCBYOCCURRENCETIME
      * EBSTUBS_FUNCENABLED_DEM_GETNEXTFILTEREDRECORD
      * EBSTUBS_FUNCENABLED_DEM_GETNEXTFILTEREDDTCANDFDC
      * EBSTUBS_FUNCENABLED_DEM_GETNEXTFILTEREDDTCANDSEVERITY
      * EBSTUBS_FUNCENABLED_DEM_GETTRANSLATIONTYPE
      * EBSTUBS_FUNCENABLED_DEM_GETSEVERITYOFDTC
      * EBSTUBS_FUNCENABLED_DEM_GETFUNCTIONALUNITOFDTC
      * EBSTUBS_FUNCENABLED_DEM_DISABLEDTCRECORDUPDATE
      * EBSTUBS_FUNCENABLED_DEM_ENABLEDTCRECORDUPDATE
      * EBSTUBS_FUNCENABLED_DEM_GETFREEZEFRAMEDATABYRECORD
      * EBSTUBS_FUNCENABLED_DEM_GETFREEZEFRAMEDATABYDTC
      * EBSTUBS_FUNCENABLED_DEM_GETSIZEOFFREEZEFRAMEBYDTC
      * EBSTUBS_FUNCENABLED_DEM_GETEXTENDEDDATARECORDBYDTC
      * EBSTUBS_FUNCENABLED_DEM_GETSIZEOFEXTENDEDDATARECORDBYDTC
      * EBSTUBS_FUNCENABLED_DEM_CLEARDTC
      * EBSTUBS_FUNCENABLED_DEM_DISABLEDTCSETTING
      * EBSTUBS_FUNCENABLED_DEM_ENABLEDTCSETTING
      * EBSTUBS_FUNCENABLED_DEM_DCMCANCELOPERATION
      * EBSTUBS_FUNCENABLED_DEM_SETEVENTDISABLED
      * EBSTUBS_FUNCENABLED_DEM_REPIUMPRFAULTDETECT
      * EBSTUBS_FUNCENABLED_DEM_REPIUMPRDENLOCK
      * EBSTUBS_FUNCENABLED_DEM_REPIUMPRDENRELEASE
      * EBSTUBS_FUNCENABLED_DEM_GETINFOTYPEVALUE08
      * EBSTUBS_FUNCENABLED_DEM_GETINFOTYPEVALUE0B
      * EBSTUBS_FUNCENABLED_DEM_DCMREADDATAOFPID01
      * EBSTUBS_FUNCENABLED_DEM_DCMREADDATAOFPID1C
      * EBSTUBS_FUNCENABLED_DEM_DCMREADDATAOFPID21
      * EBSTUBS_FUNCENABLED_DEM_DCMREADDATAOFPID30
      * EBSTUBS_FUNCENABLED_DEM_DCMREADDATAOFPID31
      * EBSTUBS_FUNCENABLED_DEM_DCMREADDATAOFPID41
      * EBSTUBS_FUNCENABLED_DEM_DCMREADDATAOFPID4D
      * EBSTUBS_FUNCENABLED_DEM_DCMREADDATAOFPID4E
      * EBSTUBS_FUNCENABLED_DEM_READDATAOFOBDFREEZEFRAME
      * EBSTUBS_FUNCENABLED_DEM_GETDTCOFOBDFREEZEFRAME
      * EBSTUBS_FUNCENABLED_DEM_SETPTOSTATUS
      * EBSTUBS_FUNCENABLED_DEM_MAINFUNCTION
      * EBSTUBS_FUNCENABLED_DEM_DCMSETSTOREDDTCFILTER
      * EBSTUBS_FUNCENABLED_DEM_DCMGETNEXTFILTEREDSTOREDDTC
      * EBSTUBS_FUNCENABLED_DEM_DCMCONTROLDTCSTATUSCHANGEDNOTIFICATION

     - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

   - EBSTUBS_MAX_CALLS_DEM
        Values: [numeric value] Default: 1
        Defines the number of API calls for which the code stubs can store the function arguments.
        Also defines the default values for the following symbols if they are not set.

   - EBSTUBS_MAX_CALLS_DEM_[fctname]
        Values: [numeric value] Default: EBSTUBS_MAX_CALLS_DEM
        Defines the number of API calls for which a specific function can.
        store the function arguments.
        Defining a value overrules the behavior set by the module-wide symbol.
        In detail the symbols are:
      * EBSTUBS_MAX_CALLS_DEM_GETVERSIONINFO
      * EBSTUBS_MAX_CALLS_DEM_PREINIT
      * EBSTUBS_MAX_CALLS_DEM_INIT
      * EBSTUBS_MAX_CALLS_DEM_SHUTDOWN
      * EBSTUBS_MAX_CALLS_DEM_REPORTERRORSTATUS
      * EBSTUBS_MAX_CALLS_DEM_SETEVENTSTATUS
      * EBSTUBS_MAX_CALLS_DEM_RESETEVENTSTATUS
      * EBSTUBS_MAX_CALLS_DEM_PRESTOREFREEZEFRAME
      * EBSTUBS_MAX_CALLS_DEM_CLEARPRESTOREDFREEZEFRAME
      * EBSTUBS_MAX_CALLS_DEM_SETOPERATIONCYCLESTATE
      * EBSTUBS_MAX_CALLS_DEM_SETOPERATIONCYCLECNTVALUE
      * EBSTUBS_MAX_CALLS_DEM_SETAGINGCYCLESTATE
      * EBSTUBS_MAX_CALLS_DEM_SETAGINGCYCLECOUNTERVALUE
      * EBSTUBS_MAX_CALLS_DEM_GETEVENTSTATUS
      * EBSTUBS_MAX_CALLS_DEM_GETEVENTFAILED
      * EBSTUBS_MAX_CALLS_DEM_GETEVENTTESTED
      * EBSTUBS_MAX_CALLS_DEM_GETDTCOFEVENT
      * EBSTUBS_MAX_CALLS_DEM_SETENABLECONDITION
      * EBSTUBS_MAX_CALLS_DEM_SETSTORAGECONDITION
      * EBSTUBS_MAX_CALLS_DEM_GETFAULTDETECTIONCOUNTER
      * EBSTUBS_MAX_CALLS_DEM_GETINDICATORSTATUS
      * EBSTUBS_MAX_CALLS_DEM_GETEVENTFREEZEFRAMEDATA
      * EBSTUBS_MAX_CALLS_DEM_GETEVENTEXTENDEDDATARECORD
      * EBSTUBS_MAX_CALLS_DEM_GETEVENTMEMORYOVERFLOW
      * EBSTUBS_MAX_CALLS_DEM_SETDTCSUPPRESSION
      * EBSTUBS_MAX_CALLS_DEM_SETDTCFILTER
      * EBSTUBS_MAX_CALLS_DEM_SETFREEZEFRAMERECORDFILTER
      * EBSTUBS_MAX_CALLS_DEM_GETSTATUSOFDTC
      * EBSTUBS_MAX_CALLS_DEM_GETDTCSTATUSAVAILABILITYMASK
      * EBSTUBS_MAX_CALLS_DEM_GETNUMBEROFFILTEREDDTC
      * EBSTUBS_MAX_CALLS_DEM_GETNEXTFILTEREDDTC
      * EBSTUBS_MAX_CALLS_DEM_GETDTCBYOCCURRENCETIME
      * EBSTUBS_MAX_CALLS_DEM_GETNEXTFILTEREDRECORD
      * EBSTUBS_MAX_CALLS_DEM_GETNEXTFILTEREDDTCANDFDC
      * EBSTUBS_MAX_CALLS_DEM_GETNEXTFILTEREDDTCANDSEVERITY
      * EBSTUBS_MAX_CALLS_DEM_GETTRANSLATIONTYPE
      * EBSTUBS_MAX_CALLS_DEM_GETSEVERITYOFDTC
      * EBSTUBS_MAX_CALLS_DEM_GETFUNCTIONALUNITOFDTC
      * EBSTUBS_MAX_CALLS_DEM_DISABLEDTCRECORDUPDATE
      * EBSTUBS_MAX_CALLS_DEM_ENABLEDTCRECORDUPDATE
      * EBSTUBS_MAX_CALLS_DEM_GETFREEZEFRAMEDATABYRECORD
      * EBSTUBS_MAX_CALLS_DEM_GETFREEZEFRAMEDATABYDTC
      * EBSTUBS_MAX_CALLS_DEM_GETSIZEOFFREEZEFRAMEBYDTC
      * EBSTUBS_MAX_CALLS_DEM_GETEXTENDEDDATARECORDBYDTC
      * EBSTUBS_MAX_CALLS_DEM_GETSIZEOFEXTENDEDDATARECORDBYDTC
      * EBSTUBS_MAX_CALLS_DEM_CLEARDTC
      * EBSTUBS_MAX_CALLS_DEM_DISABLEDTCSETTING
      * EBSTUBS_MAX_CALLS_DEM_ENABLEDTCSETTING
      * EBSTUBS_MAX_CALLS_DEM_DCMCANCELOPERATION
      * EBSTUBS_MAX_CALLS_DEM_SETEVENTDISABLED
      * EBSTUBS_MAX_CALLS_DEM_REPIUMPRFAULTDETECT
      * EBSTUBS_MAX_CALLS_DEM_REPIUMPRDENLOCK
      * EBSTUBS_MAX_CALLS_DEM_REPIUMPRDENRELEASE
      * EBSTUBS_MAX_CALLS_DEM_GETINFOTYPEVALUE08
      * EBSTUBS_MAX_CALLS_DEM_GETINFOTYPEVALUE0B
      * EBSTUBS_MAX_CALLS_DEM_DCMREADDATAOFPID01
      * EBSTUBS_MAX_CALLS_DEM_DCMREADDATAOFPID1C
      * EBSTUBS_MAX_CALLS_DEM_DCMREADDATAOFPID21
      * EBSTUBS_MAX_CALLS_DEM_DCMREADDATAOFPID30
      * EBSTUBS_MAX_CALLS_DEM_DCMREADDATAOFPID31
      * EBSTUBS_MAX_CALLS_DEM_DCMREADDATAOFPID41
      * EBSTUBS_MAX_CALLS_DEM_DCMREADDATAOFPID4D
      * EBSTUBS_MAX_CALLS_DEM_DCMREADDATAOFPID4E
      * EBSTUBS_MAX_CALLS_DEM_READDATAOFOBDFREEZEFRAME
      * EBSTUBS_MAX_CALLS_DEM_GETDTCOFOBDFREEZEFRAME
      * EBSTUBS_MAX_CALLS_DEM_SETPTOSTATUS
      * EBSTUBS_MAX_CALLS_DEM_MAINFUNCTION
      * EBSTUBS_MAX_CALLS_DEM_DCMSETSTOREDDTCFILTER
      * EBSTUBS_MAX_CALLS_DEM_DCMGETNEXTFILTEREDSTOREDDTC
      * EBSTUBS_MAX_CALLS_DEM_DCMCONTROLDTCSTATUSCHANGEDNOTIFICATION
*/
#ifdef __cplusplus
}
#endif
/******************************************************************************
End Of File
*****************************************************************************/

#endif /* !defined DEM_STUBCFG_H */
