%Read external pulse data
[pulsetime_USNCAP, pulse_USNCAP]   = textread('Pulse/USNCAP_PQ37_OLC32_25.txt',     '%f %f');
[pulsetime_FF27, pulse_FF27]       = textread('Pulse/FF27_PQ37_OLC14_25.txt',       '%f %f');
[pulsetime_ODB40, pulse_ODB40]     = textread('Pulse/ODB40_PQ37_OLC13_86.txt',      '%f %f');
[pulsetime_ODB64, pulse_ODB64]     = textread('Pulse/ODB64_PQ37_OLC24_92.txt',      '%f %f');
[pulsetime_MPDB, pulse_MPDB]       = textread('Pulse/MPDB_Pulse10_OLC24_77.txt',    '%f %f');
[pulsetime_ECE_X, pulse_ECE_X]     = textread('Pulse/ECE_Low_45_Failed_X.txt',      '%f %f');
[pulsetime_ECE_Y, pulse_ECE_Y]     = textread('Pulse/ECE_Low_45_Failed_Y.txt',      '%f %f');

% Heiko_AX_time = xlsread('eCS_ECE_stufentest_90_NewParam.xlsx','Data1', 'G1:G800000');
% Heiko_AX      = xlsread('eCS_ECE_stufentest_90_NewParam.xlsx','Data1', 'H1:H800000');
% Heiko_AY_time = xlsread('eCS_ECE_stufentest_90_NewParam.xlsx','Data1', 'I1:I800000');
% Heiko_AY      = xlsread('eCS_ECE_stufentest_90_NewParam.xlsx','Data1', 'J1:J800000');
% Heiko_AX_time = xlsread('ECE_Low_45_full.xlsx','Data1', 'G1:G500000');
% Heiko_AX      = xlsread('ECE_Low_45_full.xlsx','Data1', 'H1:H500000');
% Heiko_AY_time = xlsread('ECE_Low_45_full.xlsx','Data1', 'I1:I500000');
% Heiko_AY      = xlsread('ECE_Low_45_full.xlsx','Data1', 'J1:J500000');

%Bumpy road Meldorf Hindenburgstrasse, recorded with Phybox on Samsung Galaxy S8
load Pulse\Meldorf_Hindenburgstrasse_vom_Bahnhof_aus.mat
%Data generated by script "makevibetrainforANG.m" by Christopher Morgan,sent by mail from Chris dd. 20.01.20
load Pulse\20200131_GMW_road_Christopher_Morgan_script.mat
%Data from Chris dd. 20.01.20: VW416 (Atlas) recording, prefiltered 4th
%order Bessel 500Hz, then downsampled 2kHz
load Pulse\VW416.mat

%BMW data:
load Pulse\BMW_KSF50.mat
load Pulse\BMW_KSG30.mat
load Pulse\BMW_Rauasphalt60.mat
%%

% Load Solenoid data
load Solenoid\fp_Locked.mat
load Solenoid\fp_UnLocked.mat
load Solenoid\fullPower.mat

% ECE_45 = csvread('Pulse/2020-09-16_ECE_25gs_0,45g_45deg_01.csv');
% ECE_45_time = ECE_45(1:23158,4);
% ECE_45_ay = ECE_45(1:23158,2);
% ECE_45_ax = ECE_45(1:23158,1);

% Load ANG second batch of test data
% load Pulse\ECE_Low_v02.mat
% load Pulse\FMVSS_45_v02.mat

AccSensor=5;		% 0: no acceleration sensor (for recorded acc. signals that already contain noise i.e."bumpy road")
% 1:AD, 2:ST, 3:TDK, 4:NXP   -->priority have 2:ST and 3:TDK (decided in eCS-Meeting)

%Start acceleration sensor script
if AccSensor==0     %set an acc. sensor type in the script from FCE, even if there will be no sensor simulated
    Select=2;		%-->priority have 2:ST (faster) and 3:TDK
else
    Select=AccSensor;
end

% set model sample frequency depending on acceleration sensor (40kHz is default, 80kHz for AD-sensor)
if AccSensor~=1
    fs=40000;
else
    fs=80000;
end

Acc_Init_SelV1

pulsetype = 2 ;
phi_pulse_rotation=0 ;   %rotation of input pulse in °
offsetcorrection_on_off = 0 ;	%0=off , 1=on
AlgoType=0 ;    %0=ball algo (standard) , 1=filtered and threshold
TargetlinkAlgo = 0; % 0 = g algo, 1 = m.s² algo
AccelResolution = 4; % 1 = TDK [-2,2]g , 2 = TDK [-4,4]g, 3 = FS [-2,2]g, 4 = FS [-4,4]g
rotation = 0;
SubPulseType = 1;
simtime = 0.7;
Forced_Oscillation = 0;
sensitivity_optimisation = 0; % 1 = On, 0 = Off

% Load bus parameter
load BusStepsCreator.mat

disp('Opening model');
open_system('eCS_Algo_Simulation_2015b_opti.slx');
