IF "%TARGET%"=="" SET TARGET=CORTEXM
IF "%DERIVATE%"=="" SET DERIVATE=S32K14X
IF "%TOOLCHAIN%"=="" SET TOOLCHAIN=iar
IF [%TOOLPATH_COMPILER%]==[] SET TOOLPATH_COMPILER=
IF [%TRESOS_BASE%]==[] SET TRESOS_BASE=D:\Projects\Autoliv_VWAG_BL-3_ACG-8_7_1_CAN_S32K14_update\Tresos
IF [%PLUGINS_BASE%]==[] set PLUGINS_BASE=%TRESOS_BASE%\plugins

SET WORK_BASE=D:\Projects\Autoliv_VWAG_BL-3_ACG-8_7_1_CAN_S32K14_update
SET TEST_BASE=D:\Projects\Autoliv_VWAG_BL-3_ACG-8_7_1_CAN_S32K14_update\test_base
SET MISRA_MODULE=Demo_VAG
SET MODULE_NAME=Demo_VAG
SET INTERNAL_MODULE_NAME=osc_Demo_VAG
SET MODULE_VARIANT=TS_TxDxM1I0R0
SET MODULE_ID=8.7.1-S32K14X
SET Path=D:\EBA_WorkSpace\cygwin\bin;%Path%
SET AC_CYGWIN_DOS=D:\EBA_WorkSpace\cygwin