/* CORTEXM-user-calltrustedfunction.s
 *
 * This file contains the system function OS_UserCallTrustedFunction()
 * Generated by the makesc.pl script
 *
 * (c) Elektrobit Automotive GmbH
*/
#ifndef OS_ASM
#define OS_ASM
#endif

#include <CORTEXM/Os_asm_CORTEXM.h>

#if (OS_KERNEL_TYPE == OS_SYSTEM_CALL)

#include <Os_tool.h>
#include <Os_syscalls.h>

	OS_ASM_SECTION_TEXT
	OS_ASM_CODE_THUMB
	OS_global OS_UserCallTrustedFunction
	OS_align(4, 2)

	OS_ASM_FUNC(OS_UserCallTrustedFunction)
OS_ASM_LABEL(OS_UserCallTrustedFunction)

	mov		r12, #OS_SC_CallTrustedFunction
	svc		#0			/* make system call */
	bx		lr			/* return */
	OS_ASM_END_FUNC(OS_UserCallTrustedFunction)

	OS_ASM_SRC_END

#endif /* (OS_KERNEL_TYPE == OS_SYSTEM_CALL) */

