
#ifndef NVP_ALIAS_H_
#define NVP_ALIAS_H_ 1

/******************************************************************************

AUTOLIV ELECTRONIC document.

-------------------------------------------------------------------------------

Copyright Autoliv Inc. All rights reserved.

*******************************************************************************
H-File Template Version:
*******************************************************************************

Overview of the interfaces:
   This file Nvp_alias.h is generated by the generate_NVPaliash.py
   when using the eclipse plugin or directly the script

Date and time of generation of files: 19/07/2023 / 11:21:51

******************************************************************************/
/* PRQA S 0288 ++ */
/*
 * Explanation:
 *    Disabled for MKS keywords
 */
/*
$Revision: 1.15.2.45 $
$ProjectName: e:/MKSProjects/SBE/eCS/AUDI_MCC/Phase_01/View_Development/Components/Application/Autoliv/NVP/Implementation/inc/project.pj $
*/
/* PRQA S 0288 -- */
/*****************************************************************************/
/******************************************************************************
EXTERNAL DEPENDENCIES
******************************************************************************/
#include "Nvp_MemoryMapping.h"

#ifdef __cplusplus
extern "C" {
#endif
/******************************************************************************
DEFINITION OF CONSTANTS
******************************************************************************/

#define	BlockAddress_RAM_ECCCounters									__RAM_SHADOW__(0x000)
#define	BlockAddress_ROM_ECCCounters									__ROM_DEFAULT__(0x000)

#define	BlockAddress_RAM_WarmReset										__RAM_SHADOW__(0x010)
#define	BlockAddress_ROM_WarmReset										__ROM_DEFAULT__(0x010)

#define	BlockAddress_RAM_SOLENOID_UNLOCK_CONF_PARAM					__RAM_SHADOW__(0x018)
#define	BlockAddress_ROM_SOLENOID_UNLOCK_CONF_PARAM					__ROM_DEFAULT__(0x018)

#define	BlockAddress_RAM_ATMEnableParam								__RAM_SHADOW__(0x024)
#define	BlockAddress_ROM_ATMEnableParam								__ROM_DEFAULT__(0x024)

#define	BlockAddress_RAM_LOCK_UNLOCK_ECU_ParamSpecific					__RAM_SHADOW__(0x044)
#define	BlockAddress_ROM_LOCK_UNLOCK_ECU_ParamSpecific					__ROM_DEFAULT__(0x044)

#define	BlockAddress_RAM_MeasFrameCfg									__RAM_SHADOW__(0x048)
#define	BlockAddress_ROM_MeasFrameCfg									__ROM_DEFAULT__(0x048)

#define	BlockAddress_RAM_HW_PART_NUMBER								__RAM_SHADOW__(0x050)
#define	BlockAddress_ROM_HW_PART_NUMBER								__ROM_DEFAULT__(0x050)

#define	BlockAddress_RAM_AEE_TRACEABILITY_NUMBER						__RAM_SHADOW__(0x05C)
#define	BlockAddress_ROM_AEE_TRACEABILITY_NUMBER						__ROM_DEFAULT__(0x05C)

#define	BlockAddress_RAM_ECU_ASSEMBLY_SERIAL_NUMBER					__RAM_SHADOW__(0x068)
#define	BlockAddress_ROM_ECU_ASSEMBLY_SERIAL_NUMBER					__ROM_DEFAULT__(0x068)

#define	BlockAddress_RAM_ProcessMode									__RAM_SHADOW__(0x080)
#define	BlockAddress_ROM_ProcessMode									__ROM_DEFAULT__(0x080)

#define	BlockAddress_RAM_ECS_VARIANT									__RAM_SHADOW__(0x084)
#define	BlockAddress_ROM_ECS_VARIANT									__ROM_DEFAULT__(0x084)

#define	BlockAddress_RAM_RESERVED_1									__RAM_SHADOW__(0x088)
#define	BlockAddress_ROM_RESERVED_1									__ROM_DEFAULT__(0x088)

#define	BlockAddress_RAM_ECS_ACC_OFFSETS								__RAM_SHADOW__(0x0B8)
#define	BlockAddress_ROM_ECS_ACC_OFFSETS								__ROM_DEFAULT__(0x0B8)

#define	BlockAddress_RAM_ECS_BUCKLE_CONFIG								__RAM_SHADOW__(0x0C0)
#define	BlockAddress_ROM_ECS_BUCKLE_CONFIG								__ROM_DEFAULT__(0x0C0)

#define	BlockAddress_RAM_ECS_CODING_VARIANT							__RAM_SHADOW__(0x0C4)
#define	BlockAddress_ROM_ECS_CODING_VARIANT							__ROM_DEFAULT__(0x0C4)

#define	BlockAddress_RAM_ECS_ACC_LOWPASS								__RAM_SHADOW__(0x0CC)
#define	BlockAddress_ROM_ECS_ACC_LOWPASS								__ROM_DEFAULT__(0x0CC)

#define	BlockAddress_RAM_SBS_LAST_STATE								__RAM_SHADOW__(0x0D0)
#define	BlockAddress_ROM_SBS_LAST_STATE								__ROM_DEFAULT__(0x0D0)

#define	BlockAddress_RAM_ECS_ALGO_OUTPUT_DELAY							__RAM_SHADOW__(0x0D4)
#define	BlockAddress_ROM_ECS_ALGO_OUTPUT_DELAY							__ROM_DEFAULT__(0x0D4)

#define	BlockAddress_RAM_ECS_SENSITIVITY_LUT							__RAM_SHADOW__(0x0D8)
#define	BlockAddress_ROM_ECS_SENSITIVITY_LUT							__ROM_DEFAULT__(0x0D8)

#define	BlockAddress_RAM_ECS_SENSITIVITY_OPT							__RAM_SHADOW__(0x0EC)
#define	BlockAddress_ROM_ECS_SENSITIVITY_OPT							__ROM_DEFAULT__(0x0EC)

#define	BlockAddress_RAM_ECU_TEMP_CALIBRATION							__RAM_SHADOW__(0x0F0)
#define	BlockAddress_ROM_ECU_TEMP_CALIBRATION							__ROM_DEFAULT__(0x0F0)

#define	BlockAddress_RAM_ALV_NVM_VERSION								__RAM_SHADOW__(0x0F4)
#define	BlockAddress_ROM_ALV_NVM_VERSION								__ROM_DEFAULT__(0x0F4)

#define	BlockAddress_RAM_MEAS_FRAME_RAM_ADDR_CFG						__RAM_SHADOW__(0x0F8)
#define	BlockAddress_ROM_MEAS_FRAME_RAM_ADDR_CFG						__ROM_DEFAULT__(0x0F8)

#define	BlockAddress__RAM_ACC_AXIS_ANGLE_CALIBRATION					__RAM_SHADOW__(0x144)
#define	BlockAddress_ROM_ACC_AXIS_ANGLE_CALIBRATION					__ROM_DEFAULT__(0x144)

#define	BlockAddress__RAM_EOL_COUNTERS									__RAM_SHADOW__(0x14C)
#define	BlockAddress_ROM_EOL_COUNTERS									__ROM_DEFAULT__(0x14C)

#define	BlockAddress_RAM_RESERVED_4									__RAM_SHADOW__(0x194)
#define	BlockAddress_ROM_RESERVED_4									__ROM_DEFAULT__(0x194)

#define	BlockAddress_RAM_AutotestParam									__RAM_SHADOW__(0x1B8)
#define	BlockAddress_ROM_AutotestParam									__ROM_DEFAULT__(0x1B8)

#define	BlockAddress_RAM_PhysMeasurements								__RAM_SHADOW__(0x1D4)
#define	BlockAddress_ROM_PhysMeasurements								__ROM_DEFAULT__(0x1D4)

#define	BlockAddress_RAM_SolenoidParam									__RAM_SHADOW__(0x1DC)
#define	BlockAddress_ROM_SolenoidParam									__ROM_DEFAULT__(0x1DC)

#define	BlockAddress_RAM_ECS_PROFILES									__RAM_SHADOW__(0x1E8)
#define	BlockAddress_ROM_ECS_PROFILES									__ROM_DEFAULT__(0x1E8)

#define	BlockAddress_RAM_ECU_STATE_TIMING_PARAMETERS					__RAM_SHADOW__(0x218)
#define	BlockAddress_ROM_ECU_STATE_TIMING_PARAMETERS					__ROM_DEFAULT__(0x218)

#define	BlockAddress_RAM_SparePartNumber								__RAM_SHADOW__(0x274)
#define	BlockAddress_ROM_SparePartNumber								__ROM_DEFAULT__(0x274)

#define	BlockAddress_RAM_HwPartNumber									__RAM_SHADOW__(0x280)
#define	BlockAddress_ROM_HwPartNumber									__ROM_DEFAULT__(0x280)

#define	BlockAddress_RAM_SystemNameOrEngineType						__RAM_SHADOW__(0x28C)
#define	BlockAddress_ROM_SystemNameOrEngineType						__ROM_DEFAULT__(0x28C)

#define	BlockAddress_RAM_FBL											__RAM_SHADOW__(0x29C)
#define	BlockAddress_ROM_FBL											__ROM_DEFAULT__(0x29C)

#define	BlockAddress_RAM_Identification								__RAM_SHADOW__(0x338)
#define	BlockAddress_ROM_Identification								__ROM_DEFAULT__(0x338)

#define	BlockAddress_RAM_OdxFileVersion								__RAM_SHADOW__(0x350)
#define	BlockAddress_ROM_OdxFileVersion								__ROM_DEFAULT__(0x350)

#define	BlockAddress_RAM_ECUSerialNumber								__RAM_SHADOW__(0x358)
#define	BlockAddress_ROM_ECUSerialNumber								__ROM_DEFAULT__(0x358)

#define	BlockAddress_RAM_LogicalSwBlockVersion							__RAM_SHADOW__(0x36C)
#define	BlockAddress_ROM_LogicalSwBlockVersion							__ROM_DEFAULT__(0x36C)

#define	BlockAddress_RAM_HardwareVersionNumber							__RAM_SHADOW__(0x378)
#define	BlockAddress_ROM_HardwareVersionNumber							__ROM_DEFAULT__(0x378)

#define	BlockAddress_RAM_AppSoftwareVersionNumber						__RAM_SHADOW__(0x37C)
#define	BlockAddress_ROM_AppSoftwareVersionNumber						__ROM_DEFAULT__(0x37C)

#define	BlockAddress_RAM_ECS_STEPS										__RAM_SHADOW__(0x380)
#define	BlockAddress_ROM_ECS_STEPS										__ROM_DEFAULT__(0x380)

#define	BlockAddress_RAM_ECS_PARAMETERS								__RAM_SHADOW__(0x3B8)
#define	BlockAddress_ROM_ECS_PARAMETERS								__ROM_DEFAULT__(0x3B8)

/******************************************************************************
DECLARATION OF TYPES
******************************************************************************/

/******************************************************************************
DECLARATION OF VARIABLES
******************************************************************************/

/******************************************************************************
DECLARATION OF CONSTANT DATA
******************************************************************************/

/******************************************************************************
DECLARATION OF FUNCTIONS
******************************************************************************/

/******************************************************************************
DECLARATION OF FUNCTION-LIKE MACROS
******************************************************************************/

#ifdef __cplusplus
}
#endif
/******************************************************************************
End Of File
*****************************************************************************/

#endif /* NVP_ALIAS_H_ */
