/**************************************************************************************************\
 *** 
 *** Simulink model       : eCS_Algo_Simulation_2015b
 *** TargetLink subsystem : eCS_Algo_Simulation_2015b/eCS
 *** Codefile             : eCS_Config.h
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2022-02-24 09:08:28
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : AUTOSAR
 *** AUTOSAR version                          : 4.2.2
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : enabled
 *** Logging mode                             : Do not log anything
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Loop unroll threshold                    : 5
 *** Shift mode                               : automatic
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : 31 chars
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : enabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 6
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\Program Files\dSPACE TargetLink 4.2\Matlab\Tl\Con
 ***                                            fig\codegen\cconfig.xml
 *** Root style sheet                         : C:\Program Files\dSPACE TargetLink 4.2\Matlab\Tl\XML
 ***                                            \CodeGen\Stylesheets\TL_CSourceCodeSS.xsl
 ***
 *** TargetLink version      : 4.2 from 14-Oct-2016
 *** Code generator version  : Build Id 4.2.0.26 from 2016-10-17 16:31:48

\**************************************************************************************************/

#ifndef ECS_CONFIG_H
#define ECS_CONFIG_H

/*----------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------*/

#include "Rte_Type.h"
#include "NVP_Generated_NvmDefault.h"

/*----------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------*/

/******************************************************************************\
   DEFINE_ECS_CFG: global preprocessor macros
\******************************************************************************/
#define BALL_DAMPER_COEFF ((sint32) NVP_s16BallDamper)
#define BALL_DAMPER_SAT_MAX ((sint32) 3276800 /* 50. */) /* 
   Unit: m.s-1
   LSB: 2^-16 OFF: 0 MIN/MAX: 50 .. 50 */
#define BALL_DAMPER_SAT_MIN ((sint32) -3276800 /* -50. */) /* 
   Unit: m.s-1
   LSB: 2^-16 OFF: 0 MIN/MAX: -50 .. -50 */
#define MToMM ((uint32) 1000)

/******************************************************************************\
   DEFINE_ECS_CFG: global preprocessor macros
\******************************************************************************/
#define CRASH_ACCEL_THRESHOLD ((uint16) 28672 /* 3.5 */) /* 
   Unit: g
   LSB: 2^-13 OFF: 0 MIN/MAX: 1 .. 4
   Description: Crash acceleration threshold in g */
#define BALL_POS_MAX ((sint16) NVP_s16PositionLimit /* 0.001 */) /*
   Unit: m
   LSB: 2^-24 OFF: 0 MIN/MAX: 0 .. 0.0019 */
#define BALL_POS_MIN ((sint16) -NVP_s16PositionLimit /* -0.001 */) /*
   Unit: m
   LSB: 2^-24 OFF: 0 MIN/MAX: -0.0019 .. 0 */
#define CRASH_ACCEL_TRHD_M_PER_S_S ((uint16) 20070 /* 39.2 */) /* 
   Unit: m.s-2
   LSB: 2^-9 OFF: 0 MIN/MAX: 0 .. 39.21
   Description: Crash acceleration threshold in m.s-2 */
#define CRASH_HOLDING_TMR ((uint16) NVP_u16CrashTmr) /*
   LSB: 2^0 OFF: 0 MIN/MAX: 1 .. 65535
   Description: Latch the trigger output for x * 0.5ms */
#define ECS_DELAY_BETWEEN_UNLOCK ((uint16) NVP_u16DelayBetweenUnlocks) /*
   LSB: 2^0 OFF: 0 MIN/MAX: 1 .. 65535
   Description: Latch eCS trigger output for x * 0.5ms */
#define ECS_HOLDING_TRIGGER ((uint16) NVP_u16LatchTmr) /*
   LSB: 2^0 OFF: 0 MIN/MAX: 1 .. 65535
   Description: Latch eCS trigger output for x * 0.5ms */
#define ECS_HOLDING_TRIGGER_LONG ((uint16) NVP_u16LatchTmrLong) /*
   LSB: 2^0 OFF: 0 MIN/MAX: 1 .. 65535
   Description: Latch eCS trigger output for x * 0.5ms */
#define ECS_TRIGGER_OFF ((uint16) NVP_u16eCSTriggOFF /* 0.0001 */) /*
   Unit: m
   LSB: 2^-25 OFF: 0 MIN/MAX: 0.0001 .. 0.0001
   Description: Ball position threshold to UNLOCK  */
#define ECS_TRIGGER_ON ((uint16) NVP_u16eCSTriggON /* 0.0004 */) /*
   Unit: m
   LSB: 2^-25 OFF: 0 MIN/MAX: 0.0004 .. 0.0004
   Description: Ball position threshold to LOCK  */
#define KS16_ACCEL_MAX ((sint16) 20085 /* 39.228 */) /* 
   Unit: m.s-2
   LSB: 2^-9 OFF: 0 MIN/MAX: 39.228 .. 39.228
   Description: Maximum acceleration value for FS = 4g */
#define KS16_ACCEL_MIN ((sint16) -20085 /* -39.228 */) /* 
   Unit: m.s-2
   LSB: 2^-9 OFF: 0 MIN/MAX: -39.228 .. -39.228
   Description: Maximum acceleration value for FS = 4g */
#define KS16_AZ_LOCK_THRS ((sint16) 2511 /* 4.9035 */) /* 
   Unit: m.s-2
   LSB: 2^-9 OFF: 0 MIN/MAX: 4.9035 .. 4.9035
   Description: Z axis acceleration threshold for roll over detection in m/s/s */
#define S16_CALOTTE_ANGLE_1 ((sint16) NVP_s16Angle1 /* 17. */) /*
   Unit: °
   LSB: 2^-10 OFF: 0 MIN/MAX: 17 .. 17
   Description: s32Calotte_Angle_1 */
#define S16_CALOTTE_ANGLE_2 ((sint16) NVP_s16Angle2 /* -12. */) /*
   Unit: °
   LSB: 2^-10 OFF: 0 MIN/MAX: -12 .. -12
   Description: s32Calotte_Angle_1 */

/******************************************************************************\
   DEFINE_ECS_CFG: global preprocessor macros
\******************************************************************************/
#define CAL_B8_SENSITIVITY_OPT ((uint8) NVP_b8SensitivityOpt) /*
   LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 170
   Description: Enable/Disable sensor sensitivity optimization */
#define CRASH_SAMPLES_NB ((uint8) NVP_u8CrashSample) /*
   LSB: 2^0 OFF: 0 MIN/MAX: 1 .. 8
   Description: Number of accelration samples above the crash threshold to LOCK */

/*----------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------*/

/******************************************************************************\
   ECS_NVP_Param: mergeable global variables (RAM) | Width: 16
\******************************************************************************/
#define CAL_AU16_ACC_SENSITIVITY_FACT NVP_au16SensitivityFact /*
   Unit: m.s-2
   LSB: 2^-9 OFF: 0 MIN/MAX: 0 .. 63
   Description: Idx of accel sensitivity LuT m/s² */
#define CAL_AU16_ACC_SENSITIVITY_IDX NVP_au16SensitivityIdx /*
   Unit: m.s-2
   LSB: 2^-9 OFF: 0 MIN/MAX: 0 .. 63
   Description: Idx of accel sensitivity LuT m/s² */
#define CAL_AU16_CALOTTE_ANGLE_1_IDX NVP_au16Angle1_Idx
/*
   Unit: m
   LSB: 2^-24 OFF: 0 MIN/MAX: 0 .. 0.00390619039535522 */
#define CAL_AU16_CALOTTE_ANGLE_2_IDX NVP_au16Angle2_Idx
/*
   Unit: m
   LSB: 2^-24 OFF: 0 MIN/MAX: 0 .. 0.00390619039535522 */
#define CAL_AU16_LUT_CALLOTE_ANGLE_1_FACT NVP_au16Angle1_Fact
/*
   Unit: %
   LSB: 2^-14 OFF: 0 MIN/MAX: 0 .. 3.99993896484375 */
#define CAL_AU16_LUT_CALLOTE_ANGLE_2_FACT NVP_au16Angle2_Fact
/*
   Unit: %
   LSB: 2^-14 OFF: 0 MIN/MAX: 0 .. 3.99993896484375 */

/*----------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------*/
#endif /* ECS_CONFIG_H */
/*----------------------------------------------------------------------------*\
  END OF FILE
\*----------------------------------------------------------------------------*/
