IF "%TARGET%"=="" SET TARGET=CORTEXM
IF "%DERIVATE%"=="" SET DERIVATE=S32K14X
IF "%TOOLCHAIN%"=="" SET TOOLCHAIN=iar
IF [%TOOLPATH_COMPILER%]==[] SET TOOLPATH_COMPILER=C:\devapp\IAR_Systems\Embedded_Workbench_8.3
IF [%TRESOS_BASE%]==[] SET TRESOS_BASE=C:\devapp\EB\tresos_bolo
IF [%PLUGINS_BASE%]==[] set PLUGINS_BASE=%TRESOS_BASE%\plugins

SET WORK_BASE=C:\Projects\CheckOut\BLP-3.X_ACG-8
SET TEST_BASE=C:\Projects\CheckOut\BLP-3.X_ACG-8\test
SET MISRA_MODULE=Demo_VAG
SET MODULE_NAME=Demo_VAG
SET INTERNAL_MODULE_NAME=osc_Demo_VAG
SET MODULE_VARIANT=TS_TxDxM1I0R0
SET MODULE_ID=8.5.1-S32K14X
SET Path=C:\Projects\EBA_WorkSpace\cygwin\bin;%Path%
SET AC_CYGWIN_DOS=C:\Projects\EBA_WorkSpace\cygwin