IF "%TARGET%"=="" SET TARGET=CORTEXM
IF "%DERIVATE%"=="" SET DERIVATE=S32K14X
IF "%TOOLCHAIN%"=="" SET TOOLCHAIN=linaro
IF [%TOOLPATH_COMPILER%]==[] SET TOOLPATH_COMPILER=
IF [%TRESOS_BASE%]==[] SET TRESOS_BASE=C:\EB\tresos
IF [%PLUGINS_BASE%]==[] set PLUGINS_BASE=%TRESOS_BASE%\plugins
