# =========================================================================
#                     CONFIG FILE FOR Detail Design Generator
#   Date: 02 Mar. 2023
#   Copyright Autoliv, RBE, 2023
#   Status: In working
# ==========================================================================

# GENERAL PATHS USED IN SCRIPT

# Please provide here path to Application folder, where components are stored
# For example, on AUDI_TR6: S:\Components\Application
Path to Application Folder: 'S:\Components\Application\Autoliv'

# Write here the path to the Enterprise Architect project
EA_project_path: 's:\Architectures\Application\Description\eCS_SW_Arhitecture.eapx'

# Write here entity of data to be parsed. Type of data to analyse (functions/variables/defines/structures/all)
Data entity to parse: 'all'

# Write here component name to be analysed from Application folder upper defined
List Of Components to be analysed:
    - all
#    - ACC
#    - AdcIf
#    - ATM
#    - BswMIf
#    - CompilerIf
#    - CIL
#    - DcmIf
#    - DemIf
#    - DIA
#    - DioIf
#    - eCS
#    - EcuMIf
#    - EFX
#    - FlsIf
#    - FSM
#    - IoHwAb
#    - LPM
#    - MIC
#    - McuIf
#    - NmIf
#    - NvmIf
#    - NVP
#    - OsIf
#    - PlatformsIf
#    - PortIf
#    - PwmIf
#    - RCM
#    - RTE
#    - RteIf
#    - SAD
#    - SBC
#    - SpiIf
#    - Startup
#    - STM


List Of Components to be ignored:
  - TL_Lib
  - NVP
  - CompilerIf


# Write here new tags to be created in your comments
# The left tag will be used in comments from your code, and the Right tag will be seen in generated design document
New Tags:
  dynamicaspectdescription: 'DynamicAspectDescription'
  dynamicaspectcaller: 'DynamicAspectCaller'
  initialization: 'Initialization'
  staticaspect: 'StaticAspect'
  constrains: 'Constrains'
  range: 'Range'
  inputparam: 'InputParameters'
  outputparam: 'OutputParameters'
  ddesignrequirement: 'Detailed Design Requirement'
  archrequirement: 'Architecture Requirement'
  exception: 'exception'


# =================================
# = Diagrams Aspect Configuration =
# =================================
macro_table_width: 500
variable_table_width: 500
function_table_width: 600
