/******************************************************************************

AUTOLIV ELECTRONIC document.

-------------------------------------------------------------------------------

Copyright Autoliv Inc. All rights reserved.

*******************************************************************************
H-File Template Version:
Template version: AEM_PROCESS_1.25.00
Last template change: AEM_PROCESS_1.00.00
Template release date: 2022-09
*******************************************************************************

Overview of the interfaces:
   This file contains the implementation of the AUTOSAR module Demo_VAG.

******************************************************************************/
/*
$Revision: 1.2 $
$ProjectName: e:/MKSProjects/SBE/eCS/AUDI_MCC/Phase_01/View_Development/Components/Bootloader/Autoliv/FblUsr/Implementation/inc/project.pj $
*/
/*****************************************************************************/
/******************************************************************************
EXTERNAL DEPENDENCIES
******************************************************************************/
#ifdef __cplusplus
extern "C" {
#endif
/******************************************************************************
DEFINITION OF CONSTANTS
******************************************************************************/
#define MEMMAP_ERROR_EBSTUBS

/* Memory section macros for Testing */

#if (defined EBSTUBS_START_SEC_APPL_CODE)
  #ifdef MEMMAP_SECTION_OPENED
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to open section EBSTUBS_START_SEC_APPL_CODE within an already open section.
  #else
    #define MEMMAP_SECTION_OPENED
    #define MEMMAP_SECTION_OPENED_START_SEC_APPL_CODE
    #undef EBSTUBS_START_SEC_APPL_CODE
    #undef MEMMAP_ERROR_EBSTUBS
  #endif
#elif (defined EBSTUBS_STOP_SEC_APPL_CODE)
  #if (defined MEMMAP_SECTION_OPENED) && (defined MEMMAP_SECTION_OPENED_START_SEC_APPL_CODE)
    #undef MEMMAP_SECTION_OPENED
    #undef MEMMAP_SECTION_OPENED_START_SEC_APPL_CODE
    #undef EBSTUBS_STOP_SEC_APPL_CODE
    #undef MEMMAP_ERROR_EBSTUBS
  #else
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to close section EBSTUBS_STOP_SEC_APPL_CODE without prior opening EBSTUBS_START_SEC_APPL_CODE.
  #endif
#elif (defined EBSTUBS_START_SEC_CALLOUT_CODE)
  #ifdef MEMMAP_SECTION_OPENED
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to open section EBSTUBS_START_SEC_CALLOUT_CODE within an already open section.
  #else
    #define MEMMAP_SECTION_OPENED
    #define MEMMAP_SECTION_OPENED_START_SEC_CALLOUT_CODE
    #undef EBSTUBS_START_SEC_CALLOUT_CODE
    #undef MEMMAP_ERROR_EBSTUBS
  #endif
#elif (defined EBSTUBS_STOP_SEC_CALLOUT_CODE)
  #if (defined MEMMAP_SECTION_OPENED) && (defined MEMMAP_SECTION_OPENED_START_SEC_CALLOUT_CODE)
    #undef MEMMAP_SECTION_OPENED
    #undef MEMMAP_SECTION_OPENED_START_SEC_CALLOUT_CODE
    #undef EBSTUBS_STOP_SEC_CALLOUT_CODE
    #undef MEMMAP_ERROR_EBSTUBS
  #else
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to close section EBSTUBS_STOP_SEC_CALLOUT_CODE without prior opening EBSTUBS_START_SEC_CALLOUT_CODE.
  #endif
#elif (defined EBSTUBS_START_SEC_CODE)
  #ifdef MEMMAP_SECTION_OPENED
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to open section EBSTUBS_START_SEC_CODE within an already open section.
  #else
    #define MEMMAP_SECTION_OPENED
    #define MEMMAP_SECTION_OPENED_START_SEC_CODE
    #undef EBSTUBS_START_SEC_CODE
    #undef MEMMAP_ERROR_EBSTUBS
  #endif
#elif (defined EBSTUBS_STOP_SEC_CODE)
  #if (defined MEMMAP_SECTION_OPENED) && (defined MEMMAP_SECTION_OPENED_START_SEC_CODE)
    #undef MEMMAP_SECTION_OPENED
    #undef MEMMAP_SECTION_OPENED_START_SEC_CODE
    #undef EBSTUBS_STOP_SEC_CODE
    #undef MEMMAP_ERROR_EBSTUBS
  #else
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to close section EBSTUBS_STOP_SEC_CODE without prior opening EBSTUBS_START_SEC_CODE.
  #endif
#elif (defined EBSTUBS_START_SEC_CONFIG_DATA_UNSPECIFIED)
  #ifdef MEMMAP_SECTION_OPENED
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to open section EBSTUBS_START_SEC_CONFIG_DATA_UNSPECIFIED within an already open section.
  #else
    #define MEMMAP_SECTION_OPENED
    #define MEMMAP_SECTION_OPENED_START_SEC_CONFIG_DATA_UNSPECIFIED
    #undef EBSTUBS_START_SEC_CONFIG_DATA_UNSPECIFIED
    #undef MEMMAP_ERROR_EBSTUBS
  #endif
#elif (defined EBSTUBS_STOP_SEC_CONFIG_DATA_UNSPECIFIED)
  #if (defined MEMMAP_SECTION_OPENED) && (defined MEMMAP_SECTION_OPENED_START_SEC_CONFIG_DATA_UNSPECIFIED)
    #undef MEMMAP_SECTION_OPENED
    #undef MEMMAP_SECTION_OPENED_START_SEC_CONFIG_DATA_UNSPECIFIED
    #undef EBSTUBS_STOP_SEC_CONFIG_DATA_UNSPECIFIED
    #undef MEMMAP_ERROR_EBSTUBS
  #else
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to close section EBSTUBS_STOP_SEC_CONFIG_DATA_UNSPECIFIED without prior opening EBSTUBS_START_SEC_CONFIG_DATA_UNSPECIFIED.
  #endif
#elif (defined EBSTUBS_START_CONFIG_DATA_UNSPECIFIED)
    #undef EBSTUBS_START_CONFIG_DATA_UNSPECIFIED
    #undef MEMMAP_ERROR_EBSTUBS
#elif (defined EBSTUBS_STOP_CONFIG_DATA_UNSPECIFIED)
    #undef EBSTUBS_STOP_CONFIG_DATA_UNSPECIFIED
    #undef MEMMAP_ERROR_EBSTUBS
#elif (defined EBSTUBS_START_SEC_CONST_16)
  #ifdef MEMMAP_SECTION_OPENED
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to open section EBSTUBS_START_SEC_CONST_16 within an already open section.
  #else
    #define MEMMAP_SECTION_OPENED
    #define MEMMAP_SECTION_OPENED_START_SEC_CONST_16
    #undef EBSTUBS_START_SEC_CONST_16
    #undef MEMMAP_ERROR_EBSTUBS
  #endif
#elif (defined EBSTUBS_STOP_SEC_CONST_16)
  #if (defined MEMMAP_SECTION_OPENED) && (defined MEMMAP_SECTION_OPENED_START_SEC_CONST_16)
    #undef MEMMAP_SECTION_OPENED
    #undef MEMMAP_SECTION_OPENED_START_SEC_CONST_16
    #undef EBSTUBS_STOP_SEC_CONST_16
    #undef MEMMAP_ERROR_EBSTUBS
  #else
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to close section EBSTUBS_STOP_SEC_CONST_16 without prior opening EBSTUBS_START_SEC_CONST_16.
  #endif
#elif (defined EBSTUBS_START_SEC_CONST_16BIT)
  #ifdef MEMMAP_SECTION_OPENED
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to open section EBSTUBS_START_SEC_CONST_16BIT within an already open section.
  #else
    #define MEMMAP_SECTION_OPENED
    #define MEMMAP_SECTION_OPENED_START_SEC_CONST_16BIT
    #undef EBSTUBS_START_SEC_CONST_16BIT
    #undef MEMMAP_ERROR_EBSTUBS
  #endif
#elif (defined EBSTUBS_STOP_SEC_CONST_16BIT)
  #if (defined MEMMAP_SECTION_OPENED) && (defined MEMMAP_SECTION_OPENED_START_SEC_CONST_16BIT)
    #undef MEMMAP_SECTION_OPENED
    #undef MEMMAP_SECTION_OPENED_START_SEC_CONST_16BIT
    #undef EBSTUBS_STOP_SEC_CONST_16BIT
    #undef MEMMAP_ERROR_EBSTUBS
  #else
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to close section EBSTUBS_STOP_SEC_CONST_16BIT without prior opening EBSTUBS_START_SEC_CONST_16BIT.
  #endif
#elif (defined EBSTUBS_START_SEC_CONST_32)
  #ifdef MEMMAP_SECTION_OPENED
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to open section EBSTUBS_START_SEC_CONST_32 within an already open section.
  #else
    #define MEMMAP_SECTION_OPENED
    #define MEMMAP_SECTION_OPENED_START_SEC_CONST_32
    #undef EBSTUBS_START_SEC_CONST_32
    #undef MEMMAP_ERROR_EBSTUBS
  #endif
#elif (defined EBSTUBS_STOP_SEC_CONST_32)
  #if (defined MEMMAP_SECTION_OPENED) && (defined MEMMAP_SECTION_OPENED_START_SEC_CONST_32)
    #undef MEMMAP_SECTION_OPENED
    #undef MEMMAP_SECTION_OPENED_START_SEC_CONST_32
    #undef EBSTUBS_STOP_SEC_CONST_32
    #undef MEMMAP_ERROR_EBSTUBS
  #else
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to close section EBSTUBS_STOP_SEC_CONST_32 without prior opening EBSTUBS_START_SEC_CONST_32.
  #endif
#elif (defined EBSTUBS_START_SEC_CONST_32BIT)
  #ifdef MEMMAP_SECTION_OPENED
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to open section EBSTUBS_START_SEC_CONST_32BIT within an already open section.
  #else
    #define MEMMAP_SECTION_OPENED
    #define MEMMAP_SECTION_OPENED_START_SEC_CONST_32BIT
    #undef EBSTUBS_START_SEC_CONST_32BIT
    #undef MEMMAP_ERROR_EBSTUBS
  #endif
#elif (defined EBSTUBS_STOP_SEC_CONST_32BIT)
  #if (defined MEMMAP_SECTION_OPENED) && (defined MEMMAP_SECTION_OPENED_START_SEC_CONST_32BIT)
    #undef MEMMAP_SECTION_OPENED
    #undef MEMMAP_SECTION_OPENED_START_SEC_CONST_32BIT
    #undef EBSTUBS_STOP_SEC_CONST_32BIT
    #undef MEMMAP_ERROR_EBSTUBS
  #else
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to close section EBSTUBS_STOP_SEC_CONST_32BIT without prior opening EBSTUBS_START_SEC_CONST_32BIT.
  #endif
#elif (defined EBSTUBS_START_SEC_CONST_8)
  #ifdef MEMMAP_SECTION_OPENED
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to open section EBSTUBS_START_SEC_CONST_8 within an already open section.
  #else
    #define MEMMAP_SECTION_OPENED
    #define MEMMAP_SECTION_OPENED_START_SEC_CONST_8
    #undef EBSTUBS_START_SEC_CONST_8
    #undef MEMMAP_ERROR_EBSTUBS
  #endif
#elif (defined EBSTUBS_STOP_SEC_CONST_8)
  #if (defined MEMMAP_SECTION_OPENED) && (defined MEMMAP_SECTION_OPENED_START_SEC_CONST_8)
    #undef MEMMAP_SECTION_OPENED
    #undef MEMMAP_SECTION_OPENED_START_SEC_CONST_8
    #undef EBSTUBS_STOP_SEC_CONST_8
    #undef MEMMAP_ERROR_EBSTUBS
  #else
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to close section EBSTUBS_STOP_SEC_CONST_8 without prior opening EBSTUBS_START_SEC_CONST_8.
  #endif
#elif (defined EBSTUBS_START_SEC_CONST_8BIT)
  #ifdef MEMMAP_SECTION_OPENED
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to open section EBSTUBS_START_SEC_CONST_8BIT within an already open section.
  #else
    #define MEMMAP_SECTION_OPENED
    #define MEMMAP_SECTION_OPENED_START_SEC_CONST_8BIT
    #undef EBSTUBS_START_SEC_CONST_8BIT
    #undef MEMMAP_ERROR_EBSTUBS
  #endif
#elif (defined EBSTUBS_STOP_SEC_CONST_8BIT)
  #if (defined MEMMAP_SECTION_OPENED) && (defined MEMMAP_SECTION_OPENED_START_SEC_CONST_8BIT)
    #undef MEMMAP_SECTION_OPENED
    #undef MEMMAP_SECTION_OPENED_START_SEC_CONST_8BIT
    #undef EBSTUBS_STOP_SEC_CONST_8BIT
    #undef MEMMAP_ERROR_EBSTUBS
  #else
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to close section EBSTUBS_STOP_SEC_CONST_8BIT without prior opening EBSTUBS_START_SEC_CONST_8BIT.
  #endif
#elif (defined EBSTUBS_START_SEC_CONST_BOOLEAN)
  #ifdef MEMMAP_SECTION_OPENED
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to open section EBSTUBS_START_SEC_CONST_BOOLEAN within an already open section.
  #else
    #define MEMMAP_SECTION_OPENED
    #define MEMMAP_SECTION_OPENED_START_SEC_CONST_BOOLEAN
    #undef EBSTUBS_START_SEC_CONST_BOOLEAN
    #undef MEMMAP_ERROR_EBSTUBS
  #endif
#elif (defined EBSTUBS_STOP_SEC_CONST_BOOLEAN)
  #if (defined MEMMAP_SECTION_OPENED) && (defined MEMMAP_SECTION_OPENED_START_SEC_CONST_BOOLEAN)
    #undef MEMMAP_SECTION_OPENED
    #undef MEMMAP_SECTION_OPENED_START_SEC_CONST_BOOLEAN
    #undef EBSTUBS_STOP_SEC_CONST_BOOLEAN
    #undef MEMMAP_ERROR_EBSTUBS
  #else
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to close section EBSTUBS_STOP_SEC_CONST_BOOLEAN without prior opening EBSTUBS_START_SEC_CONST_BOOLEAN.
  #endif
#elif (defined EBSTUBS_START_SEC_CONST_UNSPECIFIED)
  #ifdef MEMMAP_SECTION_OPENED
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to open section EBSTUBS_START_SEC_CONST_UNSPECIFIED within an already open section.
  #else
    #define MEMMAP_SECTION_OPENED
    #define MEMMAP_SECTION_OPENED_START_SEC_CONST_UNSPECIFIED
    #undef EBSTUBS_START_SEC_CONST_UNSPECIFIED
    #undef MEMMAP_ERROR_EBSTUBS
  #endif
#elif (defined EBSTUBS_STOP_SEC_CONST_UNSPECIFIED)
  #if (defined MEMMAP_SECTION_OPENED) && (defined MEMMAP_SECTION_OPENED_START_SEC_CONST_UNSPECIFIED)
    #undef MEMMAP_SECTION_OPENED
    #undef MEMMAP_SECTION_OPENED_START_SEC_CONST_UNSPECIFIED
    #undef EBSTUBS_STOP_SEC_CONST_UNSPECIFIED
    #undef MEMMAP_ERROR_EBSTUBS
  #else
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to close section EBSTUBS_STOP_SEC_CONST_UNSPECIFIED without prior opening EBSTUBS_START_SEC_CONST_UNSPECIFIED.
  #endif
#elif (defined EBSTUBS_START_SEC_VAR_16BIT)
  #ifdef MEMMAP_SECTION_OPENED
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to open section EBSTUBS_START_SEC_VAR_16BIT within an already open section.
  #else
    #define MEMMAP_SECTION_OPENED
    #define MEMMAP_SECTION_OPENED_START_SEC_VAR_16BIT
    #undef EBSTUBS_START_SEC_VAR_16BIT
    #undef MEMMAP_ERROR_EBSTUBS
  #endif
#elif (defined EBSTUBS_STOP_SEC_VAR_16BIT)
  #if (defined MEMMAP_SECTION_OPENED) && (defined MEMMAP_SECTION_OPENED_START_SEC_VAR_16BIT)
    #undef MEMMAP_SECTION_OPENED
    #undef MEMMAP_SECTION_OPENED_START_SEC_VAR_16BIT
    #undef EBSTUBS_STOP_SEC_VAR_16BIT
    #undef MEMMAP_ERROR_EBSTUBS
  #else
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to close section EBSTUBS_STOP_SEC_VAR_16BIT without prior opening EBSTUBS_START_SEC_VAR_16BIT.
  #endif
#elif (defined EBSTUBS_START_SEC_VAR_32BIT)
  #ifdef MEMMAP_SECTION_OPENED
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to open section EBSTUBS_START_SEC_VAR_32BIT within an already open section.
  #else
    #define MEMMAP_SECTION_OPENED
    #define MEMMAP_SECTION_OPENED_START_SEC_VAR_32BIT
    #undef EBSTUBS_START_SEC_VAR_32BIT
    #undef MEMMAP_ERROR_EBSTUBS
  #endif
#elif (defined EBSTUBS_STOP_SEC_VAR_32BIT)
  #if (defined MEMMAP_SECTION_OPENED) && (defined MEMMAP_SECTION_OPENED_START_SEC_VAR_32BIT)
    #undef MEMMAP_SECTION_OPENED
    #undef MEMMAP_SECTION_OPENED_START_SEC_VAR_32BIT
    #undef EBSTUBS_STOP_SEC_VAR_32BIT
    #undef MEMMAP_ERROR_EBSTUBS
  #else
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to close section EBSTUBS_STOP_SEC_VAR_32BIT without prior opening EBSTUBS_START_SEC_VAR_32BIT.
  #endif
#elif (defined EBSTUBS_START_SEC_VAR_8BIT)
  #ifdef MEMMAP_SECTION_OPENED
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to open section EBSTUBS_START_SEC_VAR_8BIT within an already open section.
  #else
    #define MEMMAP_SECTION_OPENED
    #define MEMMAP_SECTION_OPENED_START_SEC_VAR_8BIT
    #undef EBSTUBS_START_SEC_VAR_8BIT
    #undef MEMMAP_ERROR_EBSTUBS
  #endif
#elif (defined EBSTUBS_STOP_SEC_VAR_8BIT)
  #if (defined MEMMAP_SECTION_OPENED) && (defined MEMMAP_SECTION_OPENED_START_SEC_VAR_8BIT)
    #undef MEMMAP_SECTION_OPENED
    #undef MEMMAP_SECTION_OPENED_START_SEC_VAR_8BIT
    #undef EBSTUBS_STOP_SEC_VAR_8BIT
    #undef MEMMAP_ERROR_EBSTUBS
  #else
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to close section EBSTUBS_STOP_SEC_VAR_8BIT without prior opening EBSTUBS_START_SEC_VAR_8BIT.
  #endif
#elif (defined EBSTUBS_START_SEC_VAR_BOOLEAN)
  #ifdef MEMMAP_SECTION_OPENED
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to open section EBSTUBS_START_SEC_VAR_BOOLEAN within an already open section.
  #else
    #define MEMMAP_SECTION_OPENED
    #define MEMMAP_SECTION_OPENED_START_SEC_VAR_BOOLEAN
    #undef EBSTUBS_START_SEC_VAR_BOOLEAN
    #undef MEMMAP_ERROR_EBSTUBS
  #endif
#elif (defined EBSTUBS_STOP_SEC_VAR_BOOLEAN)
  #if (defined MEMMAP_SECTION_OPENED) && (defined MEMMAP_SECTION_OPENED_START_SEC_VAR_BOOLEAN)
    #undef MEMMAP_SECTION_OPENED
    #undef MEMMAP_SECTION_OPENED_START_SEC_VAR_BOOLEAN
    #undef EBSTUBS_STOP_SEC_VAR_BOOLEAN
    #undef MEMMAP_ERROR_EBSTUBS
  #else
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to close section EBSTUBS_STOP_SEC_VAR_BOOLEAN without prior opening EBSTUBS_START_SEC_VAR_BOOLEAN.
  #endif
#elif (defined EBSTUBS_START_SEC_VAR_CLEARED_16)
  #ifdef MEMMAP_SECTION_OPENED
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to open section EBSTUBS_START_SEC_VAR_CLEARED_16 within an already open section.
  #else
    #define MEMMAP_SECTION_OPENED
    #define MEMMAP_SECTION_OPENED_START_SEC_VAR_CLEARED_16
    #undef EBSTUBS_START_SEC_VAR_CLEARED_16
    #undef MEMMAP_ERROR_EBSTUBS
  #endif
#elif (defined EBSTUBS_STOP_SEC_VAR_CLEARED_16)
  #if (defined MEMMAP_SECTION_OPENED) && (defined MEMMAP_SECTION_OPENED_START_SEC_VAR_CLEARED_16)
    #undef MEMMAP_SECTION_OPENED
    #undef MEMMAP_SECTION_OPENED_START_SEC_VAR_CLEARED_16
    #undef EBSTUBS_STOP_SEC_VAR_CLEARED_16
    #undef MEMMAP_ERROR_EBSTUBS
  #else
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to close section EBSTUBS_STOP_SEC_VAR_CLEARED_16 without prior opening EBSTUBS_START_SEC_VAR_CLEARED_16.
  #endif
#elif (defined EBSTUBS_START_SEC_VAR_CLEARED_32)
  #ifdef MEMMAP_SECTION_OPENED
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to open section EBSTUBS_START_SEC_VAR_CLEARED_32 within an already open section.
  #else
    #define MEMMAP_SECTION_OPENED
    #define MEMMAP_SECTION_OPENED_START_SEC_VAR_CLEARED_32
    #undef EBSTUBS_START_SEC_VAR_CLEARED_32
    #undef MEMMAP_ERROR_EBSTUBS
  #endif
#elif (defined EBSTUBS_STOP_SEC_VAR_CLEARED_32)
  #if (defined MEMMAP_SECTION_OPENED) && (defined MEMMAP_SECTION_OPENED_START_SEC_VAR_CLEARED_32)
    #undef MEMMAP_SECTION_OPENED
    #undef MEMMAP_SECTION_OPENED_START_SEC_VAR_CLEARED_32
    #undef EBSTUBS_STOP_SEC_VAR_CLEARED_32
    #undef MEMMAP_ERROR_EBSTUBS
  #else
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to close section EBSTUBS_STOP_SEC_VAR_CLEARED_32 without prior opening EBSTUBS_START_SEC_VAR_CLEARED_32.
  #endif
#elif (defined EBSTUBS_START_SEC_VAR_CLEARED_8)
  #ifdef MEMMAP_SECTION_OPENED
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to open section EBSTUBS_START_SEC_VAR_CLEARED_8 within an already open section.
  #else
    #define MEMMAP_SECTION_OPENED
    #define MEMMAP_SECTION_OPENED_START_SEC_VAR_CLEARED_8
    #undef EBSTUBS_START_SEC_VAR_CLEARED_8
    #undef MEMMAP_ERROR_EBSTUBS
  #endif
#elif (defined EBSTUBS_STOP_SEC_VAR_CLEARED_8)
  #if (defined MEMMAP_SECTION_OPENED) && (defined MEMMAP_SECTION_OPENED_START_SEC_VAR_CLEARED_8)
    #undef MEMMAP_SECTION_OPENED
    #undef MEMMAP_SECTION_OPENED_START_SEC_VAR_CLEARED_8
    #undef EBSTUBS_STOP_SEC_VAR_CLEARED_8
    #undef MEMMAP_ERROR_EBSTUBS
  #else
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to close section EBSTUBS_STOP_SEC_VAR_CLEARED_8 without prior opening EBSTUBS_START_SEC_VAR_CLEARED_8.
  #endif
#elif (defined EBSTUBS_START_SEC_VAR_CLEARED_BOOLEAN)
  #ifdef MEMMAP_SECTION_OPENED
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to open section EBSTUBS_START_SEC_VAR_CLEARED_BOOLEAN within an already open section.
  #else
    #define MEMMAP_SECTION_OPENED
    #define MEMMAP_SECTION_OPENED_START_SEC_VAR_CLEARED_BOOLEAN
    #undef EBSTUBS_START_SEC_VAR_CLEARED_BOOLEAN
    #undef MEMMAP_ERROR_EBSTUBS
  #endif
#elif (defined EBSTUBS_STOP_SEC_VAR_CLEARED_BOOLEAN)
  #if (defined MEMMAP_SECTION_OPENED) && (defined MEMMAP_SECTION_OPENED_START_SEC_VAR_CLEARED_BOOLEAN)
    #undef MEMMAP_SECTION_OPENED
    #undef MEMMAP_SECTION_OPENED_START_SEC_VAR_CLEARED_BOOLEAN
    #undef EBSTUBS_STOP_SEC_VAR_CLEARED_BOOLEAN
    #undef MEMMAP_ERROR_EBSTUBS
  #else
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to close section EBSTUBS_STOP_SEC_VAR_CLEARED_BOOLEAN without prior opening EBSTUBS_START_SEC_VAR_CLEARED_BOOLEAN.
  #endif
#elif (defined EBSTUBS_START_SEC_VAR_CLEARED_UNSPECIFIED)
  #ifdef MEMMAP_SECTION_OPENED
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to open section EBSTUBS_START_SEC_VAR_CLEARED_UNSPECIFIED within an already open section.
  #else
    #define MEMMAP_SECTION_OPENED
    #define MEMMAP_SECTION_OPENED_START_SEC_VAR_CLEARED_UNSPECIFIED
    #undef EBSTUBS_START_SEC_VAR_CLEARED_UNSPECIFIED
    #undef MEMMAP_ERROR_EBSTUBS
  #endif
#elif (defined EBSTUBS_STOP_SEC_VAR_CLEARED_UNSPECIFIED)
  #if (defined MEMMAP_SECTION_OPENED) && (defined MEMMAP_SECTION_OPENED_START_SEC_VAR_CLEARED_UNSPECIFIED)
    #undef MEMMAP_SECTION_OPENED
    #undef MEMMAP_SECTION_OPENED_START_SEC_VAR_CLEARED_UNSPECIFIED
    #undef EBSTUBS_STOP_SEC_VAR_CLEARED_UNSPECIFIED
    #undef MEMMAP_ERROR_EBSTUBS
  #else
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to close section EBSTUBS_STOP_SEC_VAR_CLEARED_UNSPECIFIED without prior opening EBSTUBS_START_SEC_VAR_CLEARED_UNSPECIFIED.
  #endif
#elif (defined EBSTUBS_START_SEC_VAR_FAST_UNSPECIFIED)
  #ifdef MEMMAP_SECTION_OPENED
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to open section EBSTUBS_START_SEC_VAR_FAST_UNSPECIFIED within an already open section.
  #else
    #define MEMMAP_SECTION_OPENED
    #define MEMMAP_SECTION_OPENED_START_SEC_VAR_FAST_UNSPECIFIED
    #undef EBSTUBS_START_SEC_VAR_FAST_UNSPECIFIED
    #undef MEMMAP_ERROR_EBSTUBS
  #endif
#elif (defined EBSTUBS_STOP_SEC_VAR_FAST_UNSPECIFIED)
  #if (defined MEMMAP_SECTION_OPENED) && (defined MEMMAP_SECTION_OPENED_START_SEC_VAR_FAST_UNSPECIFIED)
    #undef MEMMAP_SECTION_OPENED
    #undef MEMMAP_SECTION_OPENED_START_SEC_VAR_FAST_UNSPECIFIED
    #undef EBSTUBS_STOP_SEC_VAR_FAST_UNSPECIFIED
    #undef MEMMAP_ERROR_EBSTUBS
  #else
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to close section EBSTUBS_STOP_SEC_VAR_FAST_UNSPECIFIED without prior opening EBSTUBS_START_SEC_VAR_FAST_UNSPECIFIED.
  #endif
#elif (defined EBSTUBS_START_SEC_VAR_INIT_16)
  #ifdef MEMMAP_SECTION_OPENED
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to open section EBSTUBS_START_SEC_VAR_INIT_16 within an already open section.
  #else
    #define MEMMAP_SECTION_OPENED
    #define MEMMAP_SECTION_OPENED_START_SEC_VAR_INIT_16
    #undef EBSTUBS_START_SEC_VAR_INIT_16
    #undef MEMMAP_ERROR_EBSTUBS
  #endif
#elif (defined EBSTUBS_STOP_SEC_VAR_INIT_16)
  #if (defined MEMMAP_SECTION_OPENED) && (defined MEMMAP_SECTION_OPENED_START_SEC_VAR_INIT_16)
    #undef MEMMAP_SECTION_OPENED
    #undef MEMMAP_SECTION_OPENED_START_SEC_VAR_INIT_16
    #undef EBSTUBS_STOP_SEC_VAR_INIT_16
    #undef MEMMAP_ERROR_EBSTUBS
  #else
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to close section EBSTUBS_STOP_SEC_VAR_INIT_16 without prior opening EBSTUBS_START_SEC_VAR_INIT_16.
  #endif
#elif (defined EBSTUBS_START_SEC_VAR_INIT_32)
  #ifdef MEMMAP_SECTION_OPENED
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to open section EBSTUBS_START_SEC_VAR_INIT_32 within an already open section.
  #else
    #define MEMMAP_SECTION_OPENED
    #define MEMMAP_SECTION_OPENED_START_SEC_VAR_INIT_32
    #undef EBSTUBS_START_SEC_VAR_INIT_32
    #undef MEMMAP_ERROR_EBSTUBS
  #endif
#elif (defined EBSTUBS_STOP_SEC_VAR_INIT_32)
  #if (defined MEMMAP_SECTION_OPENED) && (defined MEMMAP_SECTION_OPENED_START_SEC_VAR_INIT_32)
    #undef MEMMAP_SECTION_OPENED
    #undef MEMMAP_SECTION_OPENED_START_SEC_VAR_INIT_32
    #undef EBSTUBS_STOP_SEC_VAR_INIT_32
    #undef MEMMAP_ERROR_EBSTUBS
  #else
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to close section EBSTUBS_STOP_SEC_VAR_INIT_32 without prior opening EBSTUBS_START_SEC_VAR_INIT_32.
  #endif
#elif (defined EBSTUBS_START_SEC_VAR_INIT_8)
  #ifdef MEMMAP_SECTION_OPENED
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to open section EBSTUBS_START_SEC_VAR_INIT_8 within an already open section.
  #else
    #define MEMMAP_SECTION_OPENED
    #define MEMMAP_SECTION_OPENED_START_SEC_VAR_INIT_8
    #undef EBSTUBS_START_SEC_VAR_INIT_8
    #undef MEMMAP_ERROR_EBSTUBS
  #endif
#elif (defined EBSTUBS_STOP_SEC_VAR_INIT_8)
  #if (defined MEMMAP_SECTION_OPENED) && (defined MEMMAP_SECTION_OPENED_START_SEC_VAR_INIT_8)
    #undef MEMMAP_SECTION_OPENED
    #undef MEMMAP_SECTION_OPENED_START_SEC_VAR_INIT_8
    #undef EBSTUBS_STOP_SEC_VAR_INIT_8
    #undef MEMMAP_ERROR_EBSTUBS
  #else
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to close section EBSTUBS_STOP_SEC_VAR_INIT_8 without prior opening EBSTUBS_START_SEC_VAR_INIT_8.
  #endif
#elif (defined EBSTUBS_START_SEC_VAR_INIT_BOOLEAN)
  #ifdef MEMMAP_SECTION_OPENED
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to open section EBSTUBS_START_SEC_VAR_INIT_BOOLEAN within an already open section.
  #else
    #define MEMMAP_SECTION_OPENED
    #define MEMMAP_SECTION_OPENED_START_SEC_VAR_INIT_BOOLEAN
    #undef EBSTUBS_START_SEC_VAR_INIT_BOOLEAN
    #undef MEMMAP_ERROR_EBSTUBS
  #endif
#elif (defined EBSTUBS_STOP_SEC_VAR_INIT_BOOLEAN)
  #if (defined MEMMAP_SECTION_OPENED) && (defined MEMMAP_SECTION_OPENED_START_SEC_VAR_INIT_BOOLEAN)
    #undef MEMMAP_SECTION_OPENED
    #undef MEMMAP_SECTION_OPENED_START_SEC_VAR_INIT_BOOLEAN
    #undef EBSTUBS_STOP_SEC_VAR_INIT_BOOLEAN
    #undef MEMMAP_ERROR_EBSTUBS
  #else
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to close section EBSTUBS_STOP_SEC_VAR_INIT_BOOLEAN without prior opening EBSTUBS_START_SEC_VAR_INIT_BOOLEAN.
  #endif
#elif (defined EBSTUBS_START_SEC_VAR_INIT_UNSPECIFIED)
  #ifdef MEMMAP_SECTION_OPENED
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to open section EBSTUBS_START_SEC_VAR_INIT_UNSPECIFIED within an already open section.
  #else
    #define MEMMAP_SECTION_OPENED
    #define MEMMAP_SECTION_OPENED_START_SEC_VAR_INIT_UNSPECIFIED
    #undef EBSTUBS_START_SEC_VAR_INIT_UNSPECIFIED
    #undef MEMMAP_ERROR_EBSTUBS
  #endif
#elif (defined EBSTUBS_STOP_SEC_VAR_INIT_UNSPECIFIED)
  #if (defined MEMMAP_SECTION_OPENED) && (defined MEMMAP_SECTION_OPENED_START_SEC_VAR_INIT_UNSPECIFIED)
    #undef MEMMAP_SECTION_OPENED
    #undef MEMMAP_SECTION_OPENED_START_SEC_VAR_INIT_UNSPECIFIED
    #undef EBSTUBS_STOP_SEC_VAR_INIT_UNSPECIFIED
    #undef MEMMAP_ERROR_EBSTUBS
  #else
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to close section EBSTUBS_STOP_SEC_VAR_INIT_UNSPECIFIED without prior opening EBSTUBS_START_SEC_VAR_INIT_UNSPECIFIED.
  #endif
#elif (defined EBSTUBS_START_SEC_VAR_NOINIT_16BIT)
  #ifdef MEMMAP_SECTION_OPENED
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to open section EBSTUBS_START_SEC_VAR_NOINIT_16BIT within an already open section.
  #else
    #define MEMMAP_SECTION_OPENED
    #define MEMMAP_SECTION_OPENED_START_SEC_VAR_NOINIT_16BIT
    #undef EBSTUBS_START_SEC_VAR_NOINIT_16BIT
    #undef MEMMAP_ERROR_EBSTUBS
  #endif
#elif (defined EBSTUBS_STOP_SEC_VAR_NOINIT_16BIT)
  #if (defined MEMMAP_SECTION_OPENED) && (defined MEMMAP_SECTION_OPENED_START_SEC_VAR_NOINIT_16BIT)
    #undef MEMMAP_SECTION_OPENED
    #undef MEMMAP_SECTION_OPENED_START_SEC_VAR_NOINIT_16BIT
    #undef EBSTUBS_STOP_SEC_VAR_NOINIT_16BIT
    #undef MEMMAP_ERROR_EBSTUBS
  #else
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to close section EBSTUBS_STOP_SEC_VAR_NOINIT_16BIT without prior opening EBSTUBS_START_SEC_VAR_NOINIT_16BIT.
  #endif
#elif (defined EBSTUBS_START_SEC_VAR_NOINIT_32BIT)
  #ifdef MEMMAP_SECTION_OPENED
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to open section EBSTUBS_START_SEC_VAR_NOINIT_32BIT within an already open section.
  #else
    #define MEMMAP_SECTION_OPENED
    #define MEMMAP_SECTION_OPENED_START_SEC_VAR_NOINIT_32BIT
    #undef EBSTUBS_START_SEC_VAR_NOINIT_32BIT
    #undef MEMMAP_ERROR_EBSTUBS
  #endif
#elif (defined EBSTUBS_STOP_SEC_VAR_NOINIT_32BIT)
  #if (defined MEMMAP_SECTION_OPENED) && (defined MEMMAP_SECTION_OPENED_START_SEC_VAR_NOINIT_32BIT)
    #undef MEMMAP_SECTION_OPENED
    #undef MEMMAP_SECTION_OPENED_START_SEC_VAR_NOINIT_32BIT
    #undef EBSTUBS_STOP_SEC_VAR_NOINIT_32BIT
    #undef MEMMAP_ERROR_EBSTUBS
  #else
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to close section EBSTUBS_STOP_SEC_VAR_NOINIT_32BIT without prior opening EBSTUBS_START_SEC_VAR_NOINIT_32BIT.
  #endif
#elif (defined EBSTUBS_START_SEC_VAR_NOINIT_8BIT)
  #ifdef MEMMAP_SECTION_OPENED
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to open section EBSTUBS_START_SEC_VAR_NOINIT_8BIT within an already open section.
  #else
    #define MEMMAP_SECTION_OPENED
    #define MEMMAP_SECTION_OPENED_START_SEC_VAR_NOINIT_8BIT
    #undef EBSTUBS_START_SEC_VAR_NOINIT_8BIT
    #undef MEMMAP_ERROR_EBSTUBS
  #endif
#elif (defined EBSTUBS_STOP_SEC_VAR_NOINIT_8BIT)
  #if (defined MEMMAP_SECTION_OPENED) && (defined MEMMAP_SECTION_OPENED_START_SEC_VAR_NOINIT_8BIT)
    #undef MEMMAP_SECTION_OPENED
    #undef MEMMAP_SECTION_OPENED_START_SEC_VAR_NOINIT_8BIT
    #undef EBSTUBS_STOP_SEC_VAR_NOINIT_8BIT
    #undef MEMMAP_ERROR_EBSTUBS
  #else
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to close section EBSTUBS_STOP_SEC_VAR_NOINIT_8BIT without prior opening EBSTUBS_START_SEC_VAR_NOINIT_8BIT.
  #endif
#elif (defined EBSTUBS_START_SEC_VAR_NOINIT_BOOLEAN)
  #ifdef MEMMAP_SECTION_OPENED
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to open section EBSTUBS_START_SEC_VAR_NOINIT_BOOLEAN within an already open section.
  #else
    #define MEMMAP_SECTION_OPENED
    #define MEMMAP_SECTION_OPENED_START_SEC_VAR_NOINIT_BOOLEAN
    #undef EBSTUBS_START_SEC_VAR_NOINIT_BOOLEAN
    #undef MEMMAP_ERROR_EBSTUBS
  #endif
#elif (defined EBSTUBS_STOP_SEC_VAR_NOINIT_BOOLEAN)
  #if (defined MEMMAP_SECTION_OPENED) && (defined MEMMAP_SECTION_OPENED_START_SEC_VAR_NOINIT_BOOLEAN)
    #undef MEMMAP_SECTION_OPENED
    #undef MEMMAP_SECTION_OPENED_START_SEC_VAR_NOINIT_BOOLEAN
    #undef EBSTUBS_STOP_SEC_VAR_NOINIT_BOOLEAN
    #undef MEMMAP_ERROR_EBSTUBS
  #else
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to close section EBSTUBS_STOP_SEC_VAR_NOINIT_BOOLEAN without prior opening EBSTUBS_START_SEC_VAR_NOINIT_BOOLEAN.
  #endif
#elif (defined EBSTUBS_START_SEC_VAR_NOINIT_UNSPECIFIED)
  #ifdef MEMMAP_SECTION_OPENED
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to open section EBSTUBS_START_SEC_VAR_NOINIT_UNSPECIFIED within an already open section.
  #else
    #define MEMMAP_SECTION_OPENED
    #define MEMMAP_SECTION_OPENED_START_SEC_VAR_NOINIT_UNSPECIFIED
    #undef EBSTUBS_START_SEC_VAR_NOINIT_UNSPECIFIED
    #undef MEMMAP_ERROR_EBSTUBS
  #endif
#elif (defined EBSTUBS_STOP_SEC_VAR_NOINIT_UNSPECIFIED)
  #if (defined MEMMAP_SECTION_OPENED) && (defined MEMMAP_SECTION_OPENED_START_SEC_VAR_NOINIT_UNSPECIFIED)
    #undef MEMMAP_SECTION_OPENED
    #undef MEMMAP_SECTION_OPENED_START_SEC_VAR_NOINIT_UNSPECIFIED
    #undef EBSTUBS_STOP_SEC_VAR_NOINIT_UNSPECIFIED
    #undef MEMMAP_ERROR_EBSTUBS
  #else
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to close section EBSTUBS_STOP_SEC_VAR_NOINIT_UNSPECIFIED without prior opening EBSTUBS_START_SEC_VAR_NOINIT_UNSPECIFIED.
  #endif
#elif (defined EBSTUBS_START_SEC_VAR_NO_INIT_16)
  #ifdef MEMMAP_SECTION_OPENED
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to open section EBSTUBS_START_SEC_VAR_NO_INIT_16 within an already open section.
  #else
    #define MEMMAP_SECTION_OPENED
    #define MEMMAP_SECTION_OPENED_START_SEC_VAR_NO_INIT_16
    #undef EBSTUBS_START_SEC_VAR_NO_INIT_16
    #undef MEMMAP_ERROR_EBSTUBS
  #endif
#elif (defined EBSTUBS_STOP_SEC_VAR_NO_INIT_16)
  #if (defined MEMMAP_SECTION_OPENED) && (defined MEMMAP_SECTION_OPENED_START_SEC_VAR_NO_INIT_16)
    #undef MEMMAP_SECTION_OPENED
    #undef MEMMAP_SECTION_OPENED_START_SEC_VAR_NO_INIT_16
    #undef EBSTUBS_STOP_SEC_VAR_NO_INIT_16
    #undef MEMMAP_ERROR_EBSTUBS
  #else
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to close section EBSTUBS_STOP_SEC_VAR_NO_INIT_16 without prior opening EBSTUBS_START_SEC_VAR_NO_INIT_16.
  #endif
#elif (defined EBSTUBS_START_SEC_VAR_NO_INIT_32)
  #ifdef MEMMAP_SECTION_OPENED
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to open section EBSTUBS_START_SEC_VAR_NO_INIT_32 within an already open section.
  #else
    #define MEMMAP_SECTION_OPENED
    #define MEMMAP_SECTION_OPENED_START_SEC_VAR_NO_INIT_32
    #undef EBSTUBS_START_SEC_VAR_NO_INIT_32
    #undef MEMMAP_ERROR_EBSTUBS
  #endif
#elif (defined EBSTUBS_STOP_SEC_VAR_NO_INIT_32)
  #if (defined MEMMAP_SECTION_OPENED) && (defined MEMMAP_SECTION_OPENED_START_SEC_VAR_NO_INIT_32)
    #undef MEMMAP_SECTION_OPENED
    #undef MEMMAP_SECTION_OPENED_START_SEC_VAR_NO_INIT_32
    #undef EBSTUBS_STOP_SEC_VAR_NO_INIT_32
    #undef MEMMAP_ERROR_EBSTUBS
  #else
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to close section EBSTUBS_STOP_SEC_VAR_NO_INIT_32 without prior opening EBSTUBS_START_SEC_VAR_NO_INIT_32.
  #endif
#elif (defined EBSTUBS_START_SEC_VAR_NO_INIT_8)
  #ifdef MEMMAP_SECTION_OPENED
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to open section EBSTUBS_START_SEC_VAR_NO_INIT_8 within an already open section.
  #else
    #define MEMMAP_SECTION_OPENED
    #define MEMMAP_SECTION_OPENED_START_SEC_VAR_NO_INIT_8
    #undef EBSTUBS_START_SEC_VAR_NO_INIT_8
    #undef MEMMAP_ERROR_EBSTUBS
  #endif
#elif (defined EBSTUBS_STOP_SEC_VAR_NO_INIT_8)
  #if (defined MEMMAP_SECTION_OPENED) && (defined MEMMAP_SECTION_OPENED_START_SEC_VAR_NO_INIT_8)
    #undef MEMMAP_SECTION_OPENED
    #undef MEMMAP_SECTION_OPENED_START_SEC_VAR_NO_INIT_8
    #undef EBSTUBS_STOP_SEC_VAR_NO_INIT_8
    #undef MEMMAP_ERROR_EBSTUBS
  #else
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to close section EBSTUBS_STOP_SEC_VAR_NO_INIT_8 without prior opening EBSTUBS_START_SEC_VAR_NO_INIT_8.
  #endif
#elif (defined EBSTUBS_START_SEC_VAR_NO_INIT_BOOLEAN)
  #ifdef MEMMAP_SECTION_OPENED
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to open section EBSTUBS_START_SEC_VAR_NO_INIT_BOOLEAN within an already open section.
  #else
    #define MEMMAP_SECTION_OPENED
    #define MEMMAP_SECTION_OPENED_START_SEC_VAR_NO_INIT_BOOLEAN
    #undef EBSTUBS_START_SEC_VAR_NO_INIT_BOOLEAN
    #undef MEMMAP_ERROR_EBSTUBS
  #endif
#elif (defined EBSTUBS_STOP_SEC_VAR_NO_INIT_BOOLEAN)
  #if (defined MEMMAP_SECTION_OPENED) && (defined MEMMAP_SECTION_OPENED_START_SEC_VAR_NO_INIT_BOOLEAN)
    #undef MEMMAP_SECTION_OPENED
    #undef MEMMAP_SECTION_OPENED_START_SEC_VAR_NO_INIT_BOOLEAN
    #undef EBSTUBS_STOP_SEC_VAR_NO_INIT_BOOLEAN
    #undef MEMMAP_ERROR_EBSTUBS
  #else
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to close section EBSTUBS_STOP_SEC_VAR_NO_INIT_BOOLEAN without prior opening EBSTUBS_START_SEC_VAR_NO_INIT_BOOLEAN.
  #endif
#elif (defined EBSTUBS_START_SEC_VAR_NO_INIT_UNSPECIFIED)
  #ifdef MEMMAP_SECTION_OPENED
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to open section EBSTUBS_START_SEC_VAR_NO_INIT_UNSPECIFIED within an already open section.
  #else
    #define MEMMAP_SECTION_OPENED
    #define MEMMAP_SECTION_OPENED_START_SEC_VAR_NO_INIT_UNSPECIFIED
    #undef EBSTUBS_START_SEC_VAR_NO_INIT_UNSPECIFIED
    #undef MEMMAP_ERROR_EBSTUBS
  #endif
#elif (defined EBSTUBS_STOP_SEC_VAR_NO_INIT_UNSPECIFIED)
  #if (defined MEMMAP_SECTION_OPENED) && (defined MEMMAP_SECTION_OPENED_START_SEC_VAR_NO_INIT_UNSPECIFIED)
    #undef MEMMAP_SECTION_OPENED
    #undef MEMMAP_SECTION_OPENED_START_SEC_VAR_NO_INIT_UNSPECIFIED
    #undef EBSTUBS_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
    #undef MEMMAP_ERROR_EBSTUBS
  #else
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to close section EBSTUBS_STOP_SEC_VAR_NO_INIT_UNSPECIFIED without prior opening EBSTUBS_START_SEC_VAR_NO_INIT_UNSPECIFIED.
  #endif
#elif (defined EBSTUBS_START_SEC_VAR_POWER_ON_CLEARED_16)
  #ifdef MEMMAP_SECTION_OPENED
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to open section EBSTUBS_START_SEC_VAR_POWER_ON_CLEARED_16 within an already open section.
  #else
    #define MEMMAP_SECTION_OPENED
    #define MEMMAP_SECTION_OPENED_START_SEC_VAR_POWER_ON_CLEARED_16
    #undef EBSTUBS_START_SEC_VAR_POWER_ON_CLEARED_16
    #undef MEMMAP_ERROR_EBSTUBS
  #endif
#elif (defined EBSTUBS_STOP_SEC_VAR_POWER_ON_CLEARED_16)
  #if (defined MEMMAP_SECTION_OPENED) && (defined MEMMAP_SECTION_OPENED_START_SEC_VAR_POWER_ON_CLEARED_16)
    #undef MEMMAP_SECTION_OPENED
    #undef MEMMAP_SECTION_OPENED_START_SEC_VAR_POWER_ON_CLEARED_16
    #undef EBSTUBS_STOP_SEC_VAR_POWER_ON_CLEARED_16
    #undef MEMMAP_ERROR_EBSTUBS
  #else
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to close section EBSTUBS_STOP_SEC_VAR_POWER_ON_CLEARED_16 without prior opening EBSTUBS_START_SEC_VAR_POWER_ON_CLEARED_16.
  #endif
#elif (defined EBSTUBS_START_SEC_VAR_POWER_ON_CLEARED_32)
  #ifdef MEMMAP_SECTION_OPENED
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to open section EBSTUBS_START_SEC_VAR_POWER_ON_CLEARED_32 within an already open section.
  #else
    #define MEMMAP_SECTION_OPENED
    #define MEMMAP_SECTION_OPENED_START_SEC_VAR_POWER_ON_CLEARED_32
    #undef EBSTUBS_START_SEC_VAR_POWER_ON_CLEARED_32
    #undef MEMMAP_ERROR_EBSTUBS
  #endif
#elif (defined EBSTUBS_STOP_SEC_VAR_POWER_ON_CLEARED_32)
  #if (defined MEMMAP_SECTION_OPENED) && (defined MEMMAP_SECTION_OPENED_START_SEC_VAR_POWER_ON_CLEARED_32)
    #undef MEMMAP_SECTION_OPENED
    #undef MEMMAP_SECTION_OPENED_START_SEC_VAR_POWER_ON_CLEARED_32
    #undef EBSTUBS_STOP_SEC_VAR_POWER_ON_CLEARED_32
    #undef MEMMAP_ERROR_EBSTUBS
  #else
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to close section EBSTUBS_STOP_SEC_VAR_POWER_ON_CLEARED_32 without prior opening EBSTUBS_START_SEC_VAR_POWER_ON_CLEARED_32.
  #endif
#elif (defined EBSTUBS_START_SEC_VAR_POWER_ON_CLEARED_8)
  #ifdef MEMMAP_SECTION_OPENED
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to open section EBSTUBS_START_SEC_VAR_POWER_ON_CLEARED_8 within an already open section.
  #else
    #define MEMMAP_SECTION_OPENED
    #define MEMMAP_SECTION_OPENED_START_SEC_VAR_POWER_ON_CLEARED_8
    #undef EBSTUBS_START_SEC_VAR_POWER_ON_CLEARED_8
    #undef MEMMAP_ERROR_EBSTUBS
  #endif
#elif (defined EBSTUBS_STOP_SEC_VAR_POWER_ON_CLEARED_8)
  #if (defined MEMMAP_SECTION_OPENED) && (defined MEMMAP_SECTION_OPENED_START_SEC_VAR_POWER_ON_CLEARED_8)
    #undef MEMMAP_SECTION_OPENED
    #undef MEMMAP_SECTION_OPENED_START_SEC_VAR_POWER_ON_CLEARED_8
    #undef EBSTUBS_STOP_SEC_VAR_POWER_ON_CLEARED_8
    #undef MEMMAP_ERROR_EBSTUBS
  #else
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to close section EBSTUBS_STOP_SEC_VAR_POWER_ON_CLEARED_8 without prior opening EBSTUBS_START_SEC_VAR_POWER_ON_CLEARED_8.
  #endif
#elif (defined EBSTUBS_START_SEC_VAR_POWER_ON_CLEARED_BOOLEAN)
  #ifdef MEMMAP_SECTION_OPENED
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to open section EBSTUBS_START_SEC_VAR_POWER_ON_CLEARED_BOOLEAN within an already open section.
  #else
    #define MEMMAP_SECTION_OPENED
    #define MEMMAP_SECTION_OPENED_START_SEC_VAR_POWER_ON_CLEARED_BOOLEAN
    #undef EBSTUBS_START_SEC_VAR_POWER_ON_CLEARED_BOOLEAN
    #undef MEMMAP_ERROR_EBSTUBS
  #endif
#elif (defined EBSTUBS_STOP_SEC_VAR_POWER_ON_CLEARED_BOOLEAN)
  #if (defined MEMMAP_SECTION_OPENED) && (defined MEMMAP_SECTION_OPENED_START_SEC_VAR_POWER_ON_CLEARED_BOOLEAN)
    #undef MEMMAP_SECTION_OPENED
    #undef MEMMAP_SECTION_OPENED_START_SEC_VAR_POWER_ON_CLEARED_BOOLEAN
    #undef EBSTUBS_STOP_SEC_VAR_POWER_ON_CLEARED_BOOLEAN
    #undef MEMMAP_ERROR_EBSTUBS
  #else
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to close section EBSTUBS_STOP_SEC_VAR_POWER_ON_CLEARED_BOOLEAN without prior opening EBSTUBS_START_SEC_VAR_POWER_ON_CLEARED_BOOLEAN.
  #endif
#elif (defined EBSTUBS_START_SEC_VAR_POWER_ON_CLEARED_UNSPECIFIED)
  #ifdef MEMMAP_SECTION_OPENED
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to open section EBSTUBS_START_SEC_VAR_POWER_ON_CLEARED_UNSPECIFIED within an already open section.
  #else
    #define MEMMAP_SECTION_OPENED
    #define MEMMAP_SECTION_OPENED_START_SEC_VAR_POWER_ON_CLEARED_UNSPECIFIED
    #undef EBSTUBS_START_SEC_VAR_POWER_ON_CLEARED_UNSPECIFIED
    #undef MEMMAP_ERROR_EBSTUBS
  #endif
#elif (defined EBSTUBS_STOP_SEC_VAR_POWER_ON_CLEARED_UNSPECIFIED)
  #if (defined MEMMAP_SECTION_OPENED) && (defined MEMMAP_SECTION_OPENED_START_SEC_VAR_POWER_ON_CLEARED_UNSPECIFIED)
    #undef MEMMAP_SECTION_OPENED
    #undef MEMMAP_SECTION_OPENED_START_SEC_VAR_POWER_ON_CLEARED_UNSPECIFIED
    #undef EBSTUBS_STOP_SEC_VAR_POWER_ON_CLEARED_UNSPECIFIED
    #undef MEMMAP_ERROR_EBSTUBS
  #else
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to close section EBSTUBS_STOP_SEC_VAR_POWER_ON_CLEARED_UNSPECIFIED without prior opening EBSTUBS_START_SEC_VAR_POWER_ON_CLEARED_UNSPECIFIED.
  #endif
#elif (defined EBSTUBS_START_SEC_VAR_POWER_ON_INIT_16)
  #ifdef MEMMAP_SECTION_OPENED
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to open section EBSTUBS_START_SEC_VAR_POWER_ON_INIT_16 within an already open section.
  #else
    #define MEMMAP_SECTION_OPENED
    #define MEMMAP_SECTION_OPENED_START_SEC_VAR_POWER_ON_INIT_16
    #undef EBSTUBS_START_SEC_VAR_POWER_ON_INIT_16
    #undef MEMMAP_ERROR_EBSTUBS
  #endif
#elif (defined EBSTUBS_STOP_SEC_VAR_POWER_ON_INIT_16)
  #if (defined MEMMAP_SECTION_OPENED) && (defined MEMMAP_SECTION_OPENED_START_SEC_VAR_POWER_ON_INIT_16)
    #undef MEMMAP_SECTION_OPENED
    #undef MEMMAP_SECTION_OPENED_START_SEC_VAR_POWER_ON_INIT_16
    #undef EBSTUBS_STOP_SEC_VAR_POWER_ON_INIT_16
    #undef MEMMAP_ERROR_EBSTUBS
  #else
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to close section EBSTUBS_STOP_SEC_VAR_POWER_ON_INIT_16 without prior opening EBSTUBS_START_SEC_VAR_POWER_ON_INIT_16.
  #endif
#elif (defined EBSTUBS_START_SEC_VAR_POWER_ON_INIT_32)
  #ifdef MEMMAP_SECTION_OPENED
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to open section EBSTUBS_START_SEC_VAR_POWER_ON_INIT_32 within an already open section.
  #else
    #define MEMMAP_SECTION_OPENED
    #define MEMMAP_SECTION_OPENED_START_SEC_VAR_POWER_ON_INIT_32
    #undef EBSTUBS_START_SEC_VAR_POWER_ON_INIT_32
    #undef MEMMAP_ERROR_EBSTUBS
  #endif
#elif (defined EBSTUBS_STOP_SEC_VAR_POWER_ON_INIT_32)
  #if (defined MEMMAP_SECTION_OPENED) && (defined MEMMAP_SECTION_OPENED_START_SEC_VAR_POWER_ON_INIT_32)
    #undef MEMMAP_SECTION_OPENED
    #undef MEMMAP_SECTION_OPENED_START_SEC_VAR_POWER_ON_INIT_32
    #undef EBSTUBS_STOP_SEC_VAR_POWER_ON_INIT_32
    #undef MEMMAP_ERROR_EBSTUBS
  #else
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to close section EBSTUBS_STOP_SEC_VAR_POWER_ON_INIT_32 without prior opening EBSTUBS_START_SEC_VAR_POWER_ON_INIT_32.
  #endif
#elif (defined EBSTUBS_START_SEC_VAR_POWER_ON_INIT_8)
  #ifdef MEMMAP_SECTION_OPENED
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to open section EBSTUBS_START_SEC_VAR_POWER_ON_INIT_8 within an already open section.
  #else
    #define MEMMAP_SECTION_OPENED
    #define MEMMAP_SECTION_OPENED_START_SEC_VAR_POWER_ON_INIT_8
    #undef EBSTUBS_START_SEC_VAR_POWER_ON_INIT_8
    #undef MEMMAP_ERROR_EBSTUBS
  #endif
#elif (defined EBSTUBS_STOP_SEC_VAR_POWER_ON_INIT_8)
  #if (defined MEMMAP_SECTION_OPENED) && (defined MEMMAP_SECTION_OPENED_START_SEC_VAR_POWER_ON_INIT_8)
    #undef MEMMAP_SECTION_OPENED
    #undef MEMMAP_SECTION_OPENED_START_SEC_VAR_POWER_ON_INIT_8
    #undef EBSTUBS_STOP_SEC_VAR_POWER_ON_INIT_8
    #undef MEMMAP_ERROR_EBSTUBS
  #else
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to close section EBSTUBS_STOP_SEC_VAR_POWER_ON_INIT_8 without prior opening EBSTUBS_START_SEC_VAR_POWER_ON_INIT_8.
  #endif
#elif (defined EBSTUBS_START_SEC_VAR_POWER_ON_INIT_BOOLEAN)
  #ifdef MEMMAP_SECTION_OPENED
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to open section EBSTUBS_START_SEC_VAR_POWER_ON_INIT_BOOLEAN within an already open section.
  #else
    #define MEMMAP_SECTION_OPENED
    #define MEMMAP_SECTION_OPENED_START_SEC_VAR_POWER_ON_INIT_BOOLEAN
    #undef EBSTUBS_START_SEC_VAR_POWER_ON_INIT_BOOLEAN
    #undef MEMMAP_ERROR_EBSTUBS
  #endif
#elif (defined EBSTUBS_STOP_SEC_VAR_POWER_ON_INIT_BOOLEAN)
  #if (defined MEMMAP_SECTION_OPENED) && (defined MEMMAP_SECTION_OPENED_START_SEC_VAR_POWER_ON_INIT_BOOLEAN)
    #undef MEMMAP_SECTION_OPENED
    #undef MEMMAP_SECTION_OPENED_START_SEC_VAR_POWER_ON_INIT_BOOLEAN
    #undef EBSTUBS_STOP_SEC_VAR_POWER_ON_INIT_BOOLEAN
    #undef MEMMAP_ERROR_EBSTUBS
  #else
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to close section EBSTUBS_STOP_SEC_VAR_POWER_ON_INIT_BOOLEAN without prior opening EBSTUBS_START_SEC_VAR_POWER_ON_INIT_BOOLEAN.
  #endif
#elif (defined EBSTUBS_START_SEC_VAR_POWER_ON_INIT_UNSPECIFIED)
  #ifdef MEMMAP_SECTION_OPENED
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to open section EBSTUBS_START_SEC_VAR_POWER_ON_INIT_UNSPECIFIED within an already open section.
  #else
    #define MEMMAP_SECTION_OPENED
    #define MEMMAP_SECTION_OPENED_START_SEC_VAR_POWER_ON_INIT_UNSPECIFIED
    #undef EBSTUBS_START_SEC_VAR_POWER_ON_INIT_UNSPECIFIED
    #undef MEMMAP_ERROR_EBSTUBS
  #endif
#elif (defined EBSTUBS_STOP_SEC_VAR_POWER_ON_INIT_UNSPECIFIED)
  #if (defined MEMMAP_SECTION_OPENED) && (defined MEMMAP_SECTION_OPENED_START_SEC_VAR_POWER_ON_INIT_UNSPECIFIED)
    #undef MEMMAP_SECTION_OPENED
    #undef MEMMAP_SECTION_OPENED_START_SEC_VAR_POWER_ON_INIT_UNSPECIFIED
    #undef EBSTUBS_STOP_SEC_VAR_POWER_ON_INIT_UNSPECIFIED
    #undef MEMMAP_ERROR_EBSTUBS
  #else
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to close section EBSTUBS_STOP_SEC_VAR_POWER_ON_INIT_UNSPECIFIED without prior opening EBSTUBS_START_SEC_VAR_POWER_ON_INIT_UNSPECIFIED.
  #endif
#elif (defined EBSTUBS_START_SEC_VAR_UNSPECIFIED)
  #ifdef MEMMAP_SECTION_OPENED
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to open section EBSTUBS_START_SEC_VAR_UNSPECIFIED within an already open section.
  #else
    #define MEMMAP_SECTION_OPENED
    #define MEMMAP_SECTION_OPENED_START_SEC_VAR_UNSPECIFIED
    #undef EBSTUBS_START_SEC_VAR_UNSPECIFIED
    #undef MEMMAP_ERROR_EBSTUBS
  #endif
#elif (defined EBSTUBS_STOP_SEC_VAR_UNSPECIFIED)
  #if (defined MEMMAP_SECTION_OPENED) && (defined MEMMAP_SECTION_OPENED_START_SEC_VAR_UNSPECIFIED)
    #undef MEMMAP_SECTION_OPENED
    #undef MEMMAP_SECTION_OPENED_START_SEC_VAR_UNSPECIFIED
    #undef EBSTUBS_STOP_SEC_VAR_UNSPECIFIED
    #undef MEMMAP_ERROR_EBSTUBS
  #else
    #undef MEMMAP_ERROR_EBSTUBS
    #error Tried to close section EBSTUBS_STOP_SEC_VAR_UNSPECIFIED without prior opening EBSTUBS_START_SEC_VAR_UNSPECIFIED.
  #endif
#endif
#if ((!defined MEMMAP_ERROR_EBSTUBS) && (defined MEMMAP_ERROR))
  #undef MEMMAP_ERROR
#elif ((defined MEMMAP_ERROR_EBSTUBS) && (!defined MEMMAP_ERROR))
  #undef MEMMAP_ERROR_EBSTUBS
  #error MEMMAP_ERROR_EBSTUBS the included memory section was not static defined within EB Stubs.
#endif

/******************************************************************************
DECLARATION OF VARIABLES
******************************************************************************/

/******************************************************************************
DECLARATION OF CONSTANT DATA
******************************************************************************/

/******************************************************************************
DECLARATION OF FUNCTIONS
******************************************************************************/
/******************************************************************************
DECLARATION OF FUNCTION-LIKE MACROS
******************************************************************************/
#ifdef __cplusplus
}
#endif
/******************************************************************************
End Of File
*****************************************************************************/
