IF "%TARGET%"=="" SET TARGET=CORTEXM
IF "%DERIVATE%"=="" SET DERIVATE=S32K14X
IF "%TOOLCHAIN%"=="" SET TOOLCHAIN=iar
IF [%TOOLPATH_COMPILER%]==[] SET TOOLPATH_COMPILER=D:\tools\IAR_Systems\Embedded_Workbench_8.3
IF [%TRESOS_BASE%]==[] SET TRESOS_BASE=D:\VW_S32\after_nvm_arxml_changes\VW_S32\tresos
IF [%PLUGINS_BASE%]==[] set PLUGINS_BASE=%TRESOS_BASE%\plugins
