


#path to tresos include forlder
tresos_gen_include: "s:/Components/Application/Supplier/Tresos_Configuration_8.8.7/Workspace/Application/Tresos_BSW_generated/include"

# path to tresos src folder
tresos_gen_src: "s:/Components/Application/Supplier/Tresos_Configuration_8.8.7/Workspace/Application/Tresos_BSW_generated/src"

#path to tresos xgen folder
tresos_gen_xgen: "s:/Components/Application/Supplier/Tresos_Configuration_8.8.7/Workspace/Application/Tresos_BSW_generated/xgen"
