/**************************************************************************************************\
 *** 
 *** Simulink model       : eCS_Algo_Simulation_2015b_opti
 *** TargetLink subsystem : eCS_Algo_Simulation_2015b_opti/SAD
 *** Codefile             : SAD.c
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2022-09-06 10:18:41
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : AUTOSAR
 *** AUTOSAR version                          : 4.2.2
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : enabled
 *** Logging mode                             : Do not log anything
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Loop unroll threshold                    : 5
 *** Shift mode                               : automatic
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : 31 chars
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : enabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 6
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\Program Files\dSPACE TargetLink 4.2\Matlab\Tl\Con
 ***                                            fig\codegen\cconfig.xml
 *** Root style sheet                         : C:\Program Files\dSPACE TargetLink 4.2\Matlab\Tl\XML
 ***                                            \CodeGen\Stylesheets\TL_CSourceCodeSS.xsl
 ***
 *** SUBSYS                   CORRESPONDING SIMULINK SUBSYSTEM
 *** Sc1                      SAD
 *** Sc2                      SAD/SAD
 *** Sc3                      SAD/SAD/SAD_Init
 *** Sc4                      SAD/SAD/SAD_runMainFunction
 *** Sc5                      SAD/SAD/SAD_runMainFunction/SAD mainfunction
 *** Sc6                      SAD/SAD/SAD_runMainFunction/SAD mainfunction/ComputeDutyCycle
 *** Sc7                      SAD/SAD/SAD_runMainFunction/SAD mainfunction/Contatenate 6 bus inputs 
 ***                          to bitfield
 *** Sb1                      SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_111 step1
 *** Sc8                      SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112
 *** Sc9                      SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecut
 ***                          ion
 *** Sc1                      SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ManageEndingStep
 *** Sc10                     SAD/SAD/SAD_runMainFunction/SAD mainfunction/ComputeDutyCycle/LockRequ
 ***                          est
 *** Sc11                     SAD/SAD/SAD_runMainFunction/SAD mainfunction/ComputeDutyCycle/UnlockRe
 ***                          quest
 *** Sc12                     SAD/SAD/SAD_runMainFunction/SAD mainfunction/ComputeDutyCycle/LockRequ
 ***                          est/Disable PWM
 *** Sc13                     SAD/SAD/SAD_runMainFunction/SAD mainfunction/ComputeDutyCycle/UnlockRe
 ***                          quest/Current
 *** Sc14                     SAD/SAD/SAD_runMainFunction/SAD mainfunction/ComputeDutyCycle/UnlockRe
 ***                          quest/Default no profile
 *** Sc15                     SAD/SAD/SAD_runMainFunction/SAD mainfunction/ComputeDutyCycle/UnlockRe
 ***                          quest/Disable PWM
 *** Sc16                     SAD/SAD/SAD_runMainFunction/SAD mainfunction/ComputeDutyCycle/UnlockRe
 ***                          quest/Enable PWM
 *** Sc17                     SAD/SAD/SAD_runMainFunction/SAD mainfunction/ComputeDutyCycle/UnlockRe
 ***                          quest/PWM
 *** Sc18                     SAD/SAD/SAD_runMainFunction/SAD mainfunction/ComputeDutyCycle/UnlockRe
 ***                          quest/scp_GetCurrent
 *** Sb2                      SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_111 step1/No Step to
 ***                           play
 *** Sb3                      SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_111 step1/Select Ste
 ***                          p To Execute
 *** Sb4                      SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_111 step1/Select Ste
 ***                          p To Execute/Continue Step execution
 *** Sb5                      SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_111 step1/Select Ste
 ***                          p To Execute/Filter StepId to Execute
 *** Sb6                      SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_111 step1/Select Ste
 ***                          p To Execute/Increment Step Index
 *** Sb7                      SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_111 step1/Select Ste
 ***                          p To Execute/Init Step Id
 *** Sc19                     SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Invalid Range fo
 ***                          r inputs
 *** Sc20                     SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Preliminary Chec
 ***                          ks for Step Parameters Content
 *** Sc21                     SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Preliminary Chec
 ***                          ks for Step Parameters Content/Manage Step Parameters
 *** Sc22                     SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Preliminary Chec
 *** ks for Step Parameters Content/Manage Step Parameters/ExtractParameter
 ***                          s
 *** Sc23                     SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Preliminary Chec
 *** ks for Step Parameters Content/Manage Step Parameters/KeepPreviousValu
 ***                          es
 *** Sc24                     SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Preliminary Chec
 *** ks for Step Parameters Content/Manage Step Parameters/ExtractParameter
 ***                          s/8Bit Decoder
 *** Sc25                     SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Preliminary Chec
 *** ks for Step Parameters Content/Manage Step Parameters/ExtractParameter
 ***                          s/Subsystem6
 *** Sc26                     SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecut
 ***                          ion/ManageTimer
 *** Sc27                     SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecut
 ***                          ion/New Step started
 *** Sc28                     SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecut
 ***                          ion/No step executed
 *** Sc29                     SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecut
 ***                          ion/Step execution continues
 *** Sc30                     SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecut
 ***                          ion/New Step started/Adapt Step Target Value
 *** Sc31                     SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecut
 ***                          ion/New Step started/AdaptOrderType
 *** Sc32                     SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecut
 ***                          ion/New Step started/Ramp step characteristics computation
 *** Sc33                     SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecut
 ***                          ion/New Step started/AdaptOrderType/If ActionSubsystem1
 *** Sc34                     SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecut
 ***                          ion/New Step started/AdaptOrderType/If ActionSubsystem2
 *** 
 *** SUBSYS                   CORRESPONDING MODEL BLOCK (REFERENCED MODEL)
 *** 
 *** SF-NODE   CORRESPONDING STATEFLOW NODE                           DESCRIPTION
 *** 
 *** TargetLink version      : 4.2 from 14-Oct-2016
 *** Code generator version  : Build Id 4.2.0.26 from 2016-10-17 16:31:48

\**************************************************************************************************/

#ifndef SAD_C
#define SAD_C

/*----------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------*/

#include "udt_c.h"
#include "S:\Components\Application\Supplier\Tresos_Configuration_8.5.1\Workspace\Application\Tresos_BSW_generated\include\Rte_FSM_Type.h\
"
#include "SAD_Config.h"
#include "SAD_ARfrm.h"
#include "SAD.h"
#include "Rte_SAD.h"
#include "dsfxp.h"
#include "Common.h"

/*----------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------*/
/******************************************************************************\
   MERGEABLE_GLOBAL: mergeable global variables (RAM) | Width: 16
\******************************************************************************/
uint16 u16StepByte0;
uint16 u16StepBytePosition;

/******************************************************************************\
   SLGlobalInit: Default storage class for global variables with initial value | Width: 16
\******************************************************************************/
uint16 Sc6_Data_Store_Memory[6] = 
{
   /* [0..5] */ 0, 0, 0, 0, 0, 0
   /* 0., 0., 0., 0., 0., 0. */
};

/******************************************************************************\
   SLStaticGlobal: Default storage class for global static variables | Width: 16
\******************************************************************************/
static uint16 IF_Sc9_u16CurrentTime;
static uint16 Sc5_u8SelectedProfile;

/******************************************************************************\
   SLStaticGlobal: Default storage class for global static variables | Width: 8
\******************************************************************************/
static uint8 IF_Sb1_u8StepIdx;
static boolean IF_Sc1_b_IsStepFinished;
static uint8 Sc5_Switch;
static boolean bIsTimerElapsed;

/******************************************************************************\
   SLStaticGlobal: Default storage class for global static variables | Width: N.A.
\******************************************************************************/
static stStepParam stStep = {
   0, /* u16Duration */
   0, /* u8Order */
   0, /* u8Consign */
   0, /* b8IsRamp */
   0 /* b8IsPID */
};

/******************************************************************************\
   SLStaticGlobalInit: Default storage class for global static variables with initial value | Width:
    16
\******************************************************************************/
static uint16 IF_Sc8_u16StepDuration = 0;
static uint16 Sc9_Consign = 0;
static sint16 s32RawIncrementValue = 0;
static sint16 X_Sc5_u8PrevSelectedProfile = 0;
static uint16 u16PrevTime = 0;

/******************************************************************************\
   SLStaticGlobalInit: Default storage class for global static variables with initial value | Width:
    8
\******************************************************************************/
static uint8 Sc9_orderOut = 0;
static uint8 eStepValidity = 0;
static uint8 u8StepToExecute = 255; /* Variable to store the Step Id that will be executed.
Range : [0 ; 7 ] U {255} */
static uint8 X_Sc5_u8PrevStepToExecute = 0;
static boolean b8PrevIsStepFinished = 0;
static uint8 u8PrevStepIdx = 0;

/*----------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------*/

/******************************************************************************\
   STATIC_FCN: static function(s) (invisible for other module)
\******************************************************************************/
static void M_ControlStepExecution(void);

static void M_ManageStepEvents(void);

static void M_SelectStepId(void);

static void M_StepPreprocessing(void);

/*----------------------------------------------------------------------------*\
  INLINE FUNCTIONS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------*/

/**************************************************************************************************\
 ***  FUNCTION:
 ***      SAD
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
void SAD(void)
{
   /* call of function: SAD/SAD/SAD_runMainFunction */
   Task_SAD_runMa__unction_Wrapper();

   /* call of function: SAD/SAD/SAD_Init */
   Task_SAD_Init_Wrapper();
}

/**************************************************************************************************\
 ***  FUNCTION:
 ***      SAD_Init
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
#define SAD_START_SEC_CODE
#include "SAD_MemMap.h"

FUNC(void, SAD_CODE) SAD_Init(void)
{
   /* # combined # BusOutport: SAD/SAD/SAD_Init/EN_Boost_2
      # combined # BusOutport: SAD/SAD/SAD_Init/EN_Boost_2 */
   Rte_Call_pclDioIfServices_WriteChannel(DIOIF_CH_EN_BOOST_2, DIOIF_STD_HIGH);

   /* # combined # BusOutport: SAD/SAD/SAD_Init/EN_Boost_1
      # combined # BusOutport: SAD/SAD/SAD_Init/EN_Boost_1 */
   Rte_Call_pclDioIfServices_WriteChannel(DIOIF_CH_EN_BOOST, DIOIF_STD_HIGH);
}

#define SAD_STOP_SEC_CODE
#include "SAD_MemMap.h"

/**************************************************************************************************\
 ***  FUNCTION:
 ***      SAD_runMainFunction
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
#define SAD_START_SEC_CODE
#include "SAD_MemMap.h"

FUNC(void, SAD_CODE) SAD_runMainFunction(void)
{
   /* SLLocal: Default storage class for local variables | Width: 16 */
   uint16 au16Current[6];

   /* SLLocal: Default storage class for local variables | Width: 8 */
   sint8 Aux_S8;
   sint8 Aux_S8_a;
   sint8 Sc6_For_Iterator_it;
   sint8 Sc7_For_Iterator_it;
   uint8 Sc7_Switch;
   uint8 Sc7_Switch1;
   uint8 au8SelectedProfile_a[6];

   /* SLLocal: Default storage class for local variables | Width: 32 */
   sint32 Aux_S32;

   /* SLLocalInit: Default storage class for local variables with init value | Width: 16 */
   uint16 Sc6_Merge;

   /* SLStaticLocalInit: Default storage class for static local variables with initvalue | Width: 32
    */
   static sint32 as32Integral[6] = 
   {
      /* [0..5] */ 0, 0, 0, 0, 0, 0
      /* 0., 0., 0., 0., 0., 0. */
   }; /* 
      LSB: 2^-2 OFF: 0 MIN/MAX: -536870912 .. 536870911.75
      Description: Resolution:  2^-15 */

   /* SLStaticLocalInit: Default storage class for static local variables with initvalue | Width: 16
    */
   static uint16 DD_Sc6_PWM[6] = 
   {
      /* [0..5] */ 0, 0, 0, 0, 0, 0
      /* 0., 0., 0., 0., 0., 0. */
   }; /* 
      LSB: 2^0 OFF: 0, different constrained ranges
      Description: Resolution:  2^-15 */
   static uint16 au16DutyCycle[6] = 
   {
      /* [0..5] */ 0, 0, 0, 0, 0, 0
      /* 0., 0., 0., 0., 0., 0. */
   }; /* 
      LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 32768
      Description: Resolution:  2^-15 */

   /* SLStaticLocalInit: Default storage class for static local variables with initvalue | Width: 32
    */
   static sint32 as32PrevIntegral[6] = 
   {
      /* [0..5] */ 0, 0, 0, 0, 0, 0
      /* 0., 0., 0., 0., 0., 0. */
   }; /* 
      LSB: 2^-2 OFF: 0 MIN/MAX: -536870912 .. 536870911.75
      Description: Resolution:  2^-15 */

   /* SLStaticLocalInit: Default storage class for static local variables with initvalue | Width: 16
    */
   static uint16 au16PrevDutyCycle[6] = 
   {
      /* [0..5] */ 0, 0, 0, 0, 0, 0
      /* 0., 0., 0., 0., 0., 0. */
   }; /* 
      LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 32768
      Description: Resolution:  2^-15 */
   static sint16 s16PrevSlope = 0; /* 
      LSB: 2^0 OFF: 0 MIN/MAX: -32768 .. 32767
      Description: Resolution:  2^-15 */
   static uint16 u16PrevRawOrder = 0; /* 
      LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 32768
      Description: Resolution:  2^-15 */

   /* SLStaticLocalInit: Default storage class for static local variables with initvalue | Width: 8
    */
   static uint8 X_Sc7_Unit_Delay = 0;

   /* TargetLink inport: SAD/SAD/SAD_runMainFunction/drparg_au8SelectedProfile */
   Rte_Read_prrFsmProfile_au8SelectedProfile(au8SelectedProfile_a);

   /* TargetLink inport: SAD/SAD/SAD_runMainFunction/SAD mainfunction/sim_au16Current */
   Rte_Read_prrSolenoidCurrent_au16Current(au16Current);
   Aux_S8_a = (sint8) (KU8_SOLENOID_NB - 1);
   for (Sc7_For_Iterator_it = 0; Sc7_For_Iterator_it <= Aux_S8_a; Sc7_For_Iterator_it++)
   {
      /* Switch: SAD/SAD/SAD_runMainFunction/SAD mainfunction/Contatenate 6 bus inputs to bitfield/S
         witch1 */
      if (Sc7_For_Iterator_it != 0) {
         /* Switch: SAD/SAD/SAD_runMainFunction/SAD mainfunction/Contatenate 6 bus inputs to bitfiel
            d/Switch1 */
         Sc7_Switch1 = X_Sc7_Unit_Delay;
      }
      else {
         /* Switch: SAD/SAD/SAD_runMainFunction/SAD mainfunction/Contatenate 6 bus inputs to bitfiel
            d/Switch1 */
         Sc7_Switch1 = KU8_ZERO;
      }

      /* Switch: SAD/SAD/SAD_runMainFunction/SAD mainfunction/Contatenate 6 bus inputs to bitfield/S
         witch
         # combined # Selector: SAD/SAD/SAD_runMainFunction/SAD mainfunction/Contatenate 6 bus input
         s to bitfield/u8SelectedProfile */
      if (au8SelectedProfile_a[Sc7_For_Iterator_it] != 0) {
         /* Switch: SAD/SAD/SAD_runMainFunction/SAD mainfunction/Contatenate 6 bus inputs to bitfiel
            d/Switch */
         Sc7_Switch = Sc7_Switch1;
      }
      else {
         /* Switch: SAD/SAD/SAD_runMainFunction/SAD mainfunction/Contatenate 6 bus inputs to bitfiel
            d/Switch
            # combined # SAD/SAD/SAD_runMainFunction/SAD mainfunction/Contatenate 6 bus inputs to bi
            tfield/bitfield_UnlockProfile */
         Sc7_Switch = KU8_ONE << Sc7_For_Iterator_it;
      }

      /* SAD/SAD/SAD_runMainFunction/SAD mainfunction/Contatenate 6 bus inputs to bitfield/Bitwise O
         perator
         # combined # Unit delay: SAD/SAD/SAD_runMainFunction/SAD mainfunction/Contatenate 6 bus inp
         uts to bitfield/Unit Delay */
      X_Sc7_Unit_Delay = (uint8) (Sc7_Switch1 | Sc7_Switch);
   }

   /* Switch: SAD/SAD/SAD_runMainFunction/SAD mainfunction/Switch
      # combined # Unit delay: SAD/SAD/SAD_runMainFunction/SAD mainfunction/Contatenate 6 bus inputs
       to bitfield/Unit Delay */
   if (X_Sc7_Unit_Delay != 0) {
      /* Switch: SAD/SAD/SAD_runMainFunction/SAD mainfunction/Switch */
      Sc5_Switch = KU8_UNLOCK_PROFILE;
   }
   else {
      /* Switch: SAD/SAD/SAD_runMainFunction/SAD mainfunction/Switch */
      Sc5_Switch = KU8_NO_PROFILE;
   }

   /* call of function: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_111 step1 */
   M_SelectStepId();

   /* call of function: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112 */
   M_StepPreprocessing();

   /* Selector: SAD/SAD/SAD_runMainFunction/SAD mainfunction/u8SelectedProfile */
   Sc5_u8SelectedProfile = au16PrevDutyCycle[0];

   /* call of function: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecution */
   M_ControlStepExecution();
   Aux_S8 = (sint8) (KU8_SOLENOID_NB - 1);
   for (Sc6_For_Iterator_it = 0; Sc6_For_Iterator_it <= Aux_S8; Sc6_For_Iterator_it++)
   {
      /* # combined # Relational: SAD/SAD/SAD_runMainFunction/SAD mainfunction/ComputeDutyCycle/Rela
         tional Operator1
         # combined # Selector: SAD/SAD/SAD_runMainFunction/SAD mainfunction/ComputeDutyCycle/u8Sele
         ctedProfile */
      if (au8SelectedProfile_a[Sc6_For_Iterator_it] == KU8_NO_PROFILE) {
         /* Reference of merge block: Merge1 SAD/SAD/SAD_runMainFunction/SAD mainfunction/ComputeDut
            yCycle/Merge1
            update of variable(s) associated with SAD/SAD/SAD_runMainFunction/SAD mainfunction/Compu
            teDutyCycle/LockRequest/Constant1
            # combined # Assignment: SAD/SAD/SAD_runMainFunction/SAD mainfunction/ComputeDutyCycle/I
            ntegral - output calculation */
         as32Integral[Sc6_For_Iterator_it] = 0;

         /* Reference of merge block: Merge SAD/SAD/SAD_runMainFunction/SAD mainfunction/ComputeDuty
            Cycle/Merge
            update of variable(s) associated with SAD/SAD/SAD_runMainFunction/SAD mainfunction/Compu
            teDutyCycle/LockRequest/Constant */
         Sc6_Merge = KU16_ZERO;

         /* # combined # BusOutport: SAD/SAD/SAD_runMainFunction/SAD mainfunction/ComputeDutyCycle/L
            ockRequest/Disable PWM/scp_WriteChannel
            # combined # BusOutport: SAD/SAD/SAD_runMainFunction/SAD mainfunction/ComputeDutyCycle/L
            ockRequest/Disable PWM/scp_WriteChannel */
         Rte_Call_pclDioIfServices_WriteChannel((uint8) Sc6_For_Iterator_it, KU8_ZERO);
      }
      else {
         /* SLLocal: Default storage class for local variables | Width: 16 */
         u16SolenoidCurrentType u16Current_a;

         /* SLLocalInit: Default storage class for local variables with init value | Width: 8 */
         uint8 Sc11_IsPwmEnable;

         /* call of function: SAD/SAD/SAD_runMainFunction/SAD mainfunction/ComputeDutyCycle/UnlockRe
            quest/scp_GetCurrent
            # combined # update(s) for inport SAD/SAD/SAD_runMainFunction/SAD mainfunction/ComputeDu
            tyCycle/UnlockRequest/scp_GetCurrent/u8SolenoidId */
         Rte_Call_pclSolenoidCurrent_GetCurrent((uint8) Sc6_For_Iterator_it, &u16Current_a);

         /* SwitchCase: SAD/SAD/SAD_runMainFunction/SAD mainfunction/ComputeDutyCycle/UnlockRequest/
            Switch Case */
         switch (Sc9_orderOut) {
            case 1: {
               /* SLLocal: Default storage class for local variables | Width: 32 */
               sint32 Sc13_Integral; /* LSB: 2^-2 OFF: 0 MIN/MAX: -536870912 .. 536870911.75 */
               sint32 Sc13_IntegralReset; /* LSB: 2^-2 OFF: 0 MIN/MAX: -536870912 .. 536870911.75 */
               sint32 Sc13_PI; /* LSB: 2^-2 OFF: 0 MIN/MAX: -536870912 .. 536870911.75 */

               /* SLLocal: Default storage class for local variables | Width: 16 */
               sint16 Sc13_error; /* LSB: 2^0 OFF: 0 MIN/MAX: -500 .. 500 */

               /* Sum: SAD/SAD/SAD_runMainFunction/SAD mainfunction/ComputeDutyCycle/UnlockRequest/C
                  urrent/error */
               Sc13_error = (sint16) (u16PrevRawOrder - u16Current_a);

               /* Switch: SAD/SAD/SAD_runMainFunction/SAD mainfunction/ComputeDutyCycle/UnlockReques
                  t/Current/IntegralReset
                  SAD/SAD/SAD_runMainFunction/SAD mainfunction/ComputeDutyCycle/UnlockRequest/Curren
                  t/IntegralReset: Omitted comparison with constant.
                  # combined # Relational: SAD/SAD/SAD_runMainFunction/SAD mainfunction/ComputeDutyC
                  ycle/UnlockRequest/Current/Relational Operator */
               if (Sc13_error > 100) {
                  /* Switch: SAD/SAD/SAD_runMainFunction/SAD mainfunction/ComputeDutyCycle/UnlockReq
                     uest/Current/IntegralReset */
                  Sc13_IntegralReset = KS32_ZERO_SC;
               }
               else {
                  /* Switch: SAD/SAD/SAD_runMainFunction/SAD mainfunction/ComputeDutyCycle/UnlockReq
                     uest/Current/IntegralReset
                     # combined # Selector: SAD/SAD/SAD_runMainFunction/SAD mainfunction/ComputeDuty
                     Cycle/PrevIntegral */
                  Sc13_IntegralReset = as32PrevIntegral[Sc6_For_Iterator_it];
               }

               /* Sum: SAD/SAD/SAD_runMainFunction/SAD mainfunction/ComputeDutyCycle/UnlockRequest/C
                  urrent/Integral
                  # combined # Gain: SAD/SAD/SAD_runMainFunction/SAD mainfunction/ComputeDutyCycle/U
                  nlockRequest/Current/Ki */
               Sc13_Integral = (((sint32) Sc13_error) * ((sint32) NVP_u16Ki)) + Sc13_IntegralReset;

               /* Reference of merge block: Merge1 SAD/SAD/SAD_runMainFunction/SAD mainfunction/Comp
                  uteDutyCycle/Merge1
                  update of variable(s) associated with SAD/SAD/SAD_runMainFunction/SAD mainfunction
                  /ComputeDutyCycle/UnlockRequest/Current/Saturation1
                  # combined # Assignment: SAD/SAD/SAD_runMainFunction/SAD mainfunction/ComputeDutyC
                  ycle/Integral - output calculation
                  # combined # Saturation: SAD/SAD/SAD_runMainFunction/SAD mainfunction/ComputeDutyC
                  ycle/UnlockRequest/Current/Saturation1 */
               as32Integral[Sc6_For_Iterator_it] = C__I32SATI32_SATb(Sc13_Integral, 56000 /* 14000. */
               , 0);

               /* Reference of merge block: IsPwmEnable SAD/SAD/SAD_runMainFunction/SAD mainfunction
                  /ComputeDutyCycle/UnlockRequest/IsPwmEnable
                  update of variable(s) associated with SAD/SAD/SAD_runMainFunction/SAD mainfunction
                  /ComputeDutyCycle/UnlockRequest/Current/Constant */
               Sc11_IsPwmEnable = KU8_ONE;

               /* Sum: SAD/SAD/SAD_runMainFunction/SAD mainfunction/ComputeDutyCycle/UnlockRequest/C
                  urrent/PI
                  # combined # Gain: SAD/SAD/SAD_runMainFunction/SAD mainfunction/ComputeDutyCycle/U
                  nlockRequest/Current/Kp */
               Sc13_PI = (((sint32) Sc13_error) * ((sint32) NVP_u16Kp)) + Sc13_Integral;

               /* Reference of merge block: Merge SAD/SAD/SAD_runMainFunction/SAD mainfunction/Compu
                  teDutyCycle/Merge
                  update of variable(s) associated with SAD/SAD/SAD_runMainFunction/SAD mainfunction
                  /ComputeDutyCycle/UnlockRequest/Current/Product
                  # combined # Product: SAD/SAD/SAD_runMainFunction/SAD mainfunction/ComputeDutyCycl
                  e/UnlockRequest/Current/Product
                  # combined # Product: SAD/SAD/SAD_runMainFunction/SAD mainfunction/ComputeDutyCycl
                  e/UnlockRequest/Current/Product1
                  # combined # Saturation: SAD/SAD/SAD_runMainFunction/SAD mainfunction/ComputeDutyC
                  ycle/UnlockRequest/Current/Saturation */
               Sc6_Merge = (uint16) ((((uint32) KU16_MAX_PWM) * ((uint32) C__U16SATI32_SATb(Sc13_PI,
                 56000 /* 14000. */, 0))) / 55999);
               break;
            }
            case 2: {
               /* Reference of merge block: IsPwmEnable SAD/SAD/SAD_runMainFunction/SAD mainfunction
                  /ComputeDutyCycle/UnlockRequest/IsPwmEnable
                  update of variable(s) associated with SAD/SAD/SAD_runMainFunction/SAD mainfunction
                  /ComputeDutyCycle/UnlockRequest/PWM/Constant */
               Sc11_IsPwmEnable = KU8_ONE;

               /* Switch: SAD/SAD/SAD_runMainFunction/SAD mainfunction/ComputeDutyCycle/UnlockReques
                  t/PWM/Ramp */
               if (s16PrevSlope != 0) {
                  /* Switch: SAD/SAD/SAD_runMainFunction/SAD mainfunction/ComputeDutyCycle/UnlockReq
                     uest/PWM/Ramp
                     # combined # Reference of merge block: Merge SAD/SAD/SAD_runMainFunction/SAD ma
                     infunction/ComputeDutyCycle/Merge
                     update of variable(s) associated with SAD/SAD/SAD_runMainFunction/SAD mainfunct
                     ion/ComputeDutyCycle/UnlockRequest/PWM/Ramp
                     # combined # Sum: SAD/SAD/SAD_runMainFunction/SAD mainfunction/ComputeDutyCycle
                     /UnlockRequest/PWM/Sum
                     # combined # Selector: SAD/SAD/SAD_runMainFunction/SAD mainfunction/ComputeDuty
                     Cycle/OldPWM */
                  Sc6_Merge = (uint16) (au16PrevDutyCycle[Sc6_For_Iterator_it] + ((uint16)
                   s16PrevSlope));
               }
               else {
                  /* Switch: SAD/SAD/SAD_runMainFunction/SAD mainfunction/ComputeDutyCycle/UnlockReq
                     uest/PWM/Ramp
                     # combined # Reference of merge block: Merge SAD/SAD/SAD_runMainFunction/SAD ma
                     infunction/ComputeDutyCycle/Merge
                     update of variable(s) associated with SAD/SAD/SAD_runMainFunction/SAD mainfunct
                     ion/ComputeDutyCycle/UnlockRequest/PWM/Ramp */
                  Sc6_Merge = u16PrevRawOrder;
               }
               break;
            }
            default: {
               /* Reference of merge block: IsPwmEnable SAD/SAD/SAD_runMainFunction/SAD mainfunction
                  /ComputeDutyCycle/UnlockRequest/IsPwmEnable
                  update of variable(s) associated with SAD/SAD/SAD_runMainFunction/SAD mainfunction
                  /ComputeDutyCycle/UnlockRequest/Default no profile/Constant1 */
               Sc11_IsPwmEnable = KU8_ZERO;

               /* Reference of merge block: Merge SAD/SAD/SAD_runMainFunction/SAD mainfunction/Compu
                  teDutyCycle/Merge
                  update of variable(s) associated with SAD/SAD/SAD_runMainFunction/SAD mainfunction
                  /ComputeDutyCycle/UnlockRequest/Default no profile/Constant */
               Sc6_Merge = KU16_ZERO;
               break;
            }
         }
         if (Sc11_IsPwmEnable) {
            /* # combined # BusOutport: SAD/SAD/SAD_runMainFunction/SAD mainfunction/ComputeDutyCycl
               e/UnlockRequest/Enable PWM/scp_WriteChannel
               # combined # BusOutport: SAD/SAD/SAD_runMainFunction/SAD mainfunction/ComputeDutyCycl
               e/UnlockRequest/Enable PWM/scp_WriteChannel */
            Rte_Call_pclDioIfServices_WriteChannel((uint8) Sc6_For_Iterator_it, KU8_ONE);
         }
         else {
            /* # combined # BusOutport: SAD/SAD/SAD_runMainFunction/SAD mainfunction/ComputeDutyCycl
               e/UnlockRequest/Disable PWM/scp_WriteChannel
               # combined # BusOutport: SAD/SAD/SAD_runMainFunction/SAD mainfunction/ComputeDutyCycl
               e/UnlockRequest/Disable PWM/scp_WriteChannel */
            Rte_Call_pclDioIfServices_WriteChannel((uint8) Sc6_For_Iterator_it, KU8_ZERO);
         }
      }

      /* Assignment: SAD/SAD/SAD_runMainFunction/SAD mainfunction/ComputeDutyCycle/stepDutyCycle - o
         utput calculation */
      au16DutyCycle[Sc6_For_Iterator_it] = Sc6_Merge;

      /* Assignment: SAD/SAD/SAD_runMainFunction/SAD mainfunction/ComputeDutyCycle/PWM - output calc
         ulation */
      DD_Sc6_PWM[Sc6_For_Iterator_it] = Sc6_Merge;

      /* # combined # TargetLink outport: SAD/SAD/SAD_runMainFunction/SAD mainfunction/ComputeDutyCy
         cle/sim_au16PWM */
      Rte_Write_sim_psrSolenoidPWM_au16Pwm((const uint16 *) DD_Sc6_PWM);

      /* # combined # BusOutport: SAD/SAD/SAD_runMainFunction/SAD mainfunction/ComputeDutyCycle/scp_
         SetDutyCycle
         # combined # BusOutport: SAD/SAD/SAD_runMainFunction/SAD mainfunction/ComputeDutyCycle/scp_
         SetDutyCycle */
      Rte_Call_pclPwmServices_SetDutyCycle((uint8) Sc6_For_Iterator_it, Sc6_Merge);
      for (Aux_S32 = 0; Aux_S32 < 6; Aux_S32++)
      {
         /* Data store write: SAD/SAD/SAD_runMainFunction/SAD mainfunction/ComputeDutyCycle/Data Sto
            re Write */
         Sc6_Data_Store_Memory[Aux_S32] = au16Current[Aux_S32];
      }
   }

   /* call of function: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ManageEndingStep */
   M_ManageStepEvents();

   /* Unit delay: SAD/SAD/SAD_runMainFunction/SAD mainfunction/u8PrevStepToExecute */
   X_Sc5_u8PrevStepToExecute = u8StepToExecute;

   /* Unit delay: SAD/SAD/SAD_runMainFunction/SAD mainfunction/u8PrevSelectedProfile */
   X_Sc5_u8PrevSelectedProfile = (sint16) Sc5_Switch;

   /* Unit delay: SAD/SAD/SAD_runMainFunction/au16PrevRawOrder */
   u16PrevRawOrder = Sc9_Consign;

   /* Unit delay: SAD/SAD/SAD_runMainFunction/as16PrevSlope */
   s16PrevSlope = s32RawIncrementValue;
   for (Aux_S32 = 0; Aux_S32 < 6; Aux_S32++)
   {
      /* Unit delay: SAD/SAD/SAD_runMainFunction/PrevIntegral */
      as32PrevIntegral[Aux_S32] = as32Integral[Aux_S32];

      /* Unit delay: SAD/SAD/SAD_runMainFunction/au16PrevDutyCycle */
      au16PrevDutyCycle[Aux_S32] = au16DutyCycle[Aux_S32];
   }

   /* # combined # TargetLink outport: SAD/SAD/SAD_runMainFunction/dsp_au16Pwm */
   Rte_Write_pseSolenoidPWM_au16Pwm((const uint16 *) DD_Sc6_PWM);

   /* Unit delay: SAD/SAD/SAD_runMainFunction/ab8PrevStepFinished */
   b8PrevIsStepFinished = IF_Sc1_b_IsStepFinished;

   /* Unit delay: SAD/SAD/SAD_runMainFunction/au16PrevTime */
   u16PrevTime = IF_Sc9_u16CurrentTime;

   /* Unit delay: SAD/SAD/SAD_runMainFunction/au8PrevStepIdx */
   u8PrevStepIdx = IF_Sb1_u8StepIdx;
}

#define SAD_STOP_SEC_CODE
#include "SAD_MemMap.h"

/*----------------------------------------------------------------------------*\
  MODULE LOCAL FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------*/

/**************************************************************************************************\
 ***  FUNCTION:
 ***      M_ControlStepExecution
 *** 
 ***  DESCRIPTION:
 ***      [COVERS: DSG_BFE_00033]
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
static void M_ControlStepExecution(void)
{
   /* SLLocal: Default storage class for local variables | Width: 8 */
   boolean Sc9_Relational_Operator1;
   boolean bIsNewStepStarted;

   /* SLStaticLocalInit: Default storage class for static local variables with initvalue | Width: 16
    */
   static sint16 X_Sc9_s16PrevSlopeValue = 0;

   /* Relational: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecution/Relation
      al Operator */
   bIsNewStepStarted = KE_NEW_STEP == eStepValidity;

   /* Relational: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecution/Relation
      al Operator1 */
   Sc9_Relational_Operator1 = KE_ON_GOING_STEP == eStepValidity;

   /* Switch: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecution/ManageTimer/
      Switch
      SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecution/ManageTimer/Switch: 
      Omitted comparison with constant. */
   if (stStep.b8IsPID) {
      /* Switch: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecution/ManageTim
         er/Switch
         # combined # Outport: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecu
         tion/u16CurrentTime */
      IF_Sc9_u16CurrentTime = KU16_ZERO;
   }
   else {
      /* SLLocal: Default storage class for local variables | Width: 16 */
      uint16 u16TimerOrigin;

      /* Switch: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecution/ManageTim
         er/SwitchIncrementOrResetTimer
         SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecution/ManageTimer/Switc
         hIncrementOrResetTimer: Omitted comparison with constant.
         # combined # Logical: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecu
         tion/ManageTimer/LogicalOperator1
         # combined # Logical: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecu
         tion/ManageTimer/Logical Operator */
      if (Sc9_Relational_Operator1 && (!(bIsNewStepStarted))) {
         /* Switch: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecution/Manage
            Timer/SwitchIncrementOrResetTimer
            SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecution/ManageTimer/Sw
            itchIncrementOrResetTimer: Omitted upper saturation
            SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecution/ManageTimer/Sw
            itchIncrementOrResetTimer: Omitted lower saturation */
         u16TimerOrigin = u16PrevTime;
      }
      else {
         /* Switch: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecution/Manage
            Timer/SwitchIncrementOrResetTimer
            SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecution/ManageTimer/Sw
            itchIncrementOrResetTimer: Omitted upper saturation
            SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecution/ManageTimer/Sw
            itchIncrementOrResetTimer: Omitted lower saturation */
         u16TimerOrigin = KU16_ZERO;
      }

      /* Sum: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecution/ManageTimer/
         Add
         # combined # Switch: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecut
         ion/ManageTimer/Switch
         # combined # Outport: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecu
         tion/u16CurrentTime
         SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecution/ManageTimer/Add: 
         Omitted lower saturation */
      IF_Sc9_u16CurrentTime = ((uint16) KUS_INCREMENT_TIME) + u16TimerOrigin;

      /* # combined # Switch: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecut
         ion/ManageTimer/Switch
         # combined # Outport: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecu
         tion/u16CurrentTime */
      if (IF_Sc9_u16CurrentTime < ((uint16) KUS_INCREMENT_TIME)) {
         /* # combined # Switch: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExe
            cution/ManageTimer/Switch
            # combined # Outport: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepEx
            ecution/u16CurrentTime */
         IF_Sc9_u16CurrentTime = 65535;
      }
   }

   /* Relational: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecution/ManageTi
      mer/Relational Operator
      # combined # Outport: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecutio
      n/u16CurrentTime */
   bIsTimerElapsed = IF_Sc8_u16StepDuration <= IF_Sc9_u16CurrentTime;
   if (bIsNewStepStarted) {
      /* SLLocal: Default storage class for local variables | Width: 32 */
      sint32 Sc30_DataScaling;

      /* # combined # Relational: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepEx
         ecution/New Step started/AdaptOrderType/StepPwm
         # combined # Relational: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepEx
         ecution/New Step started/AdaptOrderType/StepCurrent
         # combined # SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecution/orde
         rIn
         # combined # SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecution/orde
         rIn */
      if ((KU8_CURRENT_ORDER_TYPE == stStep.u8Order) || (KU8_PWM_ORDER_TYPE == stStep.u8Order)) {
         /* Reference of merge block: Merge2 SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_Co
            ntrolStepExecution/Merge2
            update of variable(s) associated with SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_
            12_ControlStepExecution/New Step started/AdaptOrderType/If Action
            Subsystem2/u8OrderType
            # combined # SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecution/o
            rderIn
            # combined # Unit delay: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlSte
            pExecution/u8PrevStepOrderType
            # combined # SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecution/o
            rderOut
            # combined # Unit delay: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlSte
            pExecution/u8PrevStepOrderType */
         Sc9_orderOut = stStep.u8Order;
      }
      else {
         /* Reference of merge block: Merge2 SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_Co
            ntrolStepExecution/Merge2
            update of variable(s) associated with SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_
            12_ControlStepExecution/New Step started/AdaptOrderType/If Action
            Subsystem1/KU8_NO_STEP_TYPE
            # combined # Unit delay: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlSte
            pExecution/u8PrevStepOrderType
            # combined # SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecution/o
            rderOut
            # combined # Unit delay: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlSte
            pExecution/u8PrevStepOrderType */
         Sc9_orderOut = KU8_NO_STEP_TYPE;
      }

      /* Multiport switch: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecution
         /New Step started/Adapt Step Target Value/DataScaling
         # combined # SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecution/orde
         rIn */
      switch (stStep.u8Order) {
         case 1: {
            /* # combined # SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecutio
               n/New Step started/Adapt Step Target Value/Rescaler */
            Sc30_DataScaling = (sint32) stStep.u8Consign;
            break;
         }
         case 2: {
            /* # combined # Product: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlSte
               pExecution/New Step started/Adapt Step Target Value/orderRescaled
               # combined # SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecutio
               n/New Step started/Adapt Step Target Value/Shift Arithmetic
               # combined # SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecutio
               n/New Step started/Adapt Step Target Value/u32FirstOrder */
            Sc30_DataScaling = (sint32) ((((uint32) stStep.u8Consign) << 15) / 100);
            break;
         }
         default: {
            Sc30_DataScaling = DD_Sc30_Constant1;
            break;
         }
      }

      /* Switch: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecution/New Step 
         started/Switch
         SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecution/New Step started/
         Switch: Omitted comparison with constant. */
      if (stStep.b8IsRamp) {
         /* Switch: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecution/New St
            ep started/Switch
            # combined # Reference of merge block: Merge1 SAD/SAD/SAD_runMainFunction/SAD mainfuncti
            on/TF_G_12_ControlStepExecution/Merge1
            update of variable(s) associated with SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_
            12_ControlStepExecution/New Step started/Switch
            # combined # Outport: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepEx
            ecution/New Step started/Ramp step characteristics computation/s32FirstValueForRamp
            # combined # Unit delay: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlSte
            pExecution/s32PrevFirstOrderValue
            # combined # SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecution/C
            onsign
            # combined # Unit delay: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlSte
            pExecution/s32PrevFirstOrderValue */
         Sc9_Consign = Sc5_u8SelectedProfile;
      }
      else {
         /* Switch: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecution/New St
            ep started/Switch
            # combined # Reference of merge block: Merge1 SAD/SAD/SAD_runMainFunction/SAD mainfuncti
            on/TF_G_12_ControlStepExecution/Merge1
            update of variable(s) associated with SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_
            12_ControlStepExecution/New Step started/Switch
            # combined # Unit delay: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlSte
            pExecution/s32PrevFirstOrderValue
            # combined # SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecution/C
            onsign
            # combined # Unit delay: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlSte
            pExecution/s32PrevFirstOrderValue */
         Sc9_Consign = (uint16) Sc30_DataScaling;
      }

      /* Switch: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecution/New Step 
         started/Switch1
         SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecution/New Step started/
         Switch1: Omitted comparison with constant. */
      if (stStep.b8IsRamp) {
         /* Switch: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecution/New St
            ep started/Switch1
            # combined # Reference of merge block: Merge SAD/SAD/SAD_runMainFunction/SAD mainfunctio
            n/TF_G_12_ControlStepExecution/Merge
            update of variable(s) associated with SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_
            12_ControlStepExecution/New Step started/Switch1
            # combined # Product: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepEx
            ecution/New Step started/Ramp step characteristics computation/slope
            # combined # Sum: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecut
            ion/New Step started/Ramp step characteristics computation/Sum */
         s32RawIncrementValue = (sint16) (((sint16) (((uint16) Sc30_DataScaling) -
          Sc5_u8SelectedProfile)) / ((sint32) IF_Sc8_u16StepDuration));
      }
      else {
         /* Switch: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecution/New St
            ep started/Switch1
            # combined # Reference of merge block: Merge SAD/SAD/SAD_runMainFunction/SAD mainfunctio
            n/TF_G_12_ControlStepExecution/Merge
            update of variable(s) associated with SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_
            12_ControlStepExecution/New Step started/Switch1 */
         s32RawIncrementValue = KS16_ZERO;
      }
   }
   else {
      if (Sc9_Relational_Operator1) {
         /* Reference of merge block: Merge SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_Con
            trolStepExecution/Merge
            update of variable(s) associated with SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_
            12_ControlStepExecution/Step execution continues/s32PrevRawIncrementValue */
         s32RawIncrementValue = X_Sc9_s16PrevSlopeValue;
      }
      else {
         /* Reference of merge block: Merge2 SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_Co
            ntrolStepExecution/Merge2
            update of variable(s) associated with SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_
            12_ControlStepExecution/No step executed/No step Order Type
            # combined # Unit delay: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlSte
            pExecution/u8PrevStepOrderType
            # combined # SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecution/o
            rderOut
            # combined # Unit delay: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlSte
            pExecution/u8PrevStepOrderType */
         Sc9_orderOut = KU8_NO_STEP_TYPE;

         /* Reference of merge block: Merge1 SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_Co
            ntrolStepExecution/Merge1
            update of variable(s) associated with SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_
            12_ControlStepExecution/No step executed/Motor power order shall be reset1
            # combined # Unit delay: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlSte
            pExecution/s32PrevFirstOrderValue
            # combined # SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecution/C
            onsign
            # combined # Unit delay: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlSte
            pExecution/s32PrevFirstOrderValue */
         Sc9_Consign = KU16_ZERO;

         /* Reference of merge block: Merge SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_Con
            trolStepExecution/Merge
            update of variable(s) associated with SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_
            12_ControlStepExecution/No step executed/Motor power order shall be reset */
         s32RawIncrementValue = KS16_ZERO;
      }
   }

   /* Unit delay: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ControlStepExecution/s16PrevS
      lopeValue */
   X_Sc9_s16PrevSlopeValue = s32RawIncrementValue;
}

/**************************************************************************************************\
 ***  FUNCTION:
 ***      M_ManageStepEvents
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
static void M_ManageStepEvents(void)
{
   /* Switch: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ManageEndingStep/Switch
      SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ManageEndingStep/Switch: Omitted comparis
      on with constant.
      # combined # Logical: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ManageEndingStep/Lo
      gical Operator
      # combined # Relational: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ManageEndingStep
      /Relational Operator
      # combined # Relational: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ManageEndingStep
      /Relational Operator1 */
   if ((KE_NEW_STEP == eStepValidity) || (KE_ON_GOING_STEP == eStepValidity)) {
      /* Switch: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ManageEndingStep/Switch
         # combined # Outport: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ManageEndingStep
         /b_IsStepFinished
         # combined # Logical: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ManageEndingStep
         /Logical Operator1 */
      IF_Sc1_b_IsStepFinished = bIsTimerElapsed;
   }
   else {
      /* Switch: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ManageEndingStep/Switch
         # combined # Outport: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ManageEndingStep
         /b_IsStepFinished
         # combined # Logical: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_12_ManageEndingStep
         /Logical Operator1 */
      IF_Sc1_b_IsStepFinished = KB_TRUE;
   }
}

/**************************************************************************************************\
 ***  FUNCTION:
 ***      M_SelectStepId
 *** 
 ***  DESCRIPTION:
 ***      [COVERS: DSG_BFE_00022]
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
static void M_SelectStepId(void)
{
   /* SLStaticLocalInit: Default storage class for static local variables with initvalue | Width: 8
    */
   static uint8 u8UnfilteredStepId = 255;

   /* # combined # Relational: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_111 step1/Relationa
      l Operator */
   if (KU8_NB_MAX_PROFILES_LIB <= Sc5_Switch) {
      /* Reference of merge block: MergeStepToExecute SAD/SAD/SAD_runMainFunction/SAD mainfunction/T
         F_G_111 step1/MergeStepToExecute
         update of variable(s) associated with SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_111
          step1/No Step to play/Constant */
      u8StepToExecute = KUC_UNDEFINED_STEP;
   }
   else {
      /* SLLocal: Default storage class for local variables | Width: 16 */
      uint16 Aux_U16;

      /* # combined # Relational: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_111 step1/Select
          Step To Execute/RelationalOperatorChangeCycle1
         # combined # Relational: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_111 step1/Select
          Step To Execute/RelationalOperatorChangeCycle */
      if ((((sint16) Sc5_Switch) != X_Sc5_u8PrevSelectedProfile) || (KUC_UNDEFINED_STEP ==
       X_Sc5_u8PrevStepToExecute)) {
         /* Reference of merge block: StepIndexToExecute SAD/SAD/SAD_runMainFunction/SAD mainfunctio
            n/TF_G_111 step1/Select Step To Execute/StepIndexToExecute
            update of variable(s) associated with SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_
            111 step1/Select Step To Execute/Init Step Id/Constant */
         u8UnfilteredStepId = KU8_ZERO;
      }
      else {
         if (b8PrevIsStepFinished) {
            /* Reference of merge block: StepIndexToExecute SAD/SAD/SAD_runMainFunction/SAD mainfunc
               tion/TF_G_111 step1/Select Step To Execute/StepIndexToExecute
               update of variable(s) associated with SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF
               _G_111 step1/Select Step To Execute/Increment Step Index/NewStepIndex
               # combined # Sum: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_111 step1/Select 
               Step To Execute/Increment Step Index/NewStepIndex */
            u8UnfilteredStepId = (uint8) (u8PrevStepIdx + KUC_INCREMENT_STEP_INDEX);
         }
         else {
            /* Reference of merge block: StepIndexToExecute SAD/SAD/SAD_runMainFunction/SAD mainfunc
               tion/TF_G_111 step1/Select Step To Execute/StepIndexToExecute
               update of variable(s) associated with SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF
               _G_111 step1/Select Step To Execute/Continue Step execution/u8PreviousStepIndex */
            u8UnfilteredStepId = u8PrevStepIdx;
         }
      }

      /* Sum: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_111 step1/Select Step To Execute/Fil
         ter StepId to Execute/AddThe OffsetOfFirstId */
      Aux_U16 = (uint16) u8UnfilteredStepId;

      /* # combined # Product: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_111 step1/Select St
         ep To Execute/Filter StepId to Execute/Product */
      Aux_U16 += ((uint16) (((uint16) Sc5_Switch) * ((uint16) KU8_PROFILE_SIZE)));
      u16StepBytePosition = (uint16) (Aux_U16 + ((uint16) KU8_INDEX_OF_FIRST_STEP));

      /* Switch: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_111 step1/Select Step To Execute/
         Filter StepId to Execute/Switch_ucStepToExecute
         SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_111 step1/Select Step To Execute/Filter S
         tepId to Execute/Switch_ucStepToExecute: Omitted comparison with constant.
         # combined # Relational: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_111 step1/Select
          Step To Execute/Filter StepId to Execute/RelationalOperator_bEndOfCycle */
      if (KUC_MAX_STEP_INDEX <= u8UnfilteredStepId) {
         /* Switch: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_111 step1/Select Step To Execu
            te/Filter StepId to Execute/Switch_ucStepToExecute
            # combined # Reference of merge block: MergeStepToExecute SAD/SAD/SAD_runMainFunction/SA
            D mainfunction/TF_G_111 step1/MergeStepToExecute
            update of variable(s) associated with SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_
            111 step1/Select Step To Execute/Filter StepId to Execute/Switch_ucStepToExecute */
         u8StepToExecute = KUC_UNDEFINED_STEP;
      }
      else {
         /* Switch: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_111 step1/Select Step To Execu
            te/Filter StepId to Execute/Switch
            SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_111 step1/Select Step To Execute/Filte
            r StepId to Execute/Switch: Omitted comparison with constant.
            # combined # Relational: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_111 step1/Sel
            ect Step To Execute/Filter StepId to Execute/Relational Operator
            # combined # Selector: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_111 step1/Selec
            t Step To Execute/Filter StepId to Execute/ucExtractedStepToExecute */
         if (KU8_NB_MAX_STEPS_LIB <= CFG_au8ProfileLib[u16StepBytePosition]) {
            /* Switch: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_111 step1/Select Step To Ex
               ecute/Filter StepId to Execute/Switch
               # combined # Switch: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_111 step1/Sele
               ct Step To Execute/Filter StepId to Execute/Switch_ucStepToExecute
               # combined # Reference of merge block: MergeStepToExecute SAD/SAD/SAD_runMainFunction
               /SAD mainfunction/TF_G_111 step1/MergeStepToExecute
               update of variable(s) associated with SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF
               _G_111 step1/Select Step To Execute/Filter StepId to Execute/Switch_ucStepToExecute
             */
            u8StepToExecute = KUC_UNDEFINED_STEP;
         }
         else {
            /* Switch: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_111 step1/Select Step To Ex
               ecute/Filter StepId to Execute/Switch
               # combined # Switch: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_111 step1/Sele
               ct Step To Execute/Filter StepId to Execute/Switch_ucStepToExecute
               # combined # Reference of merge block: MergeStepToExecute SAD/SAD/SAD_runMainFunction
               /SAD mainfunction/TF_G_111 step1/MergeStepToExecute
               update of variable(s) associated with SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF
               _G_111 step1/Select Step To Execute/Filter StepId to Execute/Switch_ucStepToExecute
               # combined # Selector: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_111 step1/Se
               lect Step To Execute/Filter StepId to Execute/ucExtractedStepToExecute */
            u8StepToExecute = CFG_au8ProfileLib[u16StepBytePosition];
         }
      }
   }

   /* Switch: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_111 step1/Switch */
   if (u8StepToExecute >= KUC_UNDEFINED_STEP) {
      /* Switch: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_111 step1/Switch
         # combined # Outport: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_111 step1/u8StepIdx
       */
      IF_Sb1_u8StepIdx = KU8_ZERO;
   }
   else {
      /* Switch: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_111 step1/Switch
         # combined # Outport: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_111 step1/u8StepIdx
       */
      IF_Sb1_u8StepIdx = u8UnfilteredStepId;
   }
}

/**************************************************************************************************\
 ***  FUNCTION:
 ***      M_StepPreprocessing
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
static void M_StepPreprocessing(void)
{
   /* # combined # Relational: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Is Input3 range
       valid */
   if (KU8_MAX_STEP_INDEX_0 <= u8StepToExecute) {
      /* Reference of merge block: StepValidityFlag_W SAD/SAD/SAD_runMainFunction/SAD mainfunction/T
         F_G_112/StepValidityFlag_W
         update of variable(s) associated with SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112
         /Invalid Range for inputs/Invalid Step Key Value */
      eStepValidity = KE_INVALID_STEP;
   }
   else {
      /* SLLocal: Default storage class for local variables | Width: 16 */
      uint16 u16StepDuration;

      /* SLLocal: Default storage class for local variables | Width: 8 */
      uint8 Sc20_Selector3;

      /* SLStaticLocalInit: Default storage class for static local variables with initvalue | Width:
          16 */
      static sint16 X_Sc21_Unit_Delay = 0;
      static sint16 X_Sc21_Unit_Delay1 = 0;
      static sint16 X_Sc21_Unit_Delay2 = 0;
      static sint16 X_Sc21_Unit_Delay3 = 0;
      static sint16 X_Sc21_Unit_Delay4 = 0;

      /* Product: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Preliminary Checks for Step 
         Parameters Content/Product1 */
      u16StepByte0 = (uint16) (((uint16) u8StepToExecute) * ((uint16) KU8_STEP_SIZE));

      /* Sum: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Preliminary Checks for Step Para
         meters Content/Step duration
         # combined # SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Preliminary Checks for S
         tep Parameters Content/Rescaler1
         # combined # SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Preliminary Checks for S
         tep Parameters Content/Shift Arithmetic
         # combined # SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Preliminary Checks for S
         tep Parameters Content/Rescaler
         # combined # Selector: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Preliminary Ch
         ecks for Step Parameters Content/Selector2
         # combined # Selector: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Preliminary Ch
         ecks for Step Parameters Content/Selector1
         # combined # Sum: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Preliminary Checks 
         for Step Parameters Content/Add3 */
      u16StepDuration = (uint16) ((((uint16) CFG_au8StepLib[u16StepByte0]) << 8) + ((uint16)
       CFG_au8StepLib[(uint16) (u16StepByte0 + ((uint16) KU8_ONE))]));

      /* Selector: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Preliminary Checks for Step
          Parameters Content/Selector3
         # combined # Sum: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Preliminary Checks 
         for Step Parameters Content/Add1 */
      Sc20_Selector3 = CFG_au8StepLib[(uint16) (u16StepByte0 + ((uint16) KU8_THREE))];

      /* Switch: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Preliminary Checks for Step P
         arameters Content/Switch
         SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Preliminary Checks for Step Parameter
         s Content/Switch: Omitted comparison with constant.
         # combined # Relational: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Preliminary 
         Checks for Step Parameters Content/bOutOfrangeStep */
      if (KU8_NB_MAX_STEPS_LIB <= u8StepToExecute) {
         /* Switch: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Preliminary Checks for Ste
            p Parameters Content/Switch
            # combined # Reference of merge block: StepValidityFlag_W SAD/SAD/SAD_runMainFunction/SA
            D mainfunction/TF_G_112/StepValidityFlag_W
            update of variable(s) associated with SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_
            112/Preliminary Checks for Step Parameters Content/Manage Step Parameters/Rescaler
            # combined # SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Preliminary Checks fo
            r Step Parameters Content/Manage Step Parameters/Rescaler */
         eStepValidity = KE_INVALID_STEP;
      }
      else {
         /* SLLocal: Default storage class for local variables | Width: 8 */
         uint8 u8StepOrderType;

         /* SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Preliminary Checks for Step Parame
            ters Content/Extract Step Order type */
         u8StepOrderType = (uint8) (Sc20_Selector3 & KU8_SEVEN);

         /* Switch: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Preliminary Checks for Ste
            p Parameters Content/boolStepParam
            SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Preliminary Checks for Step Parame
            ters Content/boolStepParam: Omitted comparison with constant.
            # combined # Logical: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Preliminary 
            Checks for Step Parameters Content/Logical Operator1
            # combined # Logical: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Preliminary 
            Checks for Step Parameters Content/Invalid Order type
            # combined # Relational: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Prelimina
            ry Checks for Step Parameters Content/Upper Limit
            # combined # Relational: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Prelimina
            ry Checks for Step Parameters Content/Lower Limit
            # combined # Relational: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Prelimina
            ry Checks for Step Parameters Content/Relational Operator4
            # combined # Relational: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Prelimina
            ry Checks for Step Parameters Content/Relational Operator3 */
         if ((KU16_ZERO == u16StepDuration) || (KU16_MAX == u16StepDuration) || ((KU8_PWM_ORDER_TYPE
           != u8StepOrderType) && (KU8_CURRENT_ORDER_TYPE != u8StepOrderType))) {
            /* Switch: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Preliminary Checks for 
               Step Parameters Content/boolStepParam
               # combined # Switch: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Preliminar
               y Checks for Step Parameters Content/Switch
               # combined # Reference of merge block: StepValidityFlag_W SAD/SAD/SAD_runMainFunction
               /SAD mainfunction/TF_G_112/StepValidityFlag_W
               update of variable(s) associated with SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF
               _G_112/Preliminary Checks for Step Parameters Content/Manage Step Parameters/Rescaler
               # combined # SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Preliminary Checks
                for Step Parameters Content/Manage Step Parameters/Rescaler */
            eStepValidity = KE_INVALID_STEP;
         }
         else {
            /* Switch: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Preliminary Checks for 
               Step Parameters Content/SameCycle
               SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Preliminary Checks for Step Par
               ameters Content/SameCycle: Omitted comparison with constant.
               # combined # Relational: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Prelim
               inary Checks for Step Parameters Content/Relational Operator7 */
            if (u8StepToExecute != X_Sc5_u8PrevStepToExecute) {
               /* Switch: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Preliminary Checks f
                  or Step Parameters Content/SameCycle
                  # combined # Switch: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Prelimi
                  nary Checks for Step Parameters Content/boolStepParam
                  # combined # Switch: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Prelimi
                  nary Checks for Step Parameters Content/Switch
                  # combined # Reference of merge block: StepValidityFlag_W SAD/SAD/SAD_runMainFunct
                  ion/SAD mainfunction/TF_G_112/StepValidityFlag_W
                  update of variable(s) associated with SAD/SAD/SAD_runMainFunction/SAD mainfunction
                  /TF_G_112/Preliminary Checks for Step Parameters Content/Manage Step Parameters/Re
                  scaler
                  # combined # SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Preliminary Che
                  cks for Step Parameters Content/Manage Step Parameters/Rescaler */
               eStepValidity = KE_NEW_STEP;
            }
            else {
               /* Switch: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Preliminary Checks f
                  or Step Parameters Content/SameCycle
                  # combined # Switch: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Prelimi
                  nary Checks for Step Parameters Content/boolStepParam
                  # combined # Switch: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Prelimi
                  nary Checks for Step Parameters Content/Switch
                  # combined # Reference of merge block: StepValidityFlag_W SAD/SAD/SAD_runMainFunct
                  ion/SAD mainfunction/TF_G_112/StepValidityFlag_W
                  update of variable(s) associated with SAD/SAD/SAD_runMainFunction/SAD mainfunction
                  /TF_G_112/Preliminary Checks for Step Parameters Content/Manage Step Parameters/Re
                  scaler
                  # combined # SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Preliminary Che
                  cks for Step Parameters Content/Manage Step Parameters/Rescaler */
               eStepValidity = KE_ON_GOING_STEP;
            }
         }
      }

      /* # combined # Relational: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Preliminary 
         Checks for Step Parameters Content/Manage Step Parameters/Relational Operator
         # combined # Reference of merge block: StepValidityFlag_W SAD/SAD/SAD_runMainFunction/SAD m
         ainfunction/TF_G_112/StepValidityFlag_W
         update of variable(s) associated with SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112
         /Preliminary Checks for Step Parameters Content/Manage Step Parameters/Rescaler
         # combined # SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Preliminary Checks for S
         tep Parameters Content/Manage Step Parameters/Rescaler */
      if (KE_NEW_STEP == eStepValidity) {
         /* SLLocal: Default storage class for local variables | Width: 8 */
         boolean Sc24_8Bit_Decoder_bit0;
         boolean Sc24_8Bit_Decoder_bit1;
         boolean Sc24_8Bit_Decoder_bit2;
         boolean Sc24_8Bit_Decoder_bit3;
         boolean Sc24_8Bit_Decoder_bit4;
         boolean bIsReleaseCtrlRaw;
         uint8 Aux_U8;

         /* Custom code: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Preliminary Checks fo
            r Step Parameters Content/Manage Step Parameters/ExtractParameters/8Bit Decoder/8Bit Dec
            oder << output code >>
            # combined # Reference of merge block: b8IsRamp_W SAD/SAD/SAD_runMainFunction/SAD mainfu
            nction/TF_G_112/Preliminary Checks for Step Parameters Content/Manage Step Parameters/b8
            IsRamp_W
            update of variable(s) associated with SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_
            112/Preliminary Checks for Step Parameters Content/Manage Step Parameters/ExtractParamet
            ers/8Bit Decoder/8Bit Decoder
            # combined # Reference of merge block: b8IsIfiniteStep_W SAD/SAD/SAD_runMainFunction/SAD
             mainfunction/TF_G_112/Preliminary Checks for Step Parameters Content/Manage Step Parame
            ters/b8IsIfiniteStep_W
            update of variable(s) associated with SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_
            112/Preliminary Checks for Step Parameters Content/Manage Step Parameters/ExtractParamet
            ers/8Bit Decoder/8Bit Decoder */
         {
            stStep.b8IsRamp  = (Sc20_Selector3 & 0x80) >>  7;
            stStep.b8IsPID  = (Sc20_Selector3 & 0x40) >>  6;
            bIsReleaseCtrlRaw  = (Sc20_Selector3 & 0x20) >>  5;
            Sc24_8Bit_Decoder_bit4  = (Sc20_Selector3 & 0x10) >>  4;
            Sc24_8Bit_Decoder_bit3  = (Sc20_Selector3 & 0x08) >>  3;
            Sc24_8Bit_Decoder_bit2  = (Sc20_Selector3 & 0x04) >>  2;
            Sc24_8Bit_Decoder_bit1  = (Sc20_Selector3 & 0x02) >>  1;
            Sc24_8Bit_Decoder_bit0  = (Sc20_Selector3 & 0x01);
         }

         /* Reference of merge block: u16Duration_W SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_
            G_112/Preliminary Checks for Step Parameters Content/Manage Step Parameters/u16Duration_
            W
            update of variable(s) associated with SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_
            112/Preliminary Checks for Step Parameters Content/Manage Step Parameters/ExtractParamet
            ers/u8StepDuration */
         stStep.u16Duration = u16StepDuration;

         /* Reference of merge block: u8Consign_W SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_
            112/Preliminary Checks for Step Parameters Content/Manage Step Parameters/u8Consign_W
            update of variable(s) associated with SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_
            112/Preliminary Checks for Step Parameters Content/Manage Step Parameters/ExtractParamet
            ers/Selector2
            # combined # Selector: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Preliminary
             Checks for Step Parameters Content/Manage Step Parameters/ExtractParameters/Selector2
            # combined # Sum: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Preliminary Chec
            ks for Step Parameters Content/Manage Step Parameters/ExtractParameters/Add */
         stStep.u8Consign = CFG_au8StepLib[(uint16) (u16StepByte0 + ((uint16) KU8_TWO))];

         /* [COVERS: DSG_BFE_00024]
            Sum: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Preliminary Checks for Step P
            arameters Content/Manage Step Parameters/ExtractParameters/Subsystem6/Sum
            # combined # Gain: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Preliminary Che
            cks for Step Parameters Content/Manage Step Parameters/ExtractParameters/Subsystem6/Gain
            1 */
         Aux_U8 = (uint8) (Sc24_8Bit_Decoder_bit2 << 2);

         /* # combined # Gain: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Preliminary Che
            cks for Step Parameters Content/Manage Step Parameters/ExtractParameters/Subsystem6/Gain
          */
         Aux_U8 += ((uint8) (Sc24_8Bit_Decoder_bit1 << 1));

         /* Reference of merge block: u8OrderType_W SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_
            G_112/Preliminary Checks for Step Parameters Content/Manage Step Parameters/u8OrderType_
            W
            update of variable(s) associated with SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_
            112/Preliminary Checks for Step Parameters Content/Manage Step Parameters/ExtractParamet
            ers/Subsystem6/Sum */
         stStep.u8Order = (uint8) (Aux_U8 + ((uint8) Sc24_8Bit_Decoder_bit0));
      }
      else {
         /* Reference of merge block: b8IsIfiniteStep_W SAD/SAD/SAD_runMainFunction/SAD mainfunction
            /TF_G_112/Preliminary Checks for Step Parameters Content/Manage Step Parameters/b8IsIfin
            iteStep_W
            update of variable(s) associated with SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_
            112/Preliminary Checks for Step Parameters Content/Manage Step Parameters/KeepPreviousVa
            lues/b8PrevIsInfiniteStep */
         stStep.b8IsPID = X_Sc21_Unit_Delay4 != 0;

         /* Reference of merge block: b8IsRamp_W SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_1
            12/Preliminary Checks for Step Parameters Content/Manage Step Parameters/b8IsRamp_W
            update of variable(s) associated with SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_
            112/Preliminary Checks for Step Parameters Content/Manage Step Parameters/KeepPreviousVa
            lues/b8PrevRampStep */
         stStep.b8IsRamp = X_Sc21_Unit_Delay3 != 0;

         /* Reference of merge block: u16Duration_W SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_
            G_112/Preliminary Checks for Step Parameters Content/Manage Step Parameters/u16Duration_
            W
            update of variable(s) associated with SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_
            112/Preliminary Checks for Step Parameters Content/Manage Step Parameters/KeepPreviousVa
            lues/u16PrevStepDuration */
         stStep.u16Duration = (uint16) X_Sc21_Unit_Delay2;

         /* Reference of merge block: u8Consign_W SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_
            112/Preliminary Checks for Step Parameters Content/Manage Step Parameters/u8Consign_W
            update of variable(s) associated with SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_
            112/Preliminary Checks for Step Parameters Content/Manage Step Parameters/KeepPreviousVa
            lues/s8PrevOrderValue */
         stStep.u8Consign = (uint8) X_Sc21_Unit_Delay1;

         /* Reference of merge block: u8OrderType_W SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_
            G_112/Preliminary Checks for Step Parameters Content/Manage Step Parameters/u8OrderType_
            W
            update of variable(s) associated with SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_
            112/Preliminary Checks for Step Parameters Content/Manage Step Parameters/KeepPreviousVa
            lues/u8PrevOrderType */
         stStep.u8Order = (uint8) X_Sc21_Unit_Delay;
      }

      /* Unit delay: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Preliminary Checks for St
         ep Parameters Content/Manage Step Parameters/Unit Delay */
      X_Sc21_Unit_Delay = (sint16) stStep.u8Order;

      /* Unit delay: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Preliminary Checks for St
         ep Parameters Content/Manage Step Parameters/Unit Delay2 */
      X_Sc21_Unit_Delay2 = (sint16) stStep.u16Duration;

      /* Unit delay: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Preliminary Checks for St
         ep Parameters Content/Manage Step Parameters/Unit Delay1 */
      X_Sc21_Unit_Delay1 = (sint16) stStep.u8Consign;

      /* Unit delay: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Preliminary Checks for St
         ep Parameters Content/Manage Step Parameters/Unit Delay3 */
      X_Sc21_Unit_Delay3 = (sint16) stStep.b8IsRamp;

      /* Unit delay: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Preliminary Checks for St
         ep Parameters Content/Manage Step Parameters/Unit Delay4 */
      X_Sc21_Unit_Delay4 = (sint16) stStep.b8IsPID;

      /* Outport: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/Preliminary Checks for Step 
         Parameters Content/u16StepDuration
         # combined # Outport: SAD/SAD/SAD_runMainFunction/SAD mainfunction/TF_G_112/u16StepDuration
       */
      IF_Sc8_u16StepDuration = stStep.u16Duration;
   }
}

#endif /* SAD_C */
/*----------------------------------------------------------------------------*\
  END OF FILE
\*----------------------------------------------------------------------------*/
