/**************************************************************************************************\
 *** 
 *** Simulink model       : eCS_Algo_Simulation_2015b
 *** TargetLink subsystem : eCS_Algo_Simulation_2015b/SAD
 *** Codefile             : SAD.h
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2022-03-18 16:06:41
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : AUTOSAR
 *** AUTOSAR version                          : 4.2.2
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : enabled
 *** Logging mode                             : Do not log anything
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Loop unroll threshold                    : 5
 *** Shift mode                               : automatic
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : 31 chars
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : enabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 6
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\Program Files\dSPACE TargetLink 4.2\Matlab\Tl\Con
 ***                                            fig\codegen\cconfig.xml
 *** Root style sheet                         : C:\Program Files\dSPACE TargetLink 4.2\Matlab\Tl\XML
 ***                                            \CodeGen\Stylesheets\TL_CSourceCodeSS.xsl
 ***
 *** TargetLink version      : 4.2 from 14-Oct-2016
 *** Code generator version  : Build Id 4.2.0.26 from 2016-10-17 16:31:48

\**************************************************************************************************/

#ifndef SAD_H
#define SAD_H

/*----------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------*/

#include "Rte_Type.h"

/*----------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------*/
/******************************************************************************\
   MERGEABLE_MACRO: mergeable preprocessor macros
\******************************************************************************/
#define DD_Sc38_Constant1 ((sint32) 0)

/******************************************************************************\
   MERGEABLE_MACRO: mergeable preprocessor macros
\******************************************************************************/
#define KU16_MAX_PWM ((uint16) 32768) /* Description: Max PWM Value with a resolution of 2^-15 */

/******************************************************************************\
   MERGEABLE_MACRO: mergeable preprocessor macros
\******************************************************************************/
#define KB_TRUE ((boolean) 1)
#define KE_INVALID_STEP ((uint8) 0)
#define KE_NEW_STEP ((uint8) 1)
#define KE_ON_GOING_STEP ((uint8) 2)
#define KU8_CURRENT_ORDER_TYPE ((uint8) 1)
#define KU8_INDEX_OF_FIRST_STEP ((uint8) 4)
#define KU8_MAX_STEP_INDEX_0 ((uint8) 8)
#define KU8_NB_MAX_PROFILES_LIB ((uint8) 4)
#define KU8_NB_MAX_PROFILE_LIBRARY_0 ((uint8) 4)
#define KU8_NB_MAX_STEPS_LIB ((uint8) 16)
#define KU8_NO_PROFILE ((uint8) 255)
#define KU8_NO_STEP_TYPE ((uint8) 7)
#define KU8_PROFILE_SIZE ((uint8) 12)
#define KU8_PWM_ORDER_TYPE ((uint8) 2)
#define KU8_SOLENOID_NB ((uint8) 6) /* 
   LSB: 2^0 OFF: 0 MIN/MAX: 2 .. 6
   Description: Number of controlled solenoids */
#define KU8_STEP_SIZE ((uint8) 4)
#define KUC_INCREMENT_STEP_INDEX ((uint8) 1)
#define KUC_MAX_STEP_INDEX ((uint8) 8)
#define KUC_UNDEFINED_STEP ((uint8) 255)
#define KUS_INCREMENT_TIME ((uint8) 1)

/*----------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------*/

/******************************************************************************\
   MERGEABLE_GLOBAL: mergeable global variables (RAM) | Width: 16
\******************************************************************************/
extern uint16 u16StepByte0;
extern uint16 u16StepBytePosition;

/******************************************************************************\
   MERGEABLE_GLOBAL: mergeable global variables (RAM) | Width: 8
\******************************************************************************/
extern uint8 au8FollowingCycle[4];
extern uint8 au8LastStepidx[4];

/******************************************************************************\
   SLGlobal: Default storage class for global variables | Width: 8
\******************************************************************************/
extern uint8 Sc1_u8ExecutedProfile[6];
extern uint8 Sc1_u8ExecutedProfileOld[6];

/******************************************************************************\
   SLGlobalInit: Default storage class for global variables with initial value | Width: 16
\******************************************************************************/
extern uint16 Sc9_Data_Store_Memory[6];

/*----------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------*/

/******************************************************************************\
   GlobalStep: Default function class for not static model step functions
\******************************************************************************/
extern void SAD(void);

/******************************************************************************\
   ARRunnable4: Default function class for AUTOSAR runnables
\******************************************************************************/
#define SAD_START_SEC_CODE
#include "SAD_MemMap.h"

FUNC(void, SAD_CODE) SAD_Init(void);

#define SAD_STOP_SEC_CODE
#include "SAD_MemMap.h"

#define SAD_START_SEC_CODE
#include "SAD_MemMap.h"

FUNC(void, SAD_CODE) SAD_runMainFunction(void);

#define SAD_STOP_SEC_CODE
#include "SAD_MemMap.h"

#endif /* SAD_H */
/*----------------------------------------------------------------------------*\
  END OF FILE
\*----------------------------------------------------------------------------*/
